apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname nzbget
  namespace: media
  labels:
    app: *appname
spec:
  releaseName: *appname
  chart:
    spec:
      chart: *appname
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 6m
  values:
    podLabels:
      app: *appname

    image:
      repository: ghcr.io/k8s-at-home/nzbget
      tag: v21.1
      pullPolicy: IfNotPresent
    
    # -- environment variables.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: "${TIMEZONE}"
    
    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 6789
        type: ClusterIP
    
    persistence:
      config:
        enabled: true
        existingClaim: "nzbget-config-volume"
    
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume1/media
        mountPath: /media-nfs
      downloads-k3s:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume2/downloads-k3s
        mountPath: /downloads-k3s
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume2/downloads
        mountPath: /downloads

