apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname librespeed
  namespace: utilities

spec:
  releaseName: *appname
  chart:
    spec:
      chart: *appname
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    service:
      main:
        primary: true
        annotations:
          metallb.universe.tf/address-pool: dev-infra
        ports:
          http:
            port: 80

    image:
      repository: linuxserver/librespeed
      tag: version-5.2.4
      pullPolicy: IfNotPresent
    
    env:
      TZ: ${TIMEZONE}
      PUID: "1001"
      PGID: "1001"
      PASSWORD: thekaocloud
      CUSTOM_RESULTS: false
      DB_TYPE: sqlite
      DB_NAME: librespeed
        #DB_HOSTNAME: ${RURI_ADDR}
        #DB_USERNAME: librespeed
        #DB_PASSWORD: 
        #DB_PORT: 3306
    
    ingress:
      main:
        enabled: false
    
    persistence:
      config:
        enabled: false
        existingClaim: librespeed-config-volume
