# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_MARIADB_PASSWORD: ENC[AES256_GCM,data:c0UCBEJy2wc69xW4dXhv0+rdkw==,iv:O7+cAjZb/36o2ZBRgHnXpLj2GJtp8FSoTWw8YWWeEOk=,tag:ejCvSPj/jgPxLRNuyjBHLw==,type:str]
    SECRET_MARIADB_REPLICATION_PASSWORD: ENC[AES256_GCM,data:w/To+EuSfVlodCpD6DwJRg7QXo9bzEaf4ngnnOY=,iv:B+eMHmT5lSN5g0/SP2iMJe89K4dqt8+TWLIrMyl4BUk=,tag:87sF/ISnpsiM2xoLl5BdpQ==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:kbxQ1j7vVYr7HUEm5/QINFkvsgXs0SbqcOg6kffOGmrJWUdPAw==,iv:K0UdUfIjSkCN4b//giU+amiumkx76ral8Xpd9+nF4G0=,tag:8y7tKx+HUCaz6qc8oDIIFw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:zxFbN3M9ky2XLlco4zS41ulZFE2kRro=,iv:GPvQzbQwIJgUqYAnWVoQmj6l4VSU8IRYjpF2IecMc/o=,tag:xBY9PQO7kmiv7OddXuOOfQ==,type:str]
    SECRET_PROD_DOMAIN_MGO: ENC[AES256_GCM,data:/nUFkSZwW2zbsyBVOSAR,iv:gmCbpjQ2PAa2aUwGCzRIJnl96HsoacgyNph7MI0Z3tQ=,tag:ox73cCS+p8WaPRK0EZ7DyQ==,type:str]
    SECRET_PROD_DOMAIN_KAOFAMILY: ENC[AES256_GCM,data:n4kBuYb29DtTnw==,iv:204pfvJS9FzsVQEXsqoYlltQmhPx+zIRJ0cd2fpWetk=,tag:AXO67x/JgZXxTnpl2GNcuQ==,type:str]
    SECRET_PROD_DOMAIN_KAOFOUNDATION: ENC[AES256_GCM,data:lUYmRBQ21rt4VUucCOo=,iv:sH1ayfp+alfafBskYrY70CO+lwGs6f4Norzq2EQREEY=,tag:pEMr4c4D9Lq522EOw54nsw==,type:str]
    SECRET_DEV_DOMAIN: ENC[AES256_GCM,data:yddp2TUDS+a5seiiJqo=,iv:SSWJtBZF7va9SsmpYHfl3fdYIePtooDcnJeo+07N0c4=,tag:KosOj7AYmNP3ptdtYIEdRA==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:h5ActbdrA1hNcpU=,iv:rfiqKMast/SBz5/PmVk+BzW8Bfghzmx8rYot17iNV0o=,tag:tXpyqVzlxsxixb7qwk/YOg==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:5gH+wjdh4RKV/Ss=,iv:VFqCCrLZap4daOxjpC4vpwUy83GJcBOzxrDt19xYvxo=,tag:V3LT6R2CzT206dneU20Btw==,type:str]
    SECRET_LDAP_PASSWORD_AUTHELIAUSER: ENC[AES256_GCM,data:56wNdTeBLJqwJlboyNc=,iv:GzHWV3H41pPLKBu1MJOO6a2ZfCQ8IEPIDCFCyJ3oV6A=,tag:Kq53QXNseXGFcCmzijHtKA==,type:str]
    #ENC[AES256_GCM,data:MhKKjo2Cn2jpd8udH7zQYwDWYYNAA5sSFaw6TSpPrczusYzJBo/35Xz3h6UrQXb9psHOfHs4pIK9dOH1Tw==,iv:qawnrQDXkpXOI1cJ3WZJvnahHDlTBueFsBmQhSFxsBY=,tag:o7l9xlK9qXMJm0FTvdYw3A==,type:comment]
    SECRET_TEST_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:u4JC1rUVvxgkTKv4wIxGuJHM0Nad0n0SD+9E1SHt2g9ZXlaFzkyVmsMiPOVWAz3/vw24acXuBzW9mKtkpS5HSw==,iv:moWu6hYVkUUxjq2w3+0qQNfGbYFqfcoiGOA+AJNIoSk=,tag:s7lRVG97aJlNY5TsL2wBTQ==,type:str]
    SECRET_BOOKSTACK_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:yC2PH7thhcn5rYJAkhHkOp2kB1mWeYl/atFXK7395EFp6R94emY0KDfoNNVyem/RgKlTywga6P/q9Z455BTMdA==,iv:YAQyRHEf+KhdzozNPYyP/3nAQAYHY5knvYd4YWwC9fM=,tag:ssTuI4GSmAiN9Fq9OrfrPA==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:wJjFV/9SPCRlayxsL5h8LX+09u1+QYlSP0GYmV2r/MRDwhdwEPK8uHr4eOu80CoIjgW5T7a1aaBsGuwBHs09FQ==,iv:oQMsbELQnCsdIJ5oVRRzngvfr/t+XauAHr0eO47uUd0=,tag:TmhiLQ9T5ueqPqPLoTkvHQ==,type:str]
    SECRET_VAULTWARDEN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:BCRiClwOts0gQhEaWaH0AVhwPhj2ZuWQ5o4iMCHDbQv3mibBKP7Mwta/aSxJPjkOLovqDS597DOi3/2qaEQ22g==,iv:nhnAWvWJeNwjm81sPnzRpz1AHMQ3qq41DJ7uNhcchn0=,tag:nHQYPfbeORM8dxHbx1UweA==,type:str]
    SECRET_MINIO_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:gNmjJOQsMiBr9rCXJQ7xRUc0T+oNklllGLAJOqVfTXao/A7t0hJJc0UQ2xjXirX/k+1Ak+rDA2qpzP0jU6lFMw==,iv:ULq17G/bUT94hlnto2TokbT3iJiIlQcb4z31bE5cPDk=,tag:N5eiSMgvoGQrTBabMYeXYQ==,type:str]
    SECRET_LDAP_ROOT_PASSWORD: ENC[AES256_GCM,data:Hc0MdZUkzdGk,iv:IdvLikj3+6DWTLZwdFj4HshS3uf4OO3YXowUI99J8Q0=,tag:oKJK5oGjNV7xjaB0TNLQrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZjVpdUlJdGZFTittMEI2
            cngxS3pVdzJtcnBQMVA1QjB1dHBIdU51NTNBCnZRQWNGT2wwZExMeHlWcHNWcVhP
            Q0E4b1V0WkVUa1NaNGJOZUxlMWhjM1kKLS0tIDRFeUtNdHMyMlorWGhMdytPTnc2
            M1NuMU1MVVFUQjM1NmFwS1hsZmlaNWsKbBJQeHvi7viM/g+Vebe4d5eVW2M7ty+1
            NNCP5uLZR9pjZr0noqYb5ai/DJffk0GjJxH2GY/yskhMaXFUXOFhEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T02:04:26Z"
    mac: ENC[AES256_GCM,data:myNgiToybqzg0NbckA6l8w1WBTIwXFXbI6vONCk+iDRqRdeOahYymDOXk+ovWglCS0q85U/i62WYMuA8+fDGpWAM/qchwwOGCqoAkJSoIHCs/B9/Y98J5dBmVdtCYmLQ/dwx3pDuFhow1LHZxfChzvvPTuSDXmqWHnaC7zWsBAA=,iv:jRp/af0JRxEEHe9NMWFeabb7u3XSuLJ9LPUD5kkEIn0=,tag:6pCPfMvmEUIvWIkE4zifHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
