# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_MARIADB_PASSWORD: ENC[AES256_GCM,data:x301UULQB5YCt45iMuj9Nb+tBg==,iv:6F0FLYrIzSKOUYWNfvRZhYuB44Dr03jIqpbFsWZXd9Y=,tag:bxnY5+2Mi8tHTMQulTOG8g==,type:str]
    SECRET_MARIADB_REPLICATION_PASSWORD: ENC[AES256_GCM,data:bGYfaOZOQpmczyORL5U/atIIxs4xyu95UkMP7CQ=,iv:D4thl0s0MNUoyqNzzJk6J2mCfFdoRC+Sloc5t9tfhms=,tag:qc6uo9PTVWeDNsYqOE1xaQ==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:Zzh45h5KMp6mn+vAkfWWu+TJFmdmz5T8tUr3g1Oog0Lz1DWNpA==,iv:9cZmNlYVcfRgF07NW3+tv+LS4YQE4oW+r8nfazscd8c=,tag:xUhGvBylXpfGE1b5l/9vhg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Cy0EyQk10O121QNzCsXroJeZH+0hnUY=,iv:WvhmaM4ujEdFm1qzQyqKtTk9cyuDprpai9Rsc0K31J4=,tag:zMUmg0Uiy2x2tZtvEtWV9A==,type:str]
    SECRET_PROD_DOMAIN_MGO: ENC[AES256_GCM,data:saE1Ig9eJyvP9U0MCAYm,iv:1jlJhHDpJlp/lRhaj+qDHadiB1lSS6etg3eIcb92tqw=,tag:qdbfgeOn2l4aSYswuljB/Q==,type:str]
    SECRET_PROD_DOMAIN_KAOFAMILY: ENC[AES256_GCM,data:uTLu39BC/Ivctg==,iv:eaZ46ZcdOgDIaDzUrJ/2qnCtDfTtUPk1djeESk+dOQc=,tag:6t+m2XNKmh1zpdMqvOmbUw==,type:str]
    SECRET_PROD_DOMAIN_KAOFOUNDATION: ENC[AES256_GCM,data:p7aykwrUl5Ve5zHso14=,iv:H7TjxyJjzvIkhNaswzqTxtS8I+G6vvxBWggj5axpMXg=,tag:qa3sE7QPbfC5/YDO1VxZ7Q==,type:str]
    SECRET_DEV_DOMAIN: ENC[AES256_GCM,data:p8MH//yzbLvoOngsF98=,iv:oIcHy7Tk1t0/BWkSlqf5rYsYVimg8ehxyJf/Wu0khWQ=,tag:54D/nYD9w6SrTdEdOPN/DQ==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:mllehF/j93f5VKs=,iv:IhLKcQPKb5X96GCxBE/NyRm39mx2OWZ9JlRkWhLv7Jc=,tag:dGgXDhW6J7YWVv/qBYkd3Q==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:BA8n0Ki5UCW/a4k=,iv:akwW46d0OstyqACilb2LZm6KBFJ3OXZG7UQiAlG48OA=,tag:/9v1FmPnyQc+XbCnTH+ynQ==,type:str]
    SECRET_LDAP_PASSWORD_AUTHELIAUSER: ENC[AES256_GCM,data:4dpLG7HvCJ5mKq+AnCs=,iv:8ns1UcG/KL1qE+PMy3y9MviO1x7meB7RbZGtapYZKRg=,tag:6veAW+x5LuagfRxJ6a39lw==,type:str]
    #ENC[AES256_GCM,data:/qsNK2laH8cSAmXQqgtTP7GsAbbWzJkRXxv5dWKtLpCBXBCXMJwJORmtMwKS4Ahq8dmpupAfRNUVzmwLEg==,iv:WgkfQsnO+KnVYyD5ES59bvus1dV3O3lAdHZ9LmA9BwU=,tag:5e1zHCcgq5ZyPtja8W8ALA==,type:comment]
    SECRET_TEST_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:t+3IktSLbufQlMCsvI3VMQK52kJI7N3w67uPFy3xAcoAShN/FjLwFVYzbSst6+RvbShcpmUwnnO3WWHDcHIIZA==,iv:3CZH6oVawMckK0l57t42cLitoP8tSd3w4IHBZ3A925g=,tag:ZM81TVkZ1ENoEzSPet8n8A==,type:str]
    SECRET_BOOKSTACK_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:8b4SWCDccQy1YJ5ugXbtqFSi6wbt+BZwrPxRDn3ezBigpwk7KAyVuNOa1D+tZ8kbmN2BSKWURmpaS4r6TeYItA==,iv:j6anVEAoVIUToB2w9X/9rhkl0pKo/EhdWYelibLsk5U=,tag:j3V4egeNetl94Owe48mKig==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ZV86NfhCsEduf7K+FlXMO0ijGjvczgvHOz0/yJzpvILUx1GxcMmkdp+t49J+OYZ6eeORzAvFQH6RqeiKX5FMGA==,iv:mkrMDegqDJfk9y51AdEWEWI2nJI9PuUUyT6Y4hD5gHw=,tag:BVm6zxfb9fK5ibwGaQmUcQ==,type:str]
    SECRET_VAULTWARDEN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:3e/+sPA9U9Psveaz3p1jUKrOXw7ToUmuY1UNLhMjKYU0G+QE+uTEm1fSXdSKHzlEwU2zO3Rx3bSok8trCIYjGQ==,iv:voUIMgmpfa3BI7aUeMMnEVAA9ZvyRXMXliyfq80GI/A=,tag:YPtf7c8qH4mh1G+Hwa1B5w==,type:str]
    SECRET_MINIO_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:8XJSX9YRX/2mKgN36cvaLhjiomzdafZm0vtgWjzvGNah+OZSB/O0Dhu1EowLiHi7VihkO4MLp2QE5V7Tdr8Ddg==,iv:IzQ4XPUjPLAnl6q5f6NOc5CvMB79QChJ/6SlAOo5Y5s=,tag:jJFWBDWAZHhoV7w+CxxuyA==,type:str]
    SECRET_LDAP_ROOT_PASSWORD: ENC[AES256_GCM,data:9tfwRVxxdPw2,iv:I2lF+yOxZnPt5dG1e2EhpmbvE8DGYqlrxtML6PaP0BA=,tag:ZfSPMuoheqlaq+DnxAE4Rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIa0Z1b3p6Nkdtamx3UmNI
            aXlmSWtGcVlXT1IyL0FCZTJsbHpuRjQ2eFdNCllUZ0FRR0tuRjJQUi9leTVacXp5
            K2tGUUJjV25lMWZab3k0bmRHbDlOalkKLS0tIHI4NTM1amFXdzJjK1JHRXdhc0Fx
            am1yQ1dUS2FSL3JtMUxKSHFIczdhOE0KZ+QZwXT2OnSMporKxuC5ElqNA7mGXq9K
            51JkNjhdDDMz1YNmcOxfCVzIF1+DkufsCnCVIKXjceQAOLiDj/dhgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T02:06:32Z"
    mac: ENC[AES256_GCM,data:DteMbYLbyaD/evNtHskUW/lCyv5BFatSSMHFA0HNpkrwJPIVH0Bw9DscsR2YWr41xPVGHFDsbyQLWvBrUZFnEV2nUOIgIcO8ugAb/3snk1JGmvXOVgoUSLALoEmbAbxQ5nrzrEfyZjbB0FmgkvMzXDUphwAoOcXTvz8JpnbIvSI=,iv:VtR3c200zEZieMWDySBD3j15lCaecOVr63ptWzfdPZ8=,tag:yLk/I9ea7q2x0bg6pyIgow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
