# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_MARIADB_PASSWORD: ENC[AES256_GCM,data:Fnvq079UmOXPz6IujJUnn273FA==,iv:LLrJXgt5KkiUGs3ejtVy4NqIvBP0YLEdgU4Xjpp1QV8=,tag:ppBks+DTN+/BrNEPq3fVZw==,type:str]
    SECRET_MARIADB_REPLICATION_PASSWORD: ENC[AES256_GCM,data:toTp87wxFVOMELMtNaPn8V875uB45NsS61L/NDw=,iv:qDzqGa6vFayh6Rc5V6jGMqYMotvEpdMyYSSWa8+P8+M=,tag:dgrloGLVYIOryEcTKJA6ug==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:Hdp1XeyzGVfPUVeghehHHJlPyfN6G/aQkKHxisQVnsmn/VaqBQ==,iv:0VoSaF0dakRZ0USX92iTyjM2GiNaleiUX6C934iLk9I=,tag:u9lsywTNSjZXLjLHuv5dBw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:QijFDjjFzbNuifo1xh33dDEl/PG5CPw=,iv:n2uM6HbapLmdcw7fLWJR7wOND0vnbKqW1tT+HwlZcHo=,tag:+8GS+BLA5j3ken9Pk1iswA==,type:str]
    SECRET_PROD_DOMAIN_MGO: ENC[AES256_GCM,data:FU7yCdNXvRQTNaWiNpoW,iv:rv2ssZGe3X2t3wjQ12vLH0RwFKtcNKI6/i5Sv+FlI2o=,tag:xqRJpsjKWOfW5rKyXk1Dmw==,type:str]
    SECRET_PROD_DOMAIN_KAOFAMILY: ENC[AES256_GCM,data:8ZQQkmE4cCA5ig==,iv:xI37Kv12kMdd75/reSKOIiWpA/0h9BjkRB/tFE8m/+M=,tag:DxfeMtsbzcNggxC3/ILZrQ==,type:str]
    SECRET_DEV_DOMAIN: ENC[AES256_GCM,data:uwlgJig7ZumRTTm1f9Q=,iv:Z2Ij1InjYuZU+glSGjJfA/7bUe9pj8KvasWT5hc2LM0=,tag:BPyfG04mKHelYiI+Uw/h2Q==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:I+62VhOJnkv2f/U=,iv:+mbln5tuNSk9HnPKlEHWvpv0EnkArBmfidGouoivpUU=,tag:bGnBu1qGtwwayEiOwSZp+w==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:ZtabrojFq7eJUUg=,iv:/RE4Yc06bbYgTCVUDXGcupq0MKp/QTzMFL9F8qcToio=,tag:Hw4T32n1tjqw8dcHepWskA==,type:str]
    SECRET_LDAP_PASSWORD_AUTHELIAUSER: ENC[AES256_GCM,data:Lcr281Ays51muf/nBE8=,iv:OqiyG6k8A7QISVYSvDJ/Dk0AEBarzob8griilIHFTaY=,tag:Et+LCr2TTa7bgwElsr4G3w==,type:str]
    SECRET_OIDC_ISSUER_URL: ENC[AES256_GCM,data:nQz5Q+0Y2EJWzsglHd4P8aVPzSKu/YzQyTylVMKcvxi6EzatvA==,iv:7Kv0+HPnyOcPH6G/Dx2NWN4HKaTwvoxkCXwDeloO+fs=,tag:mZbVegtbk+hBUSFfMO6TSQ==,type:str]
    SECRET_BOOKSTACK_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:IODHKTVxhWb932+MzWiHRKKsJkOcwtPA6ZfbGliDcogDzoJNXX1312HRV2SdZdVAMkBZ9WshkQ64SgEtwur8BA==,iv:vaUMN2auSkAIV8CsEQrfADe1c3gzxRhNR+2nTV0Qltc=,tag:ZUX44uP1NEH8nCbcuB9+3g==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:mY+wRpI2Nloc8C4t2nadcLPfHx93bHMip5VYF7xXdc13rYx1+aoQPnXnlOoUpCEtVFsKZAX8O9m/x+8dMT7fgA==,iv:E4wQoGFmWDis7G+rVpU30kJ0kYpxmIFlkDmJ4c42DDQ=,tag:cSIX8wY4IC1pWSCePORsOQ==,type:str]
    SECRET_VAULTWARDEN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:WngZz2EhtKDdVFB9nbL5YMoGkox+lsnhs+RUd7vlFM25UakEjpjFoEBHe/PF9SucgMju6WjoTrf0rGH/HAvCRw==,iv:ymYJyudz5cBE+sgm9ZxbdamfShyN+2zqz6H5e82krM4=,tag:fki+pUdBW18mcLFZMDbW/w==,type:str]
    SECRET_MINIO_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:7v1R7DV1dlEoYCTAuvBMvgrRcmdjN9uZD8/KpzCdcnj7dsfbq2xQhPqhvuIvEj1usHaTyGS2P36bKxpkepQvWw==,iv:XDuoplbsv2RenyMwlTN0IjtkOUs+3OLRlnPI0AbLylI=,tag:KA8E+/fDxlFwz2frggps9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZExtMzRTVGwrZWJmR3Bt
            WmlSRnVvUzl4cE96MWs2UnlpS3JLWjIxdGdVCml6NkN1RnA1NWFmMjNOZXhzVkRM
            TW5aK0p4UzYrdkN6UVRYMWpBZllXWW8KLS0tIG8xQXNmU0NGYlcwc05YR0owOWI3
            RTQ3OEFkakkxV1dmTkhRN0cxYXUyeDgKhmTvjIiOKOkzubeB4vgVaA9rBEgIRLMA
            Kjf4EWx1ECFSmvd9ghUbT/lHq4qY7iBqYTDAYuYFaWUcZgijjP+WhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-21T21:07:57Z"
    mac: ENC[AES256_GCM,data:MEKEYnIxCOfMJnirehKHqEMeEfh7vo0CitNc5VwpJreI9KulWKzaZG9JepUZ12JEDtH90UG21N9X/vxT5DM1SBg+fe9K+N2F7eyKc91pnYCEcCbxC0XKKyEps4HlJDlRYpfwnzwjRpqbxIIvAljClFxKG3XG3aXgGd1uBiaEfwQ=,iv:dTClXuHEM0wDGB5ftVGDMrGvykEivRBJBG42lZGEILE=,tag:XZkUu4IQofewTVV/9UVxmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
