---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app vaultwarden-ldap
  namespace: utilities
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: docker.io/vividboarder/vaultwarden_ldap
      #repository: docker.io/alexta69/metube
      tag: latest
    env:
      TZ: "${TIMEZONE}"
      CONFIG_PATH: "/config.toml"
        #    envFrom:
        #      - secretRef:
        #          name: *app
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
    service:
      main:
        enabled: false
         #       ports:
         #         http:
         #           port: &port 80
        #    probes:
        #      liveness: &probes
        #        enabled: true
        #        custom: true
        #        spec:
        #          httpGet:
        #            path: /
        #            port: *port
        #          initialDelaySeconds: 10
        #          periodSeconds: 10
        #          timeoutSeconds: 1
        #          failureThreshold: 3
        #      readiness: *probes
        #      startup:
        #        enabled: false

    persistence:
      config-toml:
        enabled: true
        type: configMap
        name: *app
        subPath: config.toml
        mountPath: /config.toml
          
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 128Mi
