apiVersion: v1
kind: Secret
metadata:
    name: tautulli
    namespace: media
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Wo+C09Egp8M3NOA5oUIUNCRAvztVFQLu5g9chEsyT66PFR/n7byw,iv:cREpZlVsaJnhcK97kk12gmf5mIl8m6rZ9vlYw+GhXjM=,tag:1+DWgRoLo2+pgOekd8h2DQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Pt4WTEvcrJaZCfPLMRRhkwUHSFNMrSJir70+M8aCwO+fx6FKtE6VMuY9yGgzCSzFfTA5QbnC4KjBuToycAwCug==,iv:Q+hm7Mm+5rRDfLKyBMjKAaB7Kl2aEL7CdXd/cW5rTJ0=,tag:2TLNlcvWj5Z8x4WD8TAYUw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:PaYBvg0r,iv:0cf04X5ZR3yGsVFQ12cfNSSfLd5849Yz+yNGZMB+FzI=,tag:VymOKxcOocC4Qn4nlSS+kw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uzd7HBAUIMIZPOlLGSJH+jKBRvoD,iv:UyKykKH40AEmbbrmbdQZsaoXQGwfKAqd7/Lu3rIOI2s=,tag:+s0FfM/NAE9B8hxz2185Lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWjBIM1hqMmI3UW1xRE9Y
            cGg3ZVJNdDJjVGV4b2VIZUNvdXBGTWIycG04CmpTek5zU2VYbkZBaHhYUmFKUWlW
            cStHd1pIMFFCWmRBc1lCN2VrSGxLZm8KLS0tIDd4YlRKVmFTb3M0TmJrdm1idU5l
            M2NXaWFLS1pNV1V5YVFwMFFIT2VIVUEKhV0ptk+FN8OJeUkYHYBIY6fNdtVgPyEY
            JT3r33RjoFvXmOSx1oDqlWlouLdjGuHei4dSlpTpZwi3uCLhur4qgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-26T11:00:45Z"
    mac: ENC[AES256_GCM,data:NN+1pOpA57Hu2rsA3+s+dcbDG871wjVT7swsbBUrmqF3C51RNeZt00X/0gowgH+gsdbpfP0Csqp7MphG/qn9+8FnZ0gsr3TjUASCh26V6zLp8p/fIZ+MF72Zkadu6Ql9+y5ZsOXRAV6hKXYmCJTO0ulE2ws/O7eruhRf4Vq47fg=,iv:Nd4Fwsl1ec8KED7jDL6CW/lNCKjDR9GcZ4kDhgkd3uE=,tag:jIBpMcHlQ9sotDVhBlqbYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
