apiVersion: v1
kind: Secret
metadata:
    name: tautulli
    namespace: media
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:F/EyjeBIz1EdW6UiXRalMsa+LMZcCv73P0TlnoyQYfFPaLjSrnpm,iv:k48x7ITDV/oIAw5pSxLOl8FtW1EFW6fx4BGXWXFYYGQ=,tag:JKnCaCaexk6UQ5GqzASVig==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:KrHZVjK+N3wQ4RTV4U8LLK9sCvCatcs3XK2urB7S3sxAjYRinKsWFsC+tPrcrAnfYhrxxKPCaequr7RNRqvIvA==,iv:HNgk7y5+RN0cm/iA0GKqBqrG8ma1zqPZrYKqFz/QLtg=,tag:dBBiXv8VjM67RCMiVt5Y8g==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:m8GOpubg,iv:XHvcHwOcbx6+EgOdK2ieLj+MwsgKX+pCwG2ejgtQ/8M=,tag:K8HdLXMKcyNYNCqfUm1mfQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:f1Y7BMYVieLdPBnPnJjUUi1uDzoX,iv:O7ADrA4xyyPTRL5J+icbGVHKwTWXb+PSG4DH4bx4rmM=,tag:03PyvG78WsfLa+UmhlEXKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UGZOT1RIbWR0TWpoREw4
            U2NoeEk0UXVWVmRPM3VZSEc5eHlEcGdjTEJNCnlkZDFzVzhWUlpqQVA2ZE1velV1
            M0VHSlp6cTRjaWRPazB3OG1XV0kyb1UKLS0tIGJHT2h3V21GWUhLWjZrcDVoR2Qv
            YWdqTlJ0aTJFd0gwS3k3ZFlob1U3K1kKk7tYCIKRzdS5cia1N0XfWIL5u1RhuBlM
            SHqub3kQsFfRqr2Pe57RMP6flUfxM/t1jbzQThJ9NNc790NIw9vwfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-26T10:50:41Z"
    mac: ENC[AES256_GCM,data:cFHydRdxcDM/LpJQsBsi08MzUxc9uuGj+ujpaMFiZm4parWysKVglTZtrdI21Clbc7tPduP8cR1pLMGvHo4Xj2tHxBf89NdgVbajuHMyVe8gSd9n22fHwq6WX+LwaaZZu0Y5SBNfJkRGyzliRIGgcQu6D6+OMSbA2iaYUvt53Bk=,iv:vHYd2LAk/SajxK5bRSNOX494FO8EFB9bdfjP4CRlhr4=,tag:iq4pL0C8SUPgthKC4ViV9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
