---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: redis-config
  name: redis-config
  namespace: default
data:
  redis.conf: |
    slaveof 127.0.0.1 6379
    port 6379
    tcp-keepalive 60
    save 900 1
    save 300 10
    user pinger -@all +ping on >pingpass
    unixsocket /run/redis/redis.sock
    unixsocketperm 770
---
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
  namespace: default
spec:
  #  auth:
  #    secretPath: nextcloud-config
  sentinel:
    replicas: 1
    image: redis:7.0.7
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 1
    image: redis:7.0.7
    imagePullPolicy: Always
    command:
      - "redis-server"
      - "/run/redis.conf"
    containerSecurityContext:
      runAsUser: 33
      runAsGroup: 33
    securityContext:
      runAsUser: 33
      runAsGroup: 33
      fsGroup: 33
    extraVolumes:
    - name: shared-vol
      persistentVolumeClaim:
        claimName: local-volume-pvc
    - name: redis-configmap
      configMap:
        name: redis-config
    extraVolumeMounts:
    - name: shared-vol
      mountPath: "/run/redis"
      readOnly: false
    - name: redis-configmap
      mountPath: "/run/redis.conf"
      subPath: "redis.conf"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi

