apiVersion: v1
kind: Secret
metadata:
    name: ltb-secret
stringData:
    SECRET_LTB_KEYPHRASE: ENC[AES256_GCM,data:TfewNPc5e2psycma01Ov05Cvf+H1IKbYuPdP7CwbZtiQsVfG9cJhbunBNgMaJEeHcKLw+XPidS0VWxyfVJupjw==,iv:Z+QD48k2pbl7jXkBibF4je+mHdDjkOPeqUC0qiQN/qg=,tag:PX9jyG+1Q46pRkLs6g9Kpw==,type:str]
    SECRET_LTB_SMTP_USER: ENC[AES256_GCM,data:LxDjrUMS6IN+qtfZNFEusqrlXzo=,iv:qEkGKVb1pEFoDUgTGyV6QFXS5AgEqz6M7ABr+I8g1aI=,tag:NLNugFiEvQJqiJP3Ah5XnQ==,type:str]
    SECRET_LTB_SMTP_PASSWORD: ENC[AES256_GCM,data:LXDJcDv7f3leK/hOSLP4KcZrfzZmCMJKIuyRMYUeWdAZ4DqETc6d7sGuXjU=,iv:RUQCXcbc6jSMzZhxmNG90WsMkolapANk1X1HAGFvGTc=,tag:HfwIHb470rZ8zJxG6qSviA==,type:str]
    SECRET_LTB_SMTP_HOST: ENC[AES256_GCM,data:6N9A9PFB8W5xzpZ+ekvp/LKYsZq0bhhg5k8J6Iu95X3QTQ==,iv:ozUj1HUjBd7H745U65IlgWR2bKA0d/uW8WkPOrXSffk=,tag:RK2sbX4BhReN3vLzEETUNQ==,type:str]
    SECRET_LTB_SMTP_MAIL_FROM: ENC[AES256_GCM,data:BILrNsJ/k5yDENaqw8sx5MSyGg==,iv:mDVrUopAJFKfogsqAlIGHuhhMQuVRWPi/mtveuftg2g=,tag:zhhjASJWpyoYvWDKjg2EpA==,type:str]
    SECRET_LTB_SMTP_MAIL_FROM_NAME: ENC[AES256_GCM,data:3kA0uc1Lp/yaoWHt09T72UCDhf5Puyf4jeSeQ3sU9FWIAMYHaD7+,iv:wa+p+3SRC6EdsQ4OYG7nZP1RHRkNwkrk+Sg6SUYtQpo=,tag:XQWSMzymw9JnC2gfpRrenw==,type:str]
    SECRET_LTB_PASSWORD_RESET_URL: ENC[AES256_GCM,data:TI++beP0jffX06VjIP4LL/le29hgIpIOC183FHA=,iv:/Tx3v1XrdCuTUtvQixLzO3kl0oh3YlwSBNKAQ3/i66s=,tag:dy1LsWe4gBM2NVbYu5HFUQ==,type:str]
    SECRET_LTB_LDAP_BINDND: ENC[AES256_GCM,data:boUAUJpsuPE+EmbrT/jJnRrJIPHDbmtvQXNyDBvwuYid8Q==,iv:eV5sEUSTbGMDN2mKegfCN3cmG3fQ9wGMnpdbA34LFxk=,tag:0GYi535xd3KEWzd/g+hTgw==,type:str]
    SECRET_LTB_LDAP_PASSWORD: ENC[AES256_GCM,data:spViI9QhUUF9,iv:J67gag9zfh/ukVO2cab4btaS2XZjueKIjRXXvwbnww0=,tag:shymxtH0RoPEEIx3fACj9Q==,type:str]
    SECRET_LTB_LDAP_BASE: ENC[AES256_GCM,data:5BeZSkz+cbsrzuCdjgp90w==,iv:B9vQ2R5eZDy4OeGfJJfhbMXglRdyT9Qn0UHFVeXMmpE=,tag:XXMCw3tj/4AlDV5Bk894Tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQkYxeGR3cVl0ZGZlelNh
            YkpZMG0wRXB0cmozY0lZSXdyaE1OWVJZYjJJCkltOGxnWFZJcnJrd2pLbFVCQlVu
            L2lYL2hpc3dwekl2SXN5SzExTlNHZE0KLS0tIFV0ampONFJzQ085d01ZM2p4QnAy
            ejNRcE4vWEFjdlFzOG5nc1Q4Z3JIL0UKb449Ti6hq51CQTPePg/cEZG2A4c6lSxt
            vW3yYUdx0zy3jrw/m3rFgF/IMqhOC8tDVRQB/xcsJq/Rb+b3Q+bzpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-23T09:54:09Z"
    mac: ENC[AES256_GCM,data:j5odPkKwSy8soya6cSY4eZ6a4SJRuJCblxqShY2thJ6z0oxjPiRyVQxN4uZtRjJs2pJWP0kcZX9Mz2g3X4PscKhrBPeVVvYTLyatauvMozFf3ZlIHfh5pgZfdCLNKdOrv3N8IIxQjyndlGnAhc17+VgQRObazafPX0S52qIA42U=,iv:noAuI4LyAMPmqhYp+iKZy/9Gkgm5m+NIYe4ULSiBM5A=,tag:0s4WH6072r+mkzuwmVOIRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
