apiVersion: v1
kind: Secret
metadata:
    name: ltb-secret
stringData:
    SECRET_LTB_KEYPHRASE: ENC[AES256_GCM,data:gyhJBQUPYbn9KPaNg32sAb1yZmo7cFGdrkzI15rNUmMuBNjcn6qkev9jCb/6NVOwG92VinhKUjqu3IUHjhzuMg==,iv:0dLfSx5ltvEWamTMaafvFFFoLkkfUjUvYkcfWaXhcLM=,tag:ufMG9J1307w81YIUigqDag==,type:str]
    SECRET_LTB_LDAP_PASSWORD: ENC[AES256_GCM,data:Xy+SgIdX7wg4,iv:25rI6a/PhnEF0Og+b0wjKgw2WBM0a/ZMTiWYNekNnRk=,tag:9bDx2q56EKaEieDZZwZAOg==,type:str]
    SECRET_LTB_SMTP_HOST: ENC[AES256_GCM,data:AQMWvzJDHWeq0gjW8ng+9t2c4cgZCVkV1/sN2ubSetpuPQ==,iv:+8bPN7on/JiZZlUMBd581PEogDZrtiv2zaV5r8azqVI=,tag://bal4orHMwoe+ROpF7Cdw==,type:str]
    #ENC[AES256_GCM,data:dc43w08ZrLdU3QKJRKkFGne3sXz5pH0qlMKaKNvMzFqO1Om2,iv:vTZXX5tG/+9fYnUsJTehm79USLfg1i16X4YZ2uDNXEU=,tag:bPDaQl8ozmEvk0Y5z5udhA==,type:comment]
    #ENC[AES256_GCM,data:5TaexIHFbagcSWQI4DsC0kSsQANJy+jTVYNZAEhLQWKq/w2eOgvyd+wFKzz+/g==,iv:r5AvF655bSKv/kSkSrY66hNJktWUqQg5Z1S9aZwr/Cc=,tag:rN3CcX5n7AtPa8mEpF3ObA==,type:comment]
    #ENC[AES256_GCM,data:9rhYNP8ipwQyQkGozqoOwbNzKLa8uITUZ361kdiFj51bEYa6MxykzAVZlBvsT61nlbl2FLLW6/5VexGPBv+tT8mUPrHB7tvZ898=,iv:BGbMdmx1bC8KxFfWKmPChcblkush5LKxjI/6I5n++KM=,tag:fXs8WOXn6yvNBc6DI9rXhQ==,type:comment]
    #ENC[AES256_GCM,data:2/CMCpDFTocrfLRCyeOgsDTUzwViTDH4DieL/JKPguiOD3IoVJs6OUqaPE2oTU2j8Cw=,iv:7O7R9VZXLwvUSMk/RSpnrOeB3GoN8nyk6/mIKzL47vU=,tag:6akmeZwMmA+ETlLtDQze0A==,type:comment]
    #ENC[AES256_GCM,data:y5Zhr7Jxs0qvWuVdu3bu289MM5U7RmjVAlFJ/xDvixBu106pnZHWO2dFqfLj4/K4ZcEMdM/LxUps13/WsfGKO5vkAEcsZMyo2s2D066Yyw==,iv:6I29yQoMTXhy8G+zCIMsP74/w5kFIFvAfDgnTykgKf8=,tag:JGgy6zvhwKvv2VJmxebVng==,type:comment]
    #ENC[AES256_GCM,data:Wt5+IbRkRJk8NwO5p/q1aTObzpoyhzHrjxWlw5XgFCSNQ13de8oFl6WgxS1wLngkuXWFtJYKsgoPzrT9DkahCw==,iv:7ZjG6jXXEdpprQnTqsg/ggfW2TVJHml25c7Bk1TBkQY=,tag:laITBXtmBFBSF2jou37n0w==,type:comment]
    #ENC[AES256_GCM,data:UucEQYlK4vUXxi+tF4Dcg8Ppoz6uLjt1BTSEU9HNujk9PU+EPPCJLv7Ob/7V5wiCBJFsFlXVHofLFLoRWVubGvPJ,iv:/i1VnDjFYYH2tn1Y/6xE7QRFhHdOswz9LsLj6fr9beA=,tag:FqtZmertLvQ6aybkT2LD7A==,type:comment]
    #ENC[AES256_GCM,data:/HNOwBdyMJxdxaPU0BtjDfNFMAQV5VQC2kwuM3owLAUQwZNYMCZuzBspakw4TL3iO0pvn6nNZivOJaKnGKaVM88=,iv:WQ5MCjpn2nXZ/b9fJWsXjcFAZstt40Sv8A7pXOd9Hkw=,tag:cIpHz67KpdslZlybrECWAg==,type:comment]
    #ENC[AES256_GCM,data:3sMm0mQLxkkGWiQdXshE2obDOCx8AeOkreFi+Z8S1vwE+CNWaK7XlDNfkaQnFw==,iv:DQFqwMC3cL4MSyzfMqaxNwKZuGP6LRKZ6JcIkzZnqKo=,tag:bnP3WNAGzSt6jzo9cvg8rw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSEZyUDFWdHNoaXl4MUNI
            cTR1SG1GWFZxazdJbjM1bXExVWdTdlZpM0FrCjhGKzZYSmJtTWwrSVl6UkFhNVVV
            bGs0NmpTQWpVeXJrN05QU1NFWnJkMDgKLS0tIEMrMWMyM056UkNycE1zWkFrOENW
            c1V4em1QMjBSQzAweE5LbG9sTG1ldGMKxKB5fHXAJRTF3WSVxhSNCb3dyJ7a3qYh
            TGArqWRGgT5m/HwL0myzpgju5900y3XGZ1ufyExUpyy5lULKHnCTgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-23T08:42:10Z"
    mac: ENC[AES256_GCM,data:YBKyTWxLexW7LRW8Ok1gbxyRbagJsxC62macsMY6y32AqQgUekbtibQb6OwZIWIpBneCmMLo46BMK0ldZedGpg9i39VcvpoeDBjtm4oVIAEc2inDg44tMD/VlulbErBPkQO5j/vCIsq9nIc90P7vbf+G0AZT9hrfDOFlUqFd1lk=,iv:nbRQpEAy/2qxYA6FhwY137S3SUQTHmyQwIuWfk+IhEs=,tag:CiZLdatYnpQgEt8edyH8OA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
