apiVersion: v1
kind: Secret
metadata:
    name: ltb-secret
stringData:
    SECRET_LTB_KEYPHRASE: ENC[AES256_GCM,data:GFfJhyMPOD+8qV8RBTKLX+sYaLhhdi0buT8HaCuGu7TG8zlXNTMQA14rVA3SgS6bCBoLk50de2NrYzzSiTbDBw==,iv:7AzXUpDli6fuVDMgxMBKcYLvJUMocsZswdHWg1E2ycM=,tag:xLJ00AUpREeCCVn5neiyyQ==,type:str]
    SECRET_LTB_LDAP_PASSWORD: ENC[AES256_GCM,data:0z/B2oVF6B8g,iv:Quy4NACqyO6NjTVn9EQwz6tiELion8QLmelNPkfatrk=,tag:0U+/Tnhst4PvxC+U06Tc/g==,type:str]
    #ENC[AES256_GCM,data:unC0seOy+WP9Tx6Zpgfe89YPcd4R18MdJbDGTRm/z63jcUh+FmwOp5KCYfdaJN1zZ7hp8kJXlSE=,iv:vGJTbq85E+I+WT4gD9BGLAn1968pM6XybSx5Uf+7eWo=,tag:X9oxJ0GVKUok9JiSueoZVQ==,type:comment]
    #ENC[AES256_GCM,data:uakOWeZbO1bsF4v9LBBQzGTCxow1JtElJvhhEnYitDhyTwDi/mBkLnVU,iv:IipvM4uXjWDTYEB0duwo+tHv7oRyIqpiit9XNIsnkcU=,tag:WGzbT5SNQq6HF6eREtxe5A==,type:comment]
    #ENC[AES256_GCM,data:gLOQZZR7ZgrLL8JMWiSgVCrFYld7eu91Q7/viZ3MJ2qD/rEMY3ZrNxhMf1lKetrm8Qa6/43tWfTbGFGsAPSuP5GIO2cz/w==,iv:e79ipGogJiZCarfOzz+yKGgBlYTd0+gYjuGHcf9I+/E=,tag:rDGut7IEZliA3Clszy0pgQ==,type:comment]
    #ENC[AES256_GCM,data:fpVgwPtyRlLyqeijNeMIXXoyMkY1IyX4UAD5+cTGcP/0Ds2xlLmPjTOc9GKt1w==,iv:7+RJNm2tlVCiiQReqbi3LZ8edbEKiUhxXWQZlVq1ln0=,tag:TtX04IlBK0c1Q5WRu8N7oA==,type:comment]
    #ENC[AES256_GCM,data:drqTAVOL040do9Mv7gWp9ki1qct9pmLzPH5+EY7I+tq+M2rUI9yf/DRi3qIg8TPHKVr+h2tU9mjChRYz1Wt7/nROWFzcwzo=,iv:tXhbO6qmzlx6nn1hmutO5Ls+E5C2rhjglqllKFKRAEY=,tag:QCb6lTYnuxmXPSLypWuDdA==,type:comment]
    #ENC[AES256_GCM,data:37siX+MvSWjBnTmAmbFJT3g4rCUMEtRwy9WuRM5lpxr8951Dnytnzwb4DsxlOZq56e/Ej17oBxyS7SOD,iv:R/xAQ9bpi5PH/6ShqntFJKos/FYA+1SMIsFoFe3iMac=,tag:2jXwdoCMNK14iSWqhJ7Ncg==,type:comment]
    #ENC[AES256_GCM,data:gShdFkXENwVicQ5s8CgVXX/GXwq2TsU6i5kEyd1iRmfGwy3Yse8EQmLmP4O18V6SeNTk1IA/y3OadA==,iv:S+U0DSiR7N4/qQft5z33V2IX1doizfOk5hvBRWlEaPw=,tag:PfUpQyMe204FsuzSKiggrQ==,type:comment]
    #ENC[AES256_GCM,data:XEQBx83GS5sgIJKw4iah8Im1rzCLCanxwBYXgO1JS+aal9+d6Jk=,iv:FLgHrLG5/SRyEkOdPBTu6vMTsL1yhdcmwEVqa9rTrAY=,tag:OChUXMPwa79GVXQVdzIlrQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeTROY3NQOXZpVTIwclhB
            MFR4U0N3bmFlQnlLVnhGaW9kenB2UEpSM1NRCmQveHBkTXF0OTE5dWJlWXgzTC9m
            WnM0MGFwY1p2TllDOVdGZzlqcEVRUXMKLS0tIDZaQjVMdWJPOThvb3BOcTdyVGlS
            QjdQRmZuMFMxVjdOUXMyWmk3Y2ZPVXMKtLzl/MenqaL9BfoXoDZEibrEFr7erR6G
            NaSTTZJJW46axXcu6UxRtoN9SLF0lOquaXQeoCLyhy+vRaoJNJJI/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-23T08:58:23Z"
    mac: ENC[AES256_GCM,data:LdO1Kt6UHWol08JHHVaTcA/KrSc9IerhXipemkXwv9XBlHedhxb+ouMX21DEq89DBDOH6K5DDotde8Ynl21tOPmO4kL4fFyA/6ra9Mzu/y6JmVuthgsFE8nrqy1B682TTnIY4fxDpH5BrhB7Cygu4qCMgWFq9Ckemk9F9hbpZqI=,iv:qx5f0yAagqnkRh35rcnN4OCzIssrrdTVQGPMt7mUegE=,tag:Eq+6HCx4LRimDTdPEslsgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
