apiVersion: v1
kind: Secret
metadata:
    name: ltb-secret
stringData:
    SECRET_LTB_KEYPHRASE: ENC[AES256_GCM,data:YAvBXZtmt/DSpBikLut43Sy3vzTosXXYKxFls1llKIqVQjGz9GdbYkRd+/TysVJKG5WF7FE1bW3aUl+HbFNbjg==,iv:1k9ONVOfhVbBv0LhqJuYCLTtFLii3Gr/DyUm0NEG5Fo=,tag:Am9AleU3tDo0W/jSGGAnWQ==,type:str]
    SECRET_LTB_SMTP_USER: ENC[AES256_GCM,data:bIAqF4NWqJV0AvJ04RSxN/WhGH4=,iv:WUUcPhVJfsBlkVMLenaMUpzu8vwVF2UrNbEY2nSsVhI=,tag:UUoJzJtGsD/bc12dgAU8ug==,type:str]
    SECRET_LTB_SMTP_PASSWORD: ENC[AES256_GCM,data:vWs5B0E/hly/ovwGN8yI7uCrfjkvreWLeTSbd+EW3GXsY6vwnqXfSYuAGKY=,iv:E3932jcfcxsaBhnG6NJWKSY5x/pHyz5JRJhb2LjZ+mc=,tag:+xZ0xk1TBhrFfjJ6QSX/yA==,type:str]
    SECRET_LTB_SMTP_HOST: ENC[AES256_GCM,data:u8e0gRUbfuIKyC2NM1FKQrmkLpPmzy0VBBknXe1s8lQ7Sg==,iv:CZlf52NPjMmesLMlpARW7hKBOc+YVqHBZPk3kh7b9Zg=,tag:cID5y8+IQJdYW1UMJl7AcA==,type:str]
    SECRET_LTB_SMTP_MAIL_FROM: ENC[AES256_GCM,data:gwqM1nNhxsjUOt4W/C5wHhJ/BA==,iv:QMTMAn4f4KedWkyRt/JMuWodoT+62gvOb6SVS73AvSE=,tag:jk8XKSXo0AZDQ4SGw8vSIQ==,type:str]
    SECRET_LTB_SMTP_MAIL_FROM_NAME: ENC[AES256_GCM,data:h9CTPfpy7bfnNecSSO4a9fV/JImpLMnm7vl2zPAelx5i4YYiilqo,iv:rE++oE5JQQgA1r9O+ilJiRKiwTbLoJi/bJVtZ9Qa7sI=,tag:r0Jdl19C4Wjktr5NeGB5KQ==,type:str]
    SECRET_LTB_PASSWORD_RESET_URL: ENC[AES256_GCM,data:8QXRodZYoelLLNpaBq32exFx0gmmY/r3uviGvfg=,iv:/bqAaT1cOu2seMazXzQmElok4zLbiouoVE/f/EbDwZk=,tag:clc7SQOzhdkG3KCcaCb3EA==,type:str]
    SECRET_LTB_LDAP_PASSWORD: ENC[AES256_GCM,data:Mq2oANQ6XjrWEfyylrY=,iv:QswWltgcogDH4TdiBBjirngpzQgfyaB0kyTOVl8N2Wo=,tag:r9G8tlrxDjVuY7iHDFi1tA==,type:str]
    SECRET_LTB_LOGO: ENC[AES256_GCM,data:6UPwwesDCvL/zSGAUtVlXaQkQut81w==,iv:ajVzFFaECCHxz+QTMImCsZidW4G9xjPX6i9XsC7qOV4=,tag:U656X/XdKHZtkNwmanX/9Q==,type:str]
    SECRET_LTB_LDAP_BINDDN: ENC[AES256_GCM,data:nDFXbB1mfmFs8qv2aF4wkCalZ8jzvQcGMW38NZJkxRjrJMP13T0J,iv:6QKJ8VfiHyhg7zIjoBR+X5jvim/liA/0yaV03ZargtI=,tag:fSEqtQMiOWVdsxhfkvY01g==,type:str]
    SECRET_LTB_LDAP_BASE: ENC[AES256_GCM,data:YGcJiAa9giDmbIuiMtX/Nw==,iv:8alo7cnTk5KJtpotWhNC+erV0NZkjOK+HoqfyTI6KJE=,tag:iwe1oaE/pilSZ+QIwLgK9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQXp0TGlhendwRVp6cFJp
            aW5lOTJIV2kyNWUyYythclZNeDVKWHlkZHpjClB5cUhNQk1Sd1dYM1Q2VzBUSHZt
            NXFYSlcyUVF1Qy94bVFUYW9YVGpZMUUKLS0tIHVKemJQNTRVdEs2d0hnNVJBZW8r
            djdPN3R1ZjZxMDlIUGlJY3dRZStqQzQKeyKOJ+ICIUhd3uTaVsXPe85Q8VpyQh/n
            jbC00dB78oTmoQr6av1aU5Zw0iKF+SAn27mrNL5H+/bMpWiUr+iIxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-24T00:15:07Z"
    mac: ENC[AES256_GCM,data:8m6/8jpjPxQoXeiaoL4GreByCCXyJZaPYIyk8vlFhuSHOcIAABXEkrHWHw1CU/ZzaZHXv1/s3KxF8cMHp2WtzU+wAa2E0Ii0HCvO+Bi4FmyoWm0U0i0cYHNK4RelPsMs1yH7td6ftKIEtwSHgE8Rq7G5Qyo4AlxHAdLTvveKxqg=,iv:k4a1vDrwRuS1cR0NxTFkTg3wp8NKnOcmv+l4Wk5zPVs=,tag:KBnvsaw3ks3aeTVTrV6NBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
