apiVersion: v1
kind: Secret
metadata:
    name: ltb-secret
stringData:
    SECRET_LTB_KEYPHRASE: ENC[AES256_GCM,data:gQrEpwcMilGDhiYAvRrNjcK2CBLulsitHEOlOj692/D4HwkeI1OVqojYhMaA3k0b0VBG6jpaBgyp1j6rKFOlqA==,iv:DYm0s5c8D+o4vQhK7z5KAOVjGpFZf+hcWQRe1+p6h90=,tag:SPspzt2MxbrUoUyfNRGGpA==,type:str]
    SECRET_LTB_LDAP_PASSWORD: ENC[AES256_GCM,data:oisWDhwGZtRa,iv:BSAQtl2q9e4Gspa0upHZ6AO5Jqxh2Iq++49vnFRvmR4=,tag:UmbKRPdOrwuQPGxBkqgFow==,type:str]
    #ENC[AES256_GCM,data:X1a13+ya1cdT90R1lheQAQ9s8aaH+3neRz0Tzw0CD00MnS/kaEsMN/IjD59StQwP3UWZOc9XFiI=,iv:o5f/jI/f/EskA70LHRuMSrVpN/rLopXnQ3Hf+PedDP4=,tag:yiNMCTFLPNTkvwA94xczHQ==,type:comment]
    SECRET_LTB_SMTP_USER: ENC[AES256_GCM,data:QyI7st3pedm8ua03gPc5dPjo6Bk=,iv:JEyVz2IKLwh7pBJwuGgpWrUNDF/cGjm7/VAG+YDRQk0=,tag:008Ir6gSG3K6h5mCviik/g==,type:str]
    SECRET_LTB_SMTP_PASSWORD: ENC[AES256_GCM,data:+/ns/9jbJ/jmU91+wMXbvLqqk6i6N2qntuUHm4Hc/zKnMq9Sgu1RbscUic4=,iv:HtGXJsZ7JYFBr8Nt0HmCU41crba1K0skEJvt2koDrdE=,tag:EXmFJTbziUzo6OWc2jp6Sw==,type:str]
    #ENC[AES256_GCM,data:XK61NdAYq6bCLC6Y4U8ZsABrFLHsZjpV5Kvw/goVj0oucu6JuihLtDnd25Y+KA==,iv:NnQQBoj6IdhFZaV/rz0S20F7tGRjT5jkFQ4AeK0N6Ro=,tag:BR29ibpYOiw/CCOpPkcjTQ==,type:comment]
    #ENC[AES256_GCM,data:U5GGfFznBQK2LoRgF7nEJ46csWNeR5+Rwe29gibz3O0B/Er/fy37bD/1XYPUKNp/xnn3cjHWUVKRksrArGeqX4gE2AkF7KE=,iv:F4S16dA53FxDbS0jErZNJcIQol/LDcQ03RmeC1KXnLE=,tag:QerMaPYHfe4ScMNYwnczcQ==,type:comment]
    #ENC[AES256_GCM,data:zjWSuwKlmSC9AhR+b0anivmqcXE2wC8tARYI7TuCq8sA5p9tS9WsgAuXMaRcqeTxeY6ARRybNyES27fP,iv:8Xp/nMDFFGwiW9zZNu29Xlxf2hwosGLwZdaYrAD6isw=,tag:bBO7RzC0Oi/TMXWNa/I/WA==,type:comment]
    #ENC[AES256_GCM,data:6m22RDmdMS4eSGBHRyLQjp74jHRPYrU6uE9881i1k+4KRRFbnevcsKPFtCH8oa+IU9M6YCyzNtKTIw==,iv:6K3in8zR0R27ioW9svnPDusjVLHF0JViQuuBDCgpJ/I=,tag:Hm4+jwy6YR8IOeLSd9yf5Q==,type:comment]
    #ENC[AES256_GCM,data:WX/MzJ50ru4wqrdRMTtjrcFFKSPPQvvOAXZIqzLlmGkQExgVLeY=,iv:ItyKVLNbQxS4ETC4vwzYPPxaI8i/FKuYeMhTokM0EfI=,tag:KmLwn3YfmU1ITBx9q70fag==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NGtuYlJwTFVaOE5KcmVy
            bkFqVjgrbnROdkMvUm43aEpEUmFiOUhLZUZjCnh3TjJqaDNGSzBwZElNNGJYNE90
            VDJNajYrd01ZTjBXMXNCK2pER3RsT0UKLS0tIGltR2lzamxuRHkvUVNOL3VLZmhp
            cE9tV1d0OUxqR3kyNTlCSm0rVzRuWUEKEbYNfF3uztfs8qXXboTwB/vU6Pkt76py
            WsDPwsKx3PF3FMVOS6B4Y0LLF4w9W9omt5iJGYLQCxRanrDivin83g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-23T09:01:43Z"
    mac: ENC[AES256_GCM,data:VQQDICTviefDIaogLknNWQUtATwm7mkFN1iOFqRK+/LlD10QNhSvligK6taQNr3xi1lsN1B9JbtdnA3ve1sWEGoR0UGx+otBeRuLn14iGcSpNOK8RiHh1IMkoXmfLNpXJhQkogV2jv+bS9YF1uzhy1goDoYLE+du32Xr3v/Kle8=,iv:CUsWbR0nQi2LW76auAaBxiUtoa2CKs7Bbe7P09O1SjM=,tag:VxYzK/YMIBYsffS/dYkgKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
