apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: bookstack-config-volume
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: longhorn
    resources:
        requests:
            storage: 2Gi

