---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: bookstack-config-volume
    labels:
      app: bookstack
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: longhorn
    resources:
        requests:
            storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstack-testfile
  namespace: media
data:
  testfile: |
    # Application key
    testtest123
