apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media 
resources:
  - config-pvc.yaml
  - config-env.yaml
  - helm-release.yaml
    #  - patch-deployment.yaml
patches:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: bookstack
      namespace: media
    spec:
      template:
        spec:
          containers:
          - name: bookstack
            image: ghcr.io/linuxserver/bookstack
            lifecycle:
              postStart:
                exec:
                  command: ["/bin/sh", "-c", "mv /backup/.env /config/www && echo config move done > /config/www/config.log"]
                    #            labels:
                    #              app: bookstack
                    #              app.kubernetes.io/instance: bookstack
                    #              app.kubernetes.io/name: bookstack
