apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: media
  #  labels:
  #    app: bookstack
  #    app.kubernetes.io/instance: bookstack
  #    app.kubernetes.io/name: bookstack
spec:
  #  selector:
  #    matchLabels:
  #      app: bookstack
  #      app.kubernetes.io/instance: bookstack
  #      app.kubernetes.io/name: bookstack
  template:
    spec:
      containers:
      - name: bookstack
        image: ghcr.io/linuxserver/bookstack
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "mv /backup/.env /config/www && echo config move done > /config/www/config.log"] 
