apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: media
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
spec:
  #  selector:
  #    matchLabels:
  #      app.kubernetes.io/instance: bookstack
  template:
    spec:
      containers:
      - name: bookstack
        image: ghcr.io/linuxserver/bookstack
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "mv /backup/.env /config/www && echo config move done > /config/www/config.log"] 
