---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: invidious-server
  namespace: default
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.5
        env:
          - name: POSTGRES_HOST
            value: postgres-rw.default.svc.cluster.local.
          - name: POSTGRES_DB
            value: invidious
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: invidious
                key: username
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: invidious
                key: password
