apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: media
stringData:
    username: ENC[AES256_GCM,data:cyiNIJSrQcQ=,iv:BcvJexEwKuHNwmKKSiuIEF9qnt7IMTuLY4i+MBY6pAQ=,tag:5tyB5b6ID7QM9u2AVV94zQ==,type:str]
    password: ENC[AES256_GCM,data:C+DwOtoZ6oF8uM/3He8h,iv:N2ugQlE3m78u4QYhIFeD2EGqJHbOWW3xeoIYGSYHYS0=,tag:HxTwW94l6Z+e6xN1gkkPug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQUlCNEo5YXMwK24zTWd3
            WHRBQWhyWVBTaXJ5WkhHUUhJWU9Ka0ZoMjBNCjVYYVUzeVZtbm03N3hJSlNFNXo1
            ZVFqdFM5NldXQjVWbVZRZ0J6VlhsUWcKLS0tIFBaUkRtaWdqNjNTNXc2Z2t2RTYy
            bStPS3BlaktRZ1crdVk2Yk1iMHA5c0kKDRpXPSWs7EGHfjS8nU0EJ57eIKSPezRH
            klc5iNNRiDMNh5sRnSC87OyTdtsWevxkJkHJsVNdBxYHmxS5ua6Guw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T09:26:20Z"
    mac: ENC[AES256_GCM,data:ZHbvwm8iKVDguIGy/mhyKzTiMCewn/f+hLlDtE9iABRr89ojPNZgsEb2bmBW3Ig0g7sXf9aZAxIIS+8VNwluDqi+9aoXm4JF2iCTOlOklVJNzuTMWtNqHGYAqx0ZEqkI4YVrcfLNuHFsIzV4hv2kIrX6XiFI2RYx4mDBSrwA/kw=,iv:v+mXhV2D6+ilFz54aDF7FBkJs1ib0V/daluU7cnmaYE=,tag:VuROfr4wC7PzoMzVxm9jJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: outline
    namespace: default
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:jKgMbCQKuM2+VYd1xg==,iv:gVdmCYKwU8F0xgPNuox9rK8NMlx6oBsFk8/clrb3bd0=,tag:6rPRZwr5o3/Gn0IpNAT2PQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:a5rI9sxqwYYaf6jMMYaRKN0oszQ=,iv:uaZHJ7TbkAcnejckpyCbmLJgrXSLXeLaMhR/VkpR28s=,tag:Aws0Rw+2YPeNdyFlsXvJ+g==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:5UAzTQOELWpEIUVLxp+1qqg5hEYjitj2Qmvf+nATtJroRtOb5BhIj0Z5gZK0RoV3aqa+uM5bQp/D1l6lQLyy+g==,iv:7ZkYGoJQt2Mj71dktu1AjLAy4clD3B1zRIrzvOMR2EI=,tag:cRa0jdPGksOu0bodN0M3Eg==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:y8zq/kJnwpGV7qsOfPsKhzSU3ufYLAAr9irLduFrkbT7ZzTlwbpC0pW1ZRqc/+luOa1X0tttk4y+y352RvWZ8w==,iv:bPectEvaOeYPuQoogitBZEF73PPASoMSVGZf5KA9uHQ=,tag:My1H5pih2Y47QvYEgE6FJw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:57qSCa6mMD7xkFUms+Lfk0NJcal9e9oLQoUtefSNC8awvdrdknkqfWSpNMsk7f8A4MdAYU6A/nevuyoo//b/Ea5hdY5rzD29qpfI1tdPtEaeM1mpZWM2,iv:xccw40BTPOgIvifaf5xoRWKECDE5Gl6SfQrO6sNGjS4=,tag:R+v0cO07H3WpgvWb+MSENQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:81hVTrUN9w==,iv:0DG7mx3+72zycBKsPwTI8IRwsfWx3byPyRGnUok6ai4=,tag:zx0+mYResEh3yHTrbgliNg==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:yyB2C1Z1Wn0fsOqEqg==,iv:jBGYMTWHY769OJF9nazVqb83BBhuk57KBY8qKXLRQ2I=,tag:0Dc1qAJ9/PWOBHDsGMsKcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQUlCNEo5YXMwK24zTWd3
            WHRBQWhyWVBTaXJ5WkhHUUhJWU9Ka0ZoMjBNCjVYYVUzeVZtbm03N3hJSlNFNXo1
            ZVFqdFM5NldXQjVWbVZRZ0J6VlhsUWcKLS0tIFBaUkRtaWdqNjNTNXc2Z2t2RTYy
            bStPS3BlaktRZ1crdVk2Yk1iMHA5c0kKDRpXPSWs7EGHfjS8nU0EJ57eIKSPezRH
            klc5iNNRiDMNh5sRnSC87OyTdtsWevxkJkHJsVNdBxYHmxS5ua6Guw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T09:26:20Z"
    mac: ENC[AES256_GCM,data:ZHbvwm8iKVDguIGy/mhyKzTiMCewn/f+hLlDtE9iABRr89ojPNZgsEb2bmBW3Ig0g7sXf9aZAxIIS+8VNwluDqi+9aoXm4JF2iCTOlOklVJNzuTMWtNqHGYAqx0ZEqkI4YVrcfLNuHFsIzV4hv2kIrX6XiFI2RYx4mDBSrwA/kw=,iv:v+mXhV2D6+ilFz54aDF7FBkJs1ib0V/daluU7cnmaYE=,tag:VuROfr4wC7PzoMzVxm9jJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
