apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: media
stringData:
    username: ENC[AES256_GCM,data:5dWS9YGqwG0=,iv:c7TzjYngNi4ibBs1HJxekdriqnvfFR/HoZuVTRLO8iU=,tag:PEFzvo63dbPxtsuqV4cltQ==,type:str]
    password: ENC[AES256_GCM,data:xK/lH/AhWMYP/opQ0Cl5,iv:i1ybZaTy1IGg2q5c0i6F8i70VEbrAK8VCuZg5AGpSAY=,tag:Um9CYT1V4IxODw49SDAnOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3STB3QlZlUDNvbmo5Tmx0
            WWZNU295ejBOTE5nYVJ5QnhuLzVGRmdjZjJBCnA3YlJVL2tqY1R3NzdLZ1Y1M2Fp
            aXd1dnN6SUFCMGY5NUhENHh5K3MvSFkKLS0tIHlzZmx4ZzVsdlZnTnVUb2JKR0tF
            MVNkTEJ4cmh1ai9kZkZ2RHdlcjk2R2sKWG/P8QyjUe8Wk+o2nOt/8NEXMCxbgRT6
            OWw+dffn7i4shWzkVyDF604m0zeacQccqF0cCRlfrOw8ZO73YDrX+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T09:19:03Z"
    mac: ENC[AES256_GCM,data:UKtRlyA65KPd+5aoDfGDmEKtFUxAaI79499+ioecox2hd1xh8dVvqE0FI7g6PJHhSJmwJscx9+WLR6oR9o8ansfFxfSRavpt6bJ/YuAHgrXFRVrWdEslbJmaje97SXwQg8CREExmP4Prb5ZK16UJ7XAPNrlvdk7jKJhi6KEGkuE=,iv:LmEyznashpxs9lHlmrFDM6wmWjbGLzUEOyslYnii68E=,tag:/VPy/fIQaeQozWrMryd+7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: outline
    namespace: default
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Zz/pIi08mSAFMAcNGw==,iv:it4ktBW9/b/BcgC0VcTKQwdlmNiah/OViVn+0Kr0xE0=,tag:e6Y9C7Vh+pn1FlpeOtxuKQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:YlaaJpaCdiPIsMg8fFgqfCLFsPc=,iv:1wlvfphT803j9AFX5/hXm0fBSkUc3pMI0EJ1yZaP5Jg=,tag:p/KS2Y123fE735JRMnm6nQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:+3O2VJXwHtw6KlEFmtBsiLIO/7CTfVxoDy4Y9rpaEITKvpr5qeFVYhKjyqUV6okdTiqfMiydtM708DTtb3ZMDQ==,iv:Xe7iR07TySsqefYFbEd7/Fnd7W75qD2TM46n8g3F9VE=,tag:urVR7UYIjFPaIUgDbzJjfA==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:Xl7Ri5RUlaDeSh6SSmGpFguRaJP4XiSq3CfQvZ/RNNUBuXgaQimDtecc24Ls3lY0l8FOSqj9U2qHGjqLvcOP3Q==,iv:l2uiD7cMB1R3hJY84xRCtXNcKEXc7mm3c994mM8EUgY=,tag:JQJIpJ/BpTRego0f6fK/hw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:DSyQcdWQjCRNWxH0DPwGBGlmhgf9HKOgDsxt1ah5I7SvoWXUo1jDVtlZ57UgmG0xD39IgRpQoXSrzFt1C54Axg5a+mpNZL3WiqkYNW3g+0GxY4vBmSJs,iv:/ph66t8/99NdFnLWm3tDWk0LLjtPYdIySOPmWGimJAg=,tag:ap0mld5+VkSjE9qhjZJTdw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:BARS3yLVgg==,iv:sizX5HYPIHlWR5JBKgo2USYsJIUsVpH/pGk7Xx/a+TI=,tag:RDBtIOid1IwGXjoFZLk6XQ==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:dSizH7k8y2lqpU24rQ==,iv:GJLke+Ot6kS4BI5S5PeqnlGyIRe4NGNfmSRY5f8xvF0=,tag:qHB5NXiDaAnfchzyJJSBZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3STB3QlZlUDNvbmo5Tmx0
            WWZNU295ejBOTE5nYVJ5QnhuLzVGRmdjZjJBCnA3YlJVL2tqY1R3NzdLZ1Y1M2Fp
            aXd1dnN6SUFCMGY5NUhENHh5K3MvSFkKLS0tIHlzZmx4ZzVsdlZnTnVUb2JKR0tF
            MVNkTEJ4cmh1ai9kZkZ2RHdlcjk2R2sKWG/P8QyjUe8Wk+o2nOt/8NEXMCxbgRT6
            OWw+dffn7i4shWzkVyDF604m0zeacQccqF0cCRlfrOw8ZO73YDrX+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T09:19:03Z"
    mac: ENC[AES256_GCM,data:UKtRlyA65KPd+5aoDfGDmEKtFUxAaI79499+ioecox2hd1xh8dVvqE0FI7g6PJHhSJmwJscx9+WLR6oR9o8ansfFxfSRavpt6bJ/YuAHgrXFRVrWdEslbJmaje97SXwQg8CREExmP4Prb5ZK16UJ7XAPNrlvdk7jKJhi6KEGkuE=,iv:LmEyznashpxs9lHlmrFDM6wmWjbGLzUEOyslYnii68E=,tag:/VPy/fIQaeQozWrMryd+7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
