apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: media
stringData:
    username: ENC[AES256_GCM,data:npBT8RBbzPo=,iv:p9HZ/C2s6dAot90Pe8wXDA3mOTzXGzbXvS8jTWj9SiE=,tag:qAe2Pyd+DJx/dORUSkHzRA==,type:str]
    password: ENC[AES256_GCM,data:JtJFVqY41jt6kI2uE/f5,iv:h5wqmuDVD6XThL8V2tDlII7CBrQk82hCk+w7dv24rg0=,tag:w4agXy55lkvctqwtVtwVWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZHMwQ3k5TEdDRy95WWxp
            dEttcEJoSm5IOFlkUHMrTVhXaldPRndDSWpzClBBTis0OXl5NTFRdTN3VlJENFBa
            WTBZM0xqdXpYb3luWlEyeXBOdzJNRUUKLS0tIEVVMDkyeGxUYmU0MTZCVGZwZ0hw
            eERxOTZRWitkUkloUGQ2MEs0RkFuRGcKsHOZkUWwr402OoAtyQ62dgt5dYW4Cxkv
            WFLHzGtwOZyCjjww1OU4p3Ak6SflfUI0DlYWrfqxxPiEbUJzyDDT8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T08:59:02Z"
    mac: ENC[AES256_GCM,data:NNnkfQ/00Wc4ftWiPlGGKdHFBWY4gtcEHpvshsorbgdLeHA+5mNcr5ftjyjKazlFeVfPPR6keAUhP+g7+eKrYoUk4WDk9AspIEsS8624sUmI+wm5iwysZ0ClT+jjJKxjkupVz5qKhuwRyhZWHQIYalDC3oU6DEsjs9170lLKH3k=,iv:9zr3vhKsJ2xLl5Wq6kbMdCz/NbNXi5kRuyhT48Oohv4=,tag:aTznvh45RGBBdlVHgY6Phw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: outline
    namespace: default
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lLiNx7d4Au1RzRWIyw==,iv:f5D7Daa9O2ns0CuOj+qlcaQ27AFH6TqiP6+Ep71Vu7U=,tag:5NIdYxRcAYB2uIAZWatQKA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZVydifNTfj77EZMeWlGNjNSaGyc=,iv:VbpE21ORO89lA3mYpJ2rYnsy/bLh+hUd83r+hHJVhQ8=,tag:OH3+FwmWIsgPkh67sMPNMw==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:vkOh2aIRvYeHB5Y/tSeYXIY0JDbEjcHL7/jJsL/QMvJHE1CGonYX5vxa8Bj0nOllXkiMVeSwNLk3mDlJbeM3jQ==,iv:Tti91KxdSmeKXeYKWb1uH8mfF7gCk4sGMN0RQrfQqwY=,tag:Isxz6gTTboB2FME4+1HClQ==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:6P220s0gXa4+4e8LQG35m43wI+qdv8Aru5HyLWX1gh8PbTYRgI47R9Usg5lbdemn7G/Mq3h+ZN7sxfCzPveSGw==,iv:Be93c864FSKde89t/FZouhYE+VWncC6IL53MB1Gb6jU=,tag:6tH+tJZ39wS7Q23N0XB5MA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:PLlIipF8kkr49cbyWZbPjeaU/VTdcyWly7f3w5OgQpZfaKkRfW+33lBlK7ffD+fvXlWt5N+DpZ+/X7rduvnDi+KqqsuknGborlAp0Jg+2ByZ8SGlZOjTNg==,iv:u0X/NXduEG5e+hI58hZd7zg5zuDh9bbtAs8Li7Hro98=,tag:MXv613u/qW0o4wD0SqotXQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:NZinaNPAIWE=,iv:jm5uEGH0PyzG4juHSK5doqdbJVUK6b06m90cFrtOgF4=,tag:PJIGXnwin133sX7MjVtFyw==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:dbytYjyx9P9dRvicKQ==,iv:55eL4nfXd10fexcEhg2YJwdcF1nSqLqPDjQjwi0LhCg=,tag:yphZnJtTZOwI/vnnPjaJ9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZHMwQ3k5TEdDRy95WWxp
            dEttcEJoSm5IOFlkUHMrTVhXaldPRndDSWpzClBBTis0OXl5NTFRdTN3VlJENFBa
            WTBZM0xqdXpYb3luWlEyeXBOdzJNRUUKLS0tIEVVMDkyeGxUYmU0MTZCVGZwZ0hw
            eERxOTZRWitkUkloUGQ2MEs0RkFuRGcKsHOZkUWwr402OoAtyQ62dgt5dYW4Cxkv
            WFLHzGtwOZyCjjww1OU4p3Ak6SflfUI0DlYWrfqxxPiEbUJzyDDT8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T08:59:02Z"
    mac: ENC[AES256_GCM,data:NNnkfQ/00Wc4ftWiPlGGKdHFBWY4gtcEHpvshsorbgdLeHA+5mNcr5ftjyjKazlFeVfPPR6keAUhP+g7+eKrYoUk4WDk9AspIEsS8624sUmI+wm5iwysZ0ClT+jjJKxjkupVz5qKhuwRyhZWHQIYalDC3oU6DEsjs9170lLKH3k=,iv:9zr3vhKsJ2xLl5Wq6kbMdCz/NbNXi5kRuyhT48Oohv4=,tag:aTznvh45RGBBdlVHgY6Phw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
