apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: media
stringData:
    username: ENC[AES256_GCM,data:77T150wkAgg=,iv:jPDP2aT9ZzTEe+1nCAsqgPTVh27OgOH/CoT36vnMVSk=,tag:P2cUmitk/pUBBHSjR8FeAQ==,type:str]
    password: ENC[AES256_GCM,data:AE9lCmROixUy5CYxngEc,iv:D8ciF2clKbB/K+g0nuS37D/vbojEl+hc4dLT7+M0wA4=,tag:n+qjEFJI0OhXIKXjAiIX/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNmlVeDIyM0JVM3JPZmFU
            TEZLOWlFVkxnK1l3OWRMN0VCWDIrNU9SV1hvCjNDT0tkYU1ob0JKS2p6cFNKWFc0
            bnBDMENJNWJuWEdlWjZ0NEJLelBITTgKLS0tIC8yTFFuelc4YzlyZW5CNGlXZHV5
            UFplMDJ3RXo0NTRmTUtvQStLQUVBU28KSEk7B/3LydBC9jyc2abHKhVrJJTGU6qy
            MrMKBhniZo01ZVgHpFEGrMhppH4jPqdLj9V7yg8MhGWQi25KI1ZvDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T22:35:33Z"
    mac: ENC[AES256_GCM,data:e2X8uao2H+NM0/cBF1qGLTmjlZz9cGBWMgEmYhksY4O1nM+dETGDWYinb3mxvsujodqfXlcOPksYy6aB6qrEgmpiSkN6cI02Ap3cRczsYEcLR1lMivTR1AGLQyyxPapGODge9HCLGWq/Mvahqk3AN9WYSilJG++9Ms6yFvZUWR0=,iv:mdqrLb/2dmRi1lY5FnhP+LmFPJ+VFKdAfsZAwNhK9jw=,tag:fW8cQvTzaA7yUTHFvBSujQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: outline
    namespace: default
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8cAaW9uSHpLNzhRts/+YT7w=,iv:Gpgg/PEMWbOSGvTwHD/WiUpjv8tKIzBqnr/o6Gae8oI=,tag:xxasMjay1DQmsuqQEl8gDw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lzcRzVzwqlMwg4Pu8+w3GrkzDbQ=,iv:gJXJ00sL6Jdjtg9QY2IHedmAitXOXeenM/lY2aYGe7A=,tag:RLv57hOJMu83uDVJmfhxJA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:3lIL9YNCoQUVCb5xCPdVF+tmN64nfvJQZt8SUnLQ9QliJyigwxqfcxJ3ZXTgaO3bEM+q3n3J7Nh5rZAw59+Ukw==,iv:Lgd+JwqAUaYtMrmmF3Yjbxj4ooEvDg8O6W14ypk6Plg=,tag:lBuzCHhizOGVh4z0q9OP6A==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:rIdCpYM9+DwMecf+5MUDGSHwll7xVPGDtdrK+zHgeA0SA8q3QFs5RGKnUVil0BWkAB+ad65O/YaSk8B8GigcYw==,iv:LTmoS+fWzn0fhWxZDYz42j9AbLtFF8fyjzLz8PIPKrE=,tag:QtHguI1P8JjmjgRL441BDw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:146m16vxcg6QFRnz9Dj3FJefqN/W2ICT2dnGOQ/41tLDbI6g4lCp/L052HBPVA0wID7YRaIOWEttRAVFl5ZKlvuuuUkOElBINOBPLwm+wu53hZgIiQg=,iv:szt5+9sJjUmuCKiYgWlDoXVYJ71hWUJaFj8THxrooqo=,tag:FzRD9OdQJLFfb39DYVsDeQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:8I+UPFcAIg==,iv:g2oiQemEzD++6j3FvAT6a8d5k4/LefOv6ucAPOOcQuw=,tag:26aKrBaYyJ8Pn6va25RZqw==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:NJTh07JIM8RNpnOqYg==,iv:8nvAatvRZF/mrlrTuCYG8ZtNo4gTZpzVpdwSwPtfyek=,tag:WL3mLN7AzYa6QiV/1Grw4Q==,type:str]
    SMTP_FROM_EMAIL: ENC[AES256_GCM,data:Z1P2yxCbiNWBeNbuGaZ+sw==,iv:amJzX2C0ThPcD7BNoCcuR/IUntWRxazLD8XnvJX5QOY=,tag:Ztu+WL06P0GgLb4KVG6F+Q==,type:str]
    SMTP_FROM_PASSWORD: ENC[AES256_GCM,data:VKBxUbYHsQ==,iv:nku47FZkQDAcg3Kr+ByYbW+8WJUJBRyKORqbVJtRfws=,tag:7U86xtvG7+e7HRsCBh6kew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNmlVeDIyM0JVM3JPZmFU
            TEZLOWlFVkxnK1l3OWRMN0VCWDIrNU9SV1hvCjNDT0tkYU1ob0JKS2p6cFNKWFc0
            bnBDMENJNWJuWEdlWjZ0NEJLelBITTgKLS0tIC8yTFFuelc4YzlyZW5CNGlXZHV5
            UFplMDJ3RXo0NTRmTUtvQStLQUVBU28KSEk7B/3LydBC9jyc2abHKhVrJJTGU6qy
            MrMKBhniZo01ZVgHpFEGrMhppH4jPqdLj9V7yg8MhGWQi25KI1ZvDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T22:35:33Z"
    mac: ENC[AES256_GCM,data:e2X8uao2H+NM0/cBF1qGLTmjlZz9cGBWMgEmYhksY4O1nM+dETGDWYinb3mxvsujodqfXlcOPksYy6aB6qrEgmpiSkN6cI02Ap3cRczsYEcLR1lMivTR1AGLQyyxPapGODge9HCLGWq/Mvahqk3AN9WYSilJG++9Ms6yFvZUWR0=,iv:mdqrLb/2dmRi1lY5FnhP+LmFPJ+VFKdAfsZAwNhK9jw=,tag:fW8cQvTzaA7yUTHFvBSujQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
