apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: media
stringData:
    username: ENC[AES256_GCM,data:PWh45zMWwho=,iv:FmNTh7HBngrydJeAAnVwvLrtqm79zgA2jFTihGVIRKQ=,tag:N7VDXX6sOxbYNUg3wq8jjQ==,type:str]
    password: ENC[AES256_GCM,data:PdODwXCNDJfrLO4u+a1a,iv:PGyCDweaLmYqOjFBrf0Artnk7MXP3cV/p7TGScsU+/Q=,tag:GYteHEtt21xwHjt0IQNOaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVUhqRjlKaDJ6RGhmSTRG
            dFJaYm00TExWY0llaEFXclFNeldHbXZWcTJNCjI1S2NNRm9PZ2dBQmNnV0Z1MWxp
            TFcyaldXL3VjYWdqb3dCMHJ3SEltaDQKLS0tIGlCMitubmFvWnV5aEVVVkxnT1pI
            TWRtd1VKaExZQVlVRGRaZDVYTEVxRWMK7tmEfyu8g/JB5IP/dvGkooVapTjO+gP5
            QbnRWnYGJ88Bn/sWAJn2bGZbkIEu6oj68xB8TLMAHLOFs1Plkmw88w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-02T04:06:19Z"
    mac: ENC[AES256_GCM,data:E4j1d3CW/900c2EUkcGAQn2tZhex/hYwn2pqNTXvXuDsQW//jGoczbPyAxl6h9B1MKAekSxcN5nhc9Id3/kmg15KBHhN7ZypVQ9wNXgCCpZy9H/bJ9h6SsIbaCLOYqrc89lY3xZZyK7gfwAPUr30lX4OHvoK/VOR/4z4XrvGkdM=,iv:KSw0TZIhWeP5LG11CyhKob669H5IyKayvWofgcLS5LU=,tag:PywFxAV/qqWYFoNmajwD6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: outline
    namespace: default
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:SPX8dtyZVeRzI0hfdeVkfJA=,iv:Js5SzzzmNAsP8nQNk9ftgTHqEPcJ2kvbMY73eDwe1cg=,tag:jh8HNMym6sPGMhuKiljnNQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Uep5UGzwZBi2eWgdBUyX0gRFfrc=,iv:QQPVYgUJYUq688+rh1B7HYpZx/WV2PMmmDoWjfKfewU=,tag:JReztcVNUu3Fap6AoSS8Mg==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:WF4ZsxuaKAG75YA0Gcccnt72c36G78Df0No4IyPn5XJnhKb79yTD6KHZUDD1NESARpyy6It/CySSTH8EGce2wA==,iv:JILJsYfBUJhtGw5DAmp4FYixscJOxYW6FvwS5YCxiNQ=,tag:VVTqKnXuqlfXIAODuz1MVg==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:PqGI8uhHUROQgsCJNLyQ6eJv0SnUsB9QiYdMY47/sg7YwYJBO/fWKQk0w/ug1AGacb43Aa7yG7cKgLE/X7gm/w==,iv:BMK0d7VTQ6LisniPTFejE3soXJiO0u7ZNHiva6hGmIY=,tag:Xorp16zK2cPNWJtPu1n11Q==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:xezw4Iu5RYmYXvmy3SnzApE6Ou9VJQI/Fz7y77t/PZ55KPs7iU6WOd9XNkmJT/wSE9OdAav2Bi11T/kCKTsodf/dndAJWr/QqLYlw5hEbHSDnkPn/VU=,iv:dmgXVe3MhC0fv4Sj3A2I8QkKIz+/owo+VNS1LmjEqsI=,tag:SN9I9y/V+Qf9AGLCEGLP9Q==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:fcNwyCQlaQ==,iv:cs+uSAf9PqLToo4pInrGC+Hi69OfMmQxTDSLZy6V2cs=,tag:RMNP7xn4unUEQxvexKGHBg==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:Y3W+50IAnd8XCpo46w==,iv:gGF5yiPJqIQMTyvcKLFDr5uB7vKwCe0EuM9jvKz27YM=,tag:VHiawyGj8VVgppMDNhAHEA==,type:str]
    SMTP_FROM_EMAIL: ENC[AES256_GCM,data:XVxO0G9YlGO7n6m4pBYBJw==,iv:4PZi6j/khHpnIUL1LuCiQvig0Job4tJs3jsb9x2jyuo=,tag:rP/HlmzUmd9msopA4njSow==,type:str]
    SMTP_FROM_PASSWORD: ENC[AES256_GCM,data:Pl4x376PeA==,iv:UftRyG8GY0jTIFbmsIwt6IrXjYUUXvGC8GFGK0GVgvs=,tag:d/jPi5g3Tt3pliaJelTamw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVUhqRjlKaDJ6RGhmSTRG
            dFJaYm00TExWY0llaEFXclFNeldHbXZWcTJNCjI1S2NNRm9PZ2dBQmNnV0Z1MWxp
            TFcyaldXL3VjYWdqb3dCMHJ3SEltaDQKLS0tIGlCMitubmFvWnV5aEVVVkxnT1pI
            TWRtd1VKaExZQVlVRGRaZDVYTEVxRWMK7tmEfyu8g/JB5IP/dvGkooVapTjO+gP5
            QbnRWnYGJ88Bn/sWAJn2bGZbkIEu6oj68xB8TLMAHLOFs1Plkmw88w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-02T04:06:19Z"
    mac: ENC[AES256_GCM,data:E4j1d3CW/900c2EUkcGAQn2tZhex/hYwn2pqNTXvXuDsQW//jGoczbPyAxl6h9B1MKAekSxcN5nhc9Id3/kmg15KBHhN7ZypVQ9wNXgCCpZy9H/bJ9h6SsIbaCLOYqrc89lY3xZZyK7gfwAPUr30lX4OHvoK/VOR/4z4XrvGkdM=,iv:KSw0TZIhWeP5LG11CyhKob669H5IyKayvWofgcLS5LU=,tag:PywFxAV/qqWYFoNmajwD6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
