apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: media
stringData:
    username: ENC[AES256_GCM,data:he4cw+GP9gw=,iv:sIvWQuXEyAE9Duu+a0Fi3ZoWU/BEeg2xBq4I3I/X/+U=,tag:98xmGmSRom/BXRp/cZkg1Q==,type:str]
    password: ENC[AES256_GCM,data:hePs5y6aaez6rDPzpGdm,iv:UbIcnfsP9hjY5bUrnhi4J+lyyYWakhHso2QDWyKfLbs=,tag:69Fq6JgeKKBRUfl83DRl6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKL1Y1YWxPY1Y4QXd4d2Zl
            VjgvSE4vYXREOE9XVzMzWVZ1MjNGcXJIcWprClJYWVZRVGZ6N0FhZTNNQmU2M0RT
            T1hpanFmbHlJY2hsUENrWVhnL3BvdlUKLS0tIEpJQWx1MDI2ZHY5NEROVUVzS2E0
            T0VQcTQ0MVBLYkZaNWsxdHhzbEQzekUK7LWga2ZQgW+jfRGgxV2S5phRmcIAKPgy
            gUTq8qIlDWVVM1zFk+8Uh3pvSM0S1VBkG1i2Z3Y0DBa9sQ1hsdrHPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T08:28:02Z"
    mac: ENC[AES256_GCM,data:IVYLocggDhqgFUo8NM6zZAEc0GdVlvTI23n4DkPLbEiS2orw4PiddVEZ0aAiGp6A/L/dRdRtOG+vAVStfDnNUbkDJ+BjKdT2nFcpgmBosEd1wOmBFXzJoKtprfdhDJrH8l04rfplAJvXj7YSfq9XrWNMg8py6KuOJpWzXTqA/M8=,iv:RcUX0XG3795oaAuCkTq+Gq3FPncUCIyEyoRImMRABYs=,tag:OFkbf1L2X1eteD+elQjOtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: outline
    namespace: default
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8dpqaNznEpJVAF2+og==,iv:ZPWszY6nupNZx49YZUWkSGvTsV4E6xwJe6XQMTBlO3k=,tag:WTgWLG0HNqpIIPHY9wG/SA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:cA7LfAPlKpPBfjbRBHtR2Ggqm6Q=,iv:06D+LJQoztTBE5lCjCey6S0x5IOlL+4k27M57PxIzjE=,tag:iFrGgrc0ZIy69kpW13JSgA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:JbPpDEyE+NRE5B5B8u4TBTO2VpS8jMrvMyIs/OnF6DLNfujBrWC2Wwu/b4gsTiTrf5XfUZg2iVaKjYXTnp35aw==,iv:ba63SWTCojT/xwfDAu7qvPR5gcMqTSlNfZwcHCu3Fi0=,tag:YhAnUHxduOdH5F7+fkjsFA==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:vaxLHQm5HEuOjYluHGdtIJ7oWHi8c7rL/wFKO5UYjPjnT7R9JSVc1Opt6kMnp6sPhMXRuRB7bpfNAPPnBOGlYQ==,iv:UhUTiPbq/0fjHw30hAty10ti4mczK7Vem33aVNIOZfQ=,tag:MrfBizBoHgEiO9VI4Qxreg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:QKluk55W8bAGFHUKEKCAr3FqfaMriUbyM6+sFd9ojFlaxOGbAPdl6qFCQXCEkNimyhAUPXU3TgDqhNXvHcnPIPPoek0AmdQmX3hRvwXroUu+O3MWeHne,iv:AUPQk1SQ0zXdW7RzxphRmML5SWAdIqNpwVh7mjLiar4=,tag:tkM+XMDdco9DpWgxIdkJ5w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:0gqMbkJywQ==,iv:y0FpJ4pLUVzEFVZtHnaKPsCNEgjtDfpTJxyFZPaYZl4=,tag:lBNwg6KXkIjtmNDUFUkCWg==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:2IEaW7ur1cLmYmWoDMw=,iv:rw7fYM3kS2VLt8mY4KQx6zuVfwk6oBM+RAFiZtzC2D8=,tag:Ngt3uXeZLRqo0vsA7acDNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKL1Y1YWxPY1Y4QXd4d2Zl
            VjgvSE4vYXREOE9XVzMzWVZ1MjNGcXJIcWprClJYWVZRVGZ6N0FhZTNNQmU2M0RT
            T1hpanFmbHlJY2hsUENrWVhnL3BvdlUKLS0tIEpJQWx1MDI2ZHY5NEROVUVzS2E0
            T0VQcTQ0MVBLYkZaNWsxdHhzbEQzekUK7LWga2ZQgW+jfRGgxV2S5phRmcIAKPgy
            gUTq8qIlDWVVM1zFk+8Uh3pvSM0S1VBkG1i2Z3Y0DBa9sQ1hsdrHPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T08:28:02Z"
    mac: ENC[AES256_GCM,data:IVYLocggDhqgFUo8NM6zZAEc0GdVlvTI23n4DkPLbEiS2orw4PiddVEZ0aAiGp6A/L/dRdRtOG+vAVStfDnNUbkDJ+BjKdT2nFcpgmBosEd1wOmBFXzJoKtprfdhDJrH8l04rfplAJvXj7YSfq9XrWNMg8py6KuOJpWzXTqA/M8=,iv:RcUX0XG3795oaAuCkTq+Gq3FPncUCIyEyoRImMRABYs=,tag:OFkbf1L2X1eteD+elQjOtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
