apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: media
stringData:
    username: ENC[AES256_GCM,data:fdM0wFuqiwU=,iv:NuwQFB6PexD522AXN4Yym8QQCbgCBCfcThdP9+ur83Q=,tag:oTXdBrhguoINY5ul92jH+Q==,type:str]
    password: ENC[AES256_GCM,data:3UFWM4LPLvPa/iQS1EgW,iv:b0H2tZ4eEPFmLoDYvQ0Kqd8eXEswjNK576LpCvy9UiI=,tag:Pq+UjZts7H4j8F9N/JkHYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNFo5VmFIdzd2K3V4cy9K
            QStPTkkwa0k4QXJYSmo0SXpGRGt2WmpmNVN3CkRYKzN5U2xFM2tvOWs4MVExclVo
            NGt2TnNwNXJiYkdyUnRMTXRvRjI3S2MKLS0tIDFxeTR1VTFGWXhtaTB3SFRWc3RW
            VHkzVGZ6OGxWdHNsWVBWK01scGhXZHcKoA1rr7DC6MvG/a5ZDUXXBIy9YUEcv+h5
            uEh5s78u1+9LmDQ7+Qj2USM6BydQlvLegIExpMyztLu0x9U1Pd8mlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T19:58:27Z"
    mac: ENC[AES256_GCM,data:+6cr7KLaovfqy6qtOrsS32K3HhzBcsup/TZb6/Q0JA0Dl7H4C8xkfnkf0bKsryZ4/s765HZW9f8uEuXbSbxWzHaJRelJ02iNqbTz9yG7MarjWMJixCrBskytcBGGuWQlHosz9RUqRwAOfuWaER0fq4TxL0lHcDhiS2oSHxCKbjU=,iv:3i050W3M10RPBoXLf2unVgjqOoMns7ru+m5ZArnoqzM=,tag:PWDJFUYYlmvPAgWMhcsAZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: outline
    namespace: default
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:PMEhg8hO1cQuXlDENJ4ECQ==,iv:skC3EryHbNCpuIrzguXQPd9/EKSqDR6NCHdKO76Yytk=,tag:/9eS+44KyR6iWF04QNnm4Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:AV+8sErDGVuIKEsn19no0FI3Pxs=,iv:Lag33va7F/4NTbad1WQee42//8SdSiiG3HHxgnVfCBA=,tag:SI4lTZu4aelBiDS0D3lFbg==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:B8vV2WyV5KUPwU2E8YEc4RjowsN1UrNfIfsVz36veVfDvfdNSvtaIxEh2DssrOdwAFdG+YhUeEw1sljavQNhFA==,iv:lIOZYZCOz9xI0eQhgUldP7403oBuMLs3PbOjWM4JU2s=,tag:BVFHedmj0bQKUfXXhe0v/A==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:c2LT/JVX4yUHZ9+zLdnOiirwJiwlaCh42FZO82RSzRhgXiSDPM3xgHYOyUqF59TLt+fjTF28PcKnD0lJ8Jq22A==,iv:NDtVz30slAV9sPb77ykhtImrmkAnvti0Bl/jz9xX+yo=,tag:m1GSOzOqy6ceXYS2fbaK4w==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:D0yTH4kDtQzDQkJ6j0akfaUnVzFU6RfpiU3pK5i1MUjxwIajAPmjjQLeJjhu+1Jk74UyeisUCLpbuZ9624C4l3pyEUJyKfFwjYbTkUgeqUbaGxD+kA8=,iv:5LLEIy71rZjrzXorWWbvTpcTx0rXUBa1RlQXeIARqqI=,tag:VXtOxjP2zqMk4PqGr5DNiw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:8jVaUhRVRQ==,iv:tE14c+OITWS7HXP05aIdNw72GJEInX+246kMRVnTFkE=,tag:zdeMm4GWHboaKOKRm5jKQw==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:hEdhW/6v2oK4BhW/bg==,iv:qMeT937Nexu5ThyC9S+z0+Uw4fujQq5ktSNw0a41CyM=,tag:NFqZzZFbZPoxY/8o40le1A==,type:str]
    SMTP_FROM_EMAIL: ENC[AES256_GCM,data:BhncFmtuvNs069frd9mTAA==,iv:hTuvYlFynhrojCZRqBuJybTbMvaPo9Ji4tBIr5dfMzM=,tag:cPW7pxVCqUTabYCJStgieQ==,type:str]
    SMTP_FROM_PASSWORD: ENC[AES256_GCM,data:Uczn5RIiVw==,iv:tBtHYdx9OSqrpZXWMm2Gys3UzOZ4JFKRrfbThBoMg0M=,tag:asNNQe9vycjP0unO3TKPiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNFo5VmFIdzd2K3V4cy9K
            QStPTkkwa0k4QXJYSmo0SXpGRGt2WmpmNVN3CkRYKzN5U2xFM2tvOWs4MVExclVo
            NGt2TnNwNXJiYkdyUnRMTXRvRjI3S2MKLS0tIDFxeTR1VTFGWXhtaTB3SFRWc3RW
            VHkzVGZ6OGxWdHNsWVBWK01scGhXZHcKoA1rr7DC6MvG/a5ZDUXXBIy9YUEcv+h5
            uEh5s78u1+9LmDQ7+Qj2USM6BydQlvLegIExpMyztLu0x9U1Pd8mlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T19:58:27Z"
    mac: ENC[AES256_GCM,data:+6cr7KLaovfqy6qtOrsS32K3HhzBcsup/TZb6/Q0JA0Dl7H4C8xkfnkf0bKsryZ4/s765HZW9f8uEuXbSbxWzHaJRelJ02iNqbTz9yG7MarjWMJixCrBskytcBGGuWQlHosz9RUqRwAOfuWaER0fq4TxL0lHcDhiS2oSHxCKbjU=,iv:3i050W3M10RPBoXLf2unVgjqOoMns7ru+m5ZArnoqzM=,tag:PWDJFUYYlmvPAgWMhcsAZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
