# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: outline
    namespace: default
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:I4YMk2lkV2hbcIc+BA==,iv:o7YKZJNbtXt/32YgKtcbCIRRSipn2syaAmzwrArZfpU=,tag:ZdAwFg66dMbVbIG2mvQDgw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:048U085GvX3zGYI3gKYWMjps4mA=,iv:DmKqHOHSySZS8bJxLYC28Lz80u0W9yLPVfUajVxKlP0=,tag:J0isUvcDfDP2bbtMkZ996Q==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:/a9X94SiWMLF5oWFXP2mKRHK4pWzdB9vG4+uL46EznoFTG7z5icDOmiQDU8sXjU+Y+bUqhlk/YK0SzbBtTWnhQ==,iv:8yBKBcQInUcac9e60pldfWjWZ+IbQ8ry41/VS3kmbco=,tag:CYFy1ncm68Mt4kp+RqSglw==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:E6iEmjpGEUjAtVAp9kVTcDgd0FeygZcCjq5bB2I842Z24eyQR7mZE0w/whGknDK04yBMC9jhJF33ogNFsQpQPg==,iv:a6x5vu9KvUjgjcXhi2rXRqtXIg9t8f2tZ0Nlm1/ktFc=,tag:x769/rSI79PZAn3somXzfw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:RoxXZupAHtzl6W0csyvRWfKNyBu7QDFBxZich1FhzqKkOKVEbckAYu4ZnHwMOEVmc0HosY9cXNtX8h8YQ7pjSsDIqgLjyzJiW1vyShbpJos1nWz5IBPJ,iv:7Tpdpgw/58E0/Y2C9Poppgqxiu8S+hw7mv6JaGZMTOA=,tag:VNtCZ6wyfyoSAEUP62Jnvw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:NZ8JKj1Tkw==,iv:ZbQ/fLZAtua4Q05UuTOg9ZnjTJ0q0myT51fvu4ffEHU=,tag:VjIaWquiWuhBFg7IwF+PyA==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:joWv8L3jwvUACxfWwiE=,iv:mh8DFMdiNDIGUmpjqM2m2hk1gfnIG+IxsizBMlbhdio=,tag:2VDOlPBuu4LqWvmpnprsoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcVVkSmNDT1BCUXV0Yjlh
            VVM0WS9Nam1aZ3dDS3UrSWZMTWVob2piWWhFCitLSy9TVWJoTEdKNGNpeW9FbGVD
            bkt2OGlEYzcwei8yamZaZDlvbXA4ejgKLS0tIFV1cTZVTEtzWU5nNmNZRldSdWZE
            N1RKbjJ6MTFzeFQ0VTNHdTdscW1zUk0KUT0R+3tEaxaamPQ6Lls7MRuvFpV6AKCI
            DGH1s64vMxHjMXjKdJT3xmvX0Mupg5RejHQ4rjkU58eBcj5hGMsvmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T08:22:29Z"
    mac: ENC[AES256_GCM,data:qNtLyydafzhGwJ+2+QBXirilSAXgm1r/p6ichkZ4TbwkV1kEFyMMjc2RH8xLACcIyUzn8gXLmZ4CdLA4SJYYa2OjNV5GsjUczkDBAZPbZKAXyEnZKwT1AVGtZ419pDtmCBoi9VXnlKH8iGOk1YaB5aUwfbPk55pDNf4JNyyWDrg=,iv:o3npsmGVVciTc4uIhjCWR00yNBJZ94Dfz9uUKic837Y=,tag:kulwRfwKWaTrGxGXvIzGiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
