apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: media
stringData:
    username: ENC[AES256_GCM,data:rRDL+xr04So=,iv:sSwtvdsLoMe6fthHaBtbbW2grbxswywBJoLySoumpG0=,tag:nstf84xrl4UF0JShO5PxDg==,type:str]
    password: ENC[AES256_GCM,data:/dLqf/niPn00DHoLpo7J,iv:6oJRo04cwEwaWytArmAZMaIXzEtxxnPjwqi/Mp/swnI=,tag:KKFHJc6BjUyqdGZR8gVLRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOWcybFI2bC9RRy9WcWtS
            YjJIN1BnckQxNjViejFmK0tnRDRhSnlQMmxrCllPTzd2SzFPTzNQY3VqSU1BbWZO
            U3R0clZnUUdoSm1EbVZPTDVnTUVZMncKLS0tIEZVRzZQRk5veXFOcEtQWUtWN0c4
            bHEweTJLRjRub0dWSllpZXo0a0ttNGMKTKRRUMTK42d3L/ABRG95Ya199dE1AoLU
            BdYG0HXJ9xED/YE6c5E/puLnM+EOqrn38jYhdi2Xc0SnRv4JaxIUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T21:59:28Z"
    mac: ENC[AES256_GCM,data:SatzM850UAxS/gywHhDKYDElkm+MOGLF4P0oeyZjaThVbf5WGXQUmM/W/nhmidoRRlgGjQ4eSGWM/KTPi+ZvKoD3Diuyp+jYNv2D5xgOlmF2ZYX4K9qxuB6iS2Nbvurii3ngVWY2IWh2M3dcBWDUSjgDt2GA9bV1VFmANgrb3Xo=,iv:JecsrGTmCAAiTNpOlYStf+7FBvZDrY75muIuFyHJ9LY=,tag:fJUuWaQOTc3qf+/hcMnWUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: outline
    namespace: default
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:SsP37IFc7uLPh1/WfH5Nug==,iv:KtO+GZgw1pwRIMstk39Mrxtg9amjQGbJBzaBkWtdHSk=,tag:UUeilS6TAe6LktJAwvZ76g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:WhUw/zgwURKpD+EN4zPn9rL3C/1CFQ==,iv:CBb0DbSPrYijnM4/vaNTS1zPcwLhA5mlSvs2MjuYzyY=,tag:cyZkO05Bz1qRv5NsI2g02w==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:DysUTns51yKNAqO9uDn6cWu2yutphRlVwNSZBCZuLxDI7cQOlFVIvHr/IRW9m4cZXWt7890I3CiDWHFp1JpLlg==,iv:b/MlMRqMcp8jtPQJDIaR5G7+Sen0T0R1V4tMZsH+iz8=,tag:/Hto3qcQi2+SPglrB+96rQ==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:oVyNU6JhGcXi40PEbdv/rMnuJc8EGJJTiPuL6mObfkZMkd9r/AtL3drNZnOKI5wFh9csvilVT2mEq00YQTn98A==,iv:UCG8Hr7scRWGxwiMpO8fxziN1LT5gMK6LubMy37gDOA=,tag:VoaehnMa5wBX9OKRnDu9AA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:OFxI8kOQE6fUVP81hWZO2HJv9gvnhODz5RvQXYtG6gNBSBHgeG5iPeWtFROTb1qiuQOJ9ucgr2PtRg/08TYGzBSEu0NI6qcUqsZdjq++MlLsZQy8KTA=,iv:3G1wLAwCrZ2zC5jVFBoBPTx7TCcoJXgMgnkkSTQtyu8=,tag:EJrn2mWvQ85UAnZzHrCnhg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:DzwJak0oAw==,iv:Znla+naK3uqtEBrfdtemwuwZVcS17wIUSZaoeQXmxsc=,tag:JRB+OSeCnp2+j8fCeOEVDg==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:vZguJN1JppyHTB1lhw==,iv:QU02+o/sh9BKcR89gnVRH3//257/NOqnYDLJmvtCqvU=,tag:GKMb6lPulBseLs/dHGldrw==,type:str]
    SMTP_FROM_EMAIL: ENC[AES256_GCM,data:IQrYS1xoqsWYuEkhSvW8QA==,iv:w9gE4Xuw+xezHpYyy9fUJEFMDBvKivLeFts0Z8ZiFcg=,tag:C2gwHEQoY7F/ftP1XQlVkQ==,type:str]
    SMTP_FROM_PASSWORD: ENC[AES256_GCM,data:A7h5hklf8A==,iv:nV+ol5maX52+7PoowPtxxpGHvqgWIjdvZVVqESryT+A=,tag:I80ORUuWGyb3c15DyvIJ9g==,type:str]
    #ENC[AES256_GCM,data:QlSYHFXoDa6hF8YFhV50U+b7iL7sPHM0A6rNiunAJK++HjE=,iv:Jak5ipir/3l1m4659GwT3wAT+kYWw1R7hn7DQonVa+I=,tag:uJJxDtHTURXoIIbUGAhecw==,type:comment]
    #ENC[AES256_GCM,data:j7nTb57ibDvnBDwr9DT0rd5CJ+Co8eCFK6wmBxAyQaueGna/Ul2Kt/m5ig==,iv:0Y2Z+IAp7GbBri00GZbE/Fj1h4F9czPybBES+LuoyvM=,tag:p7S7Cxti3gN0sC6gZ693sg==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOWcybFI2bC9RRy9WcWtS
            YjJIN1BnckQxNjViejFmK0tnRDRhSnlQMmxrCllPTzd2SzFPTzNQY3VqSU1BbWZO
            U3R0clZnUUdoSm1EbVZPTDVnTUVZMncKLS0tIEZVRzZQRk5veXFOcEtQWUtWN0c4
            bHEweTJLRjRub0dWSllpZXo0a0ttNGMKTKRRUMTK42d3L/ABRG95Ya199dE1AoLU
            BdYG0HXJ9xED/YE6c5E/puLnM+EOqrn38jYhdi2Xc0SnRv4JaxIUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T21:59:28Z"
    mac: ENC[AES256_GCM,data:SatzM850UAxS/gywHhDKYDElkm+MOGLF4P0oeyZjaThVbf5WGXQUmM/W/nhmidoRRlgGjQ4eSGWM/KTPi+ZvKoD3Diuyp+jYNv2D5xgOlmF2ZYX4K9qxuB6iS2Nbvurii3ngVWY2IWh2M3dcBWDUSjgDt2GA9bV1VFmANgrb3Xo=,iv:JecsrGTmCAAiTNpOlYStf+7FBvZDrY75muIuFyHJ9LY=,tag:fJUuWaQOTc3qf+/hcMnWUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
