---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guacamole
  namespace: networking
  annotations:
    coredns.io/hostname: "nezuko.${SECRET_DEV_DOMAIN}"
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  ingressClassName: traefik
  rules:
    - host: &host "guac.${SECRET_DEV_DOMAIN}"
      http:
        paths:
          - backend:
              service:
                name: guacamole
                port:
                  number: 9797
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - *host
      secretName: *host
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
  namespace: networking
spec:
  ports:
    - name: https
      port: 9797
      protocol: TCP
      targetPort: https
---
apiVersion: v1
kind: Endpoints
metadata:
  name: guacamole
  namespace: networking
subsets:
  - addresses:
      - ip: "192.168.0.125"
    ports:
      - name: http
        port: 9797
        protocol: TCP
