apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik.yaml
  - guacamole.yaml
  - vaultwarden.yaml
  - proxmox.yaml
  - synology-dsm.yaml
  - synology-moments.yaml
  - synology-drive.yaml
