---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app invidious-server
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
        #  dependsOn:
        #    - name: postgres
        #      namespace: default
  values:
    image:
      repository: quay.io/invidious/invidious
      tag: 12db1be87b581b7de616768995e1e69f21a9b691
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "youtube"
          hajimari.io/group: "Media"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
        hosts:
          - host: &uri "invidious.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *uri
            secretName: *uri
    persistence:
      config:
        enabled: true
        type: configMap
        name: *app
        subPath: config.yml
        mountPath: /invidious/config/config.yml
        readOnly: false
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
