apiVersion: v1
kind: Secret
metadata:
    name: invidious-server
    namespace: media
stringData:
    USERNAME: ENC[AES256_GCM,data:1KyDUvlvYSRI,iv:pNutI/RcEzceyq8435ArDXmgl+nwqzshflRnaqNkl6Y=,tag:tj0VDk8mg5lGvCPvN/ycTA==,type:str]
    PASSWORD: ENC[AES256_GCM,data:A1TBaphn64jIGGx3I8DX0GwWCw==,iv:Yb4GAUk9ShdblQCqE0y9P9vnG8IlEP92vBjr0SSUFuI=,tag:QVO/qNwLPmQJSjahsNzy8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cjNMU0M4SDBxdFB4UzNF
            eUh1azlzLy80bHpLdjRkelMwWUN5VTJLaWxzCkhYemVkMWF1MHpycHdhTDVuTld6
            NHRJYXVxOENlM0wvWElyTXZ4OWFUdDAKLS0tIEROeHNIZUo2NHhYK2QwTEIxbmNV
            eUppNmdtL2tPUmNnQlAzNXlPeGtHRUUKBTi5STqQf7y2WGBzA93swbp9iNse3Q0C
            Y/GrA77oGXfnvOF9vKKjlfiG7picS5ved62zbouBs1rArTcPsSoIXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-26T05:02:04Z"
    mac: ENC[AES256_GCM,data:4YqkicVcJQo9mU/Wfi6RuiKDPqH8dncMsH1jRGi3OihjTdo7XD/Fu3Dnwv0l68mtZe6c9G0cdFpprevnSmld73E4EmcnslqLWD2+1JNsk4q04QQFxZaQOYSq2OQChPftefXCDOUcqSMETkGa03DIXPFeTeJ43f44chh1zqa2wIc=,iv:uK9hUmlzm2qx9iz4GpMKPQHLmuxj0FqTTrwSl+F1cCw=,tag:z25oSyH/nTPi6moByvT7lg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
