apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mealie-volume
    labels:
      app: mealie
      snapshot.home.arpa/enabled: "true"
spec:
    accessModes:
        - ReadWriteOnce
        - ReadOnlyMany
    storageClassName: longhorn
    resources:
        requests:
            storage: 4Gi

