# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_MARIADB_PASSWORD: ENC[AES256_GCM,data:ZoSlqmzoBgAWy/GOK9OWNlbbGQ==,iv:h0875apn95RUazu7uCDnuBhC6kL6ZM9vJYaT65J1vEk=,tag:LPVje0XCcM0P0eGQJP/Aew==,type:str]
    SECRET_MARIADB_REPLICATION_PASSWORD: ENC[AES256_GCM,data:wzDZij/RTnbRI9Y+EXRR8tQPR7LzVdC2MDgetWs=,iv:DmCIaZJmP5B6A7r5hEHzDXn7pGCbmCF/YnGEXu708PU=,tag:AQH/oSJ6J3Y57jp/nxDbzg==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:uysc7kN0+NxKGzsEHMLldOrG6CnL7RfbxKwXQ8IkBE8WQT8hLA==,iv:aNNdCZUuQ8yUC+/u/Hcc1gbwV7yu0gKv25LpUWhcaLE=,tag:wflSAbWaGPhc6adru2d2eg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:QE8l/U8bvAWmxsATNMPkyTXWOj8lKrs=,iv:3W4XXwrqn4t4CJF6SZZBGa54aKEMEGMVzIMAC5YQ3gs=,tag:cmg5m5jbP9BEv3i7V5CAaQ==,type:str]
    SECRET_PROD_DOMAIN_MGO: ENC[AES256_GCM,data:qulp5DQZTuWO30KtaTqH,iv:7Uwt/ar/4j5Cm6jH4lTRhhJVEythZbuGBDITo9L7P18=,tag:Jn4K7CSFE2dmwAqzn5ib4w==,type:str]
    SECRET_PROD_DOMAIN_KAOFAMILY: ENC[AES256_GCM,data:6jb0IVybpwtvnA==,iv:DEGBcVI3YRlfaHQUDXS4LpVE+r66zI9n7LuFas7gJZ4=,tag:H69ZXcpor5Ln4FsJAqV+5Q==,type:str]
    SECRET_PROD_DOMAIN_KAOFOUNDATION: ENC[AES256_GCM,data:fUMfHIJvxeRu8IZJYJE=,iv:gUi1tmYvcwg6suhFGh0ZIjGEDdBCcQGzbVYxHOTxRf4=,tag:OeWML819/8ua+sRzhlYxYg==,type:str]
    SECRET_DEV_DOMAIN: ENC[AES256_GCM,data:Luo3ACGyPeedjFsH,iv:26WQHAWpgcpC/hRGCXW0P/Br66CLjZpx7WJC9IjkNLQ=,tag:+iOqN+FQ6eVZTejMxbiRGA==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:lBW3ML1RWN6XXP4=,iv:+dZNjF5GrsN/zsnI7LL0/NL3NdER/XTBYbUlPGd+2Ds=,tag:M/AeOHS46dy9CietTndF8g==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:Qgj4rxkhtQfPoiA=,iv:Fxuvjdwcl9xg8lcQuMGXuMjpj8PSw/iiS4585kHqSbc=,tag:V8Qj5qYhd2pWB21e/lJJDw==,type:str]
    SECRET_LDAP_PASSWORD_AUTHELIAUSER: ENC[AES256_GCM,data:Z6chyRLbzHr01TA15NQ=,iv:d7UNrTaEAYIAEjTaaiIkIc3SmneuyUoysBVOU0bRzWw=,tag:hpS/FYOQnHPpk+n7fO8+6A==,type:str]
    #ENC[AES256_GCM,data:5DGaK4klUSinK9GgShdM8XE2+zCr3fGN7rHM8LbavFLor4l5YRK1QhTBeG2w61yaz4JUq3vZCdH2MGf1Bw==,iv:JqT71AZ0LpA9PRhFJTw6jihbzesLdV6RVZ56DN0kPDQ=,tag:b3NdxuDdfDo2dObYDjj6FQ==,type:comment]
    SECRET_TEST_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:BTe3sKJK+9Op0a6Jz21WROSj296h2hxXaLcF94z6wgKe0tWg7yxBjRN7PjQzSMRXRrQu20lCyZGUvrvbXggrNQ==,iv:huhaNrggUwmB4+kMyjdVfYlz9VcVdAEvDA+7xdSbYZA=,tag:O5mKPCf52tyokevMp1EjkQ==,type:str]
    SECRET_BOOKSTACK_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Hj6Ex6B5gVckILWbkDeOAD18e5I/5PGFMSP2Ly6xPxdc++Xh3xzT74C4gR9TwtoQHkEmn/ym2c005s6zUiniDg==,iv:F0P+x7Ykye2cirUHTEmzYzCtZom3sFSxMQ9q1cYvSq0=,tag:YLI9PKtW3gMpnLutSq1oIA==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Zi2C17PCoAcLoV0yfuBXBPxfyb7fBDDeBAiEj9xXVSRRD5T4H8BEIFsfEUVAUAEMswOgQZ9jzxJWU49YTJJrpQ==,iv:2pQ2JyN5LK03RJTjQV6gDbVt04gSm+VL9bo0tWO2fBg=,tag:D+f7rxwSf6RMQtHGtCcb4w==,type:str]
    SECRET_VAULTWARDEN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:r5HcQgV4FFkaj2DHsSXkiQ25QTU5StN/+gMIYf5XjRUWo89qxRfAAQ1EMIVg0H49VeOkOWgP4NKaW0pp/MdVgQ==,iv:MblNe0XI4SsBa/ErHZ66uGb01ndnTjtjqgfgAkTUrl8=,tag:COomSfzB0VAKxDpa6jJpag==,type:str]
    SECRET_MINIO_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:wU5yTbrc9cWZiO4yB5F+BQ9DEvWifELa1XbJM0lqUUppFnZfW8QZGn85bDWfmLPpVianNGm6ahiZcrKnSkG2Ig==,iv:B2G5HhepTxSNRVIfqhhS/qMS3BuDDS78Y+LgRahmKx8=,tag:Nnia6TZDzirTgC81lVOPPQ==,type:str]
    SECRET_LDAP_ROOT_PASSWORD: ENC[AES256_GCM,data:j1YIkJyXk2Tm,iv:B/bH+tlzlsDa88ppta3jg3zmwWnxXr04PJmRHGN5Dm0=,tag:BQkJs79Q8e6/SGa41a/QMA==,type:str]
    SECRET_SMTP_HOST_AWS: null
    SECRET_SMTP_USERNAME_AWS: null
    SECRET_SMTP_PASSWORD_AWS: null
    SECRET_SMTP_HOST_GMAIL: ENC[AES256_GCM,data:FToelvNq37gvXJCS9To=,iv:Yx7ceEhkMenE97nFwUj5hk4cPD395WNCLXaoK6eGJXc=,tag:CXizM7snA5pimW8n8KnJ4w==,type:str]
    SECRET_SMTP_USERNAME_GMAIL: ENC[AES256_GCM,data:4xpA4ksyLw2zxGZqzfnk3A==,iv:03pC3tvwJHhn7KGne9+KckzzKqnafEJKQbOa5t32xEE=,tag:PxkDiJZ8MfDQUhtGscFiJg==,type:str]
    SECRET_SMTP_PASSWORD_GMAIL: ENC[AES256_GCM,data:VVYGLhwekg==,iv:AFhJn+7X6etz5LsAXgxNaw5wB/UP9mHWiYHKQPRQY0c=,tag:ONwrrmP34l2mTu3qE0QC1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5THBmSEZiR3loZE5ISFRE
            dFRDRE5pM1NyT0lUK3BnVDhNa0hXQTB5bUJrClVjSStSQ2drYnEvQnNrVVcrUzFa
            ZFo4Q3JqY1djNlZpMnZ3QmxFVzBBdFUKLS0tIDRTSENzaXUzVGVOZUJmRUVseU1m
            RjZ2bURseFZiQkJQREhvLzZpTk10ZmsKIoQiDUCwAoWcppBeDU1tIapx0X7wCQtK
            WQioXFpxRMr/JkZqVhGdA+7Xc50K/cH0o9GGYwzCM/S4uc1OuMJtSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T06:19:21Z"
    mac: ENC[AES256_GCM,data:sJPbXsEijZK1B55cTUVZal6MAJBfib+Jr4eSkmAmOTyEN67vxc3g06RysMckeNNq/OgQuWqCLLDOFTSuLYo70u+MpxubHMipUOcHNPkW+eiN+SG8Botp5oK80j3TUt8bVP8afjnUdfBD8981hgu4K33DG70KLjE6nbd9s4Cq37k=,iv:HMH0t4e0ZzdT58cqwNvjJb0BmpGXWKWrUPYXJ0vxmxw=,tag:12oVfhCzyvlDKWhRGkB+TQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
