# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_MARIADB_PASSWORD: ENC[AES256_GCM,data:DgL8hYUQRlHi5ZnfKVlICMdBOQ==,iv:PfYCQTXOYU2sLj4EmjN/iXWkLBDGR9wQ+7NOPMi2fzs=,tag:rvBmyq0deE6DhjuBWw690Q==,type:str]
    SECRET_MARIADB_REPLICATION_PASSWORD: ENC[AES256_GCM,data:V3OwWbSjNslDWEhmQ9SKN1IzgvaLwBJ/DPE0mBg=,iv:1jYf92WtWD2TeifWwtvf4DRbj997LcmIBgJ4fWBm46Q=,tag:oROGxebjmL3NgYYqIXzEDw==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:YhAttSGJ2lRy7y3AUPSsmvusYAJqkRk67k3OznCpXwqBDdPV+A==,iv:MCRsU1WDixhS5qlNF0uHolKSzy8V7CGDhyJDtr4/Hsc=,tag:kE1Na9ALt8mwCcpntNpa0A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:CWEE3WY4VdGqo0mu0GpNz1BKCkeHtbI=,iv:FrtBzdRvsS7mXAzG9A/6qY9I693EZBLcQorzX1le2fM=,tag:kRjzDCMLru+HF6Ls06xeUw==,type:str]
    SECRET_PROD_DOMAIN_MGO: ENC[AES256_GCM,data:ZX6jeNDP5EVJU9JJodld,iv:o4LmuNQLJ0tiJVxusWOSWyt4BvL7HliZqto2eRktmLI=,tag:PzGnCtN4q4WZ6H6Qs2nnuw==,type:str]
    SECRET_PROD_DOMAIN_KAOFAMILY: ENC[AES256_GCM,data:RfAfNM3cACVHEw==,iv:g74qM4rsoyBylHD1P/qEJwLPkaNMjkZVy7Gpfp9Sz/Y=,tag:eJxaRdk3y2m6VigG10+UUg==,type:str]
    SECRET_PROD_DOMAIN_KAOFOUNDATION: ENC[AES256_GCM,data:v4s27jAod4FLHn1q0oI=,iv:Cy30EPZMCjyvFw7x9CAMl32GbssU8oGQTvlimEXzQGw=,tag:x3tdESV/zwoCU7GH/Baa4Q==,type:str]
    SECRET_DEV_DOMAIN: ENC[AES256_GCM,data:Jnp42D6P2tT0bA/K,iv:sod6JTIyCbuEtCtN0O7y1atP2GoCoF90lANA5/Ujecs=,tag:di1KvzuNnwkH0HQPJ2reEQ==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:KgdDr0UmQXimYjo=,iv:bB0jsnyhsu+SA0gckdJNbG5sOxyLlriLQ7YPLnxL8es=,tag:nInt3jOypEzk3+S/p2yhNw==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:F01pchuDZgqNYOw=,iv:k/AWrTptfYw14ydBQuCCQoaDWoNNysq++arbtSikuT0=,tag:eNP2wlbSkxezHPpte3kSfg==,type:str]
    SECRET_LDAP_PASSWORD_AUTHELIAUSER: ENC[AES256_GCM,data:CaTbK5emBXJ4WCH7gOg=,iv:nb8C4JZsHEOVdzL0HFeVVQo8EJBETbeCHu6ciiSYoKA=,tag:YPjrP5UEY8lsUJxF8PqsjA==,type:str]
    #ENC[AES256_GCM,data:HVBr9qFcx6EDISjthjtCG/rUCrXdhWkYHYhwY6wagbLmR97KEeGumdEeO/szhD34627b/xHXHncOB3oGyg==,iv:9bwaSEPM9NrA9mkbGlaGWdJW5MwY1Rq66NYn48YhO3E=,tag:xheO4EerspV+XiEu3BpE0w==,type:comment]
    SECRET_TEST_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:TOEYJ/oBaoo9XRoOIQ9Q+Zp1TP4Tlu1S8vPKmLhg/TTcEYeT6fx71GZhqy+/gOfpqUaJbvNRxrZfgi4O7Y4+mw==,iv:eQpeufLFcSo8vrKcFeJHJFRVAh0vzDp3xearm93s4mg=,tag:stlpPouIQDXt4IVQp4v/7Q==,type:str]
    SECRET_BOOKSTACK_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:by/gbIC+1zdP7lFcAz/spLYWpKqErNDpOnwm3alWOj3jYzdq8uCtVXTiGPyBmozu2JCWj2MwGEyDFjhag6OTyw==,iv:HLnBzS0FrGWJMSIap+BCQYDBi5xO+EYBVFsBr6ln3aA=,tag:2rsHsY0RvY6tgHbxJo8mkQ==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Md3lF7Rvk/aAdq2R8q0l+LHmyUdqDsnW8IBxSlw1cqQTzhEVpbeBbsLX3Y5NCoMMNbdxzSPinNmK7ONFoNvaVA==,iv:cr0GmBQ6FXOBB/iLj8xkI7V0af6Y4Jn5IsFmahgJTeU=,tag:zIQbP1BcfnU0EXF0banZ7w==,type:str]
    SECRET_VAULTWARDEN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:xpTmWLi74RceuE1zUyngPd7/ILnhy3SR9lgNhuo2IZ2iT0DHNqTC4kqYI09ageDdqIHj9spWyKCPcR2NzCiXdg==,iv:r01wZkViQR6QU58jvbJpkemNv0FQIg+qhNGGauqRfJM=,tag:SeLtnqiMTBXUyymM8VboTQ==,type:str]
    SECRET_MINIO_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:fMTXc5XVTt9IC3FAosxpqKjLFaEl96vgWopJgmzKle5HHp5G0IW/CC8iUkhghedSAN+T+T4PNnIWGFyNNvb3Rw==,iv:IXZhcUHCi2by+wEVCj07nYJTsqCe1rBY3r1eQZati1w=,tag:9RBOCBG3/CMNjnud88DpEQ==,type:str]
    SECRET_LDAP_ROOT_PASSWORD: ENC[AES256_GCM,data:aIACG4mg3RvC,iv:HClYBFcE7guyrxsjrk7f4tBRwwwH9ajcVaPwasqWQs0=,tag:LJjqrM6ZLbM7FiIqj3Uutw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VzdsaVdkRFpVY3lxZ3VS
            Z2lFK3dQRFRBRDV5cnk1d1dzWkZBbU83L1JRCmdFb2V3QnQxOTdncVdXbzk5bW9F
            aHEyaGhJMXZrYU42dHJQRSswbWJQU1UKLS0tIDRrWWtNcGZhNE9Fbi9qaXRBek9a
            aU1WVGc1bElZY3dodTJwQXRBZmt1U0UKjtemQQ2pvSYd4cIMd5gGd3eEAoMPuarC
            5cn1k+FsMpxRppT8mToqOKcwzGleQf/IloL7sSr0UcVnZHrsuB4hgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-23T07:21:20Z"
    mac: ENC[AES256_GCM,data:T448zoamRjZFQJnFO9bdcJvB8b/SfBIbzyP+K/11ZmnU9cDtytYLdX7tb2SLawecIIb2ujiACWVpA3QR9n45bEpX/8q0PAQPylfyiTGJR05qSccVNimvMcKSmGZjXVytorNpq7XT5DOheaonK8d6GqlDqmr1xE8PNJaKjKpEWV0=,iv:XsrWRBS0ZIY5qn1xblTIjJIYx/CP6Lxzw+S7+ii+vOI=,tag:VkEtZARLz+YCqP0eFA71ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
