apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
    - name: crds
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./components/core/prod
  prune: true
  wait: true
  timeout: 5m0s
