apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: networking
stringData:
    username: postgres
    password: QkAM7sf@8AExe&7
---
kind: Secret
apiVersion: v1
metadata:
    name: authelia
    namespace: networking
type: Opaque
stringData:
    JWT_SECRET: xPJGATKEOPauNAtbKRnPTL2x14W4xEY9ibD1YBX7YatOhcDo3WbMzCH4gilbekR
    SESSION_SECRET: vclg94sHHAN4LvH9iJgdnBK6E6AMwA23FzkNR91a448BGnkmX9Y3MYCrQuWNdg7
    REDIS_PASSWORD: ""
    REDIS_SENTINEL_PASSWORD: ""
    LDAP_PASSWORD: RjN8GK92Wija7j
    STORAGE_PASSWORD: authelia
    STORAGE_ENCRYPTION_KEY: rbpPcBsTMZqxlspHF0UfuEiGEzaEqohHovdjKgvkGKdBc10dWzRjwfbByf6uX+iN6G2z4soo6s1jMfA1NdlLvg==
    SMTP_PASSWORD: BMeIuJVoeEQKD+7JfSZSDwKU8H1eMvAKD5Pw7cui1OCR
    DUO_SECRET_KEY: eV6WY3i0md0rb0D1RWsngJ0xHlTqsu2DLUlMBFe8
    OIDC_HMAC_SECRET: I3MnpYlKTqtjQ4E41nahdopKKFBTU5DLl2TuNYEH8mP5FCLpXZifv0K5ludgmxjT
    OIDC_ISSUER_PRIVATE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIJKwIBAAKCAgEA2dJQF7I6/rNo/MRVxRxH0Y8V71vDPsPyCAy1/9vn5vU4FR8C
        XEXcYsvnY4dqfcaQwEKA7DgmXyCP6FMqe3gDWkLNFOAoMgA/Ks5VVDqO7c2+/P6i
        Hnz8KkxB8Fa7iEXpK4cTwmZgbSbjzOe79KFY27hhNxFebaqtoLDNZdiWI1U7byBs
        gHh5zQ2AKg5ScGBaMtKhYSSKcHh5r8Ls9YYbKCWc0vgCu4wQHyM0EUDXJvdQfgCI
        gwaTD64pIE0qWwI3Jty5QIJLyX/okpViptR3T6YKwrFmZ192d0O4QoIbr+UK4mTI
        KbDsXOia7evzsOIwntWcLJXbBcqDI3J97T5+jEV7qVHVNodTtFHl7ssclU49tsMn
        X6x3otMRBo/0qAapRN9NX7qanFCLQ0K4KHTsYT8UM6lzGTjZDMtENAo9xdNrxD4t
        rSgoG/j9RclYunMl1sxgKV2bp0DQ5kGv4undTJOooZKEHNC2rcv+RwTDyYCEJ8ZH
        2ssixMZvJXDi1XZchyhUMVmGgx3NFVzIIfmaK4s+PoBkQN3TXmWKLxUPPm1MYvKe
        SCyo3vzOYHmv8x6yx8zQqtWgeGSfoqwAkJc1GiKYDjSSrZwcmR9ow4WfLxR0swgS
        f50/IwtHXxGTjhn/iI/dvcjD4ApxaI87Amp7dFYjU1eGDfqvCyE4xduAaaUCAwEA
        AQKCAgEA0K2eMbV8s3qqQE7QZPB9FZThTNk6qi0K+Q9EZYUGHMwdGI8GseP0CWqT
        mVSofyr2jlqoLKZ2jHgjpk3Wy0bk31pUI4XEvHJkEdxu/yzCtayBJtvD8TWIV/WK
        zngpXZqskhjsozd1ddzmLO5tsSXKfWWdLSaksqfrg6Eehk4DOIJ1WDdV+5ZwCjS+
        7oueCy8j+sCz/t8FCk9BNVOntGjwJ3wxTCRyab77yvjs7wKRnTEemjhkkDKCPWl6
        2QlUZLAwqjiX+edaOAckhxo60t2GGHZYpMFT/AEG+6eTJZSEdfUWgmJPKTHon/Hw
        S7PbWUC5l9HJtyUyGdAz5ofPgLR4gqExPc+Lq22b732YHu/nmvgXIbydvlFVFY3L
        YxpVAO97cTV5ncXM1sILgEwJq0KiR5XbOfDL55n7eMz5QeLOMiuC5epGJn2nSInj
        sNwUcAiuIDJ5LFbvviFw4TfSUDoKJLHT3W7Vkt4UbdG+ycwkZhF5dXAb9qLQgUHR
        cu7jDxtqueLAm1eGXhPO2ubBn3MBmYvORMp8ed7ZZMkS2Pb+UthhB+H3mvQq+7T5
        FXrMZFWhZhjCci8j17c+PEkMeY95sKWVEpNTeMhw7zoxGo5BxrRrkNcspjWbQbUW
        Hu+GUdcB6E1PrSlQ6OF0Czdz1zWrf4KoKlgzEq1/UHTBuq49jFkCggEBAPdzoAvc
        rGsCjWLLUVRnlZReiVEB+UuLc88n8o4ePEVJLn464QYtOJzA6qC9w0gBVIC0cY9M
        JI9to9y/O6G1aXSLVQbykzG1V0FjB91m8r874M/IrLDdauVoZJOUfVPB5d5gA1TH
        FzGAxzTk4gVSrrMeG/PjyMxPZvjp/5XM9is2a9J8/+2P3J/iMIN2puF8wXOWpOaV
        8DFII4/UwLrzSwg3TuP7rDS6Vz23lR+YtEN4fVefhh8ynmobYxh70q8/w8Y8KCaX
        KQlic1rEOogH+dwjdlUVmHXD23o4d/x4R8bJAmO1t5H5EamNTYYCZv12q7s6gnAW
        +XeeyqgcPinTJDMCggEBAOFYpjtB+gMa9bCVZeOxMf4mijTZda45KQayDgoCFYaY
        R021rFlULlnLVOATf4nPXzQI4QhkU4R9o/xyh3MLMMsNaOx37JD9GHYFh66EoRHK
        PE9r44Vt1ZpsawozJJ/se/vcNGHiTFlR0qKP7LqO8zIP3R8pWoDx/sAgkrYYh9tp
        /1N7XN6N5ZvAciekUsyhgHJia9/ZeCMj88XhyMN8plBcnkqS/1em1bSVJCP+Py61
        UlnSmBpjnSX7M+CPlcbvV9kPwfoHHQZ76Y64++i0hSKVgMNnxcjCSQI0hSd/loug
        zHxAchSEjYGpM5uu3y9kDuGtVv+Iiysfl0u0laetoscCggEBAN/n8wjou+b0X0Tm
        3oe2VwXy6OOxGoe9/qOS7Qql1zmGd5hm5Ji3MIO+mE+shdhQw8rV+++DIY3a0qv7
        KhUv1uVK8jwgIQqYoQScfFBdSAe8QbciSQicwY4lgOR9N04jpEEstbbvk1AKy7ZT
        6SSR5VxUQUzVbytYKb/P1KIS3SjKzJOg4d9vDl5pyCYcpfJg9ZcG192CDN46/Vq3
        U1GWte0QRsVKRE9N0YUZ6ci2X16x1xEDWtQ99FPkxi0wVbqXwylL47TPkKVaPTED
        YEcYmIEWYYupx9O/zofwMrnziFcaKZxZoGpoag/2uRAqelCdIdV/oumUEFWqDIxD
        SgiEcjsCggEBANHXn1RnJ81keY2qUWsqQoeMk/6K0c8fY1jczb38GtdvTlbK6md0
        wITVl3/iKE3IUbs+2W7bHfqulNosPH2g2hr7rc0mD6EkTnb4x1R4JRVP4cGDkida
        FCLs+vBQl7ZknT/32r+b38T9MMw4ghVnsIfZxeuSsriIoNWAf54aUci8eArhQaXt
        NPdIygSoPIJZkibyB8o31GvEuuh2TGHd3XHQDYccQ7L3pOG4UCNESsnQB5OlTAam
        5FvOBI0EqFDL6F41Ekkl/p1fHirNj6cvExsVZQaRx9gfM6VeCvCxGxuC7Wh3CsSY
        er1XNruuqB6ValY0+GKUYCQUEutoikPOqVkCggEBAMq16DrluYjxO3HcXVJUbTPW
        8S9/Aewc4AAwUs+s0GQTALm1VK9j5rp9ejNRhemqfbwyLdICkxyUEOVkwclnzJLZ
        L86GC15Cn1Bqi/cN9b7RDfeemNvBCKRWhyOjWlqsvbTXaoAZAGQoY9iXqsNgBQHa
        VPcfcRL1rAWaukQDw+ZC/SRoPrBkNDuc3CEK0hABxXQDYRBSW7SFHiURqaj6xh1/
        TyygYxwJ+S+/TcmIKfNF+rrrQBD1XhVS0czGNP7a/3Lc31MOwTgdMiWk0OXCAihQ
        J+cwO6ehjlexgW+HIE7d93BSz3GeGtbopwC/4Ez4AKBij6tM7AsMaa0B2UKROCE=
        -----END RSA PRIVATE KEY-----
