apiVersion: v1
kind: Secret
metadata:
    name: gamevault
    namespace: home
stringData:
    DB_SYSTEM: ENC[AES256_GCM,data:lJTw6kSwQhIfTQ==,iv:0pOKKT/hdI1ViHTzz+kpNJ6tgdN5szIsxfcGspejsHg=,tag:xUWVmpncyBBPJpGTxte6gw==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:+HPS9w2Z2mBK,iv:+IpQRTyBpjXRje7xZxrUCcOkKuFKTnkV7UVdYXbrU5I=,tag:++UKFVE2R1udji2y7JS9Wg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:IYVv52XJwX61,iv:jOb/JhbiAzMGIMWFDwmbHD1zVPyFRdTUMFK+KTpOHSI=,tag:bFotmuKoHLoru1yiRD5rBA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:3nwclrd1os1gH7nKDFaQvvK78XkkiN7JRhgY77zElHD3WAQ/S362jHEr0IGNzBFRsbgD+KiPoW2kSJNt1Vg3EA==,iv:OOpMT1lEoOanQrU464IcM6VZ045+bsy4touMStHdZOQ=,tag:63kFSn+a8xWicX2lmsML4w==,type:str]
    DB_HOST: ENC[AES256_GCM,data:TOxbarH90fWXky1aiOv3WnQR28KyKr7WK7X9R781v27foPOf/4tX2A==,iv:Lcr3iWKi50pOUlNmPaxTMTVVwz/OObhEm5K28qN+FPU=,tag:uEkuvDNTwNCZkAcJqnTA1w==,type:str]
    SERVER_ADMIN_USERNAME: ENC[AES256_GCM,data:2wF2Oc0=,iv:ABwTHKq71I22rMVHiFXij2M7q4e4JstVmleBwD0Qg2I=,tag:ZYrEJ3MBD+LofmoE6EQlRw==,type:str]
    #ENC[AES256_GCM,data:l7elQTTtyyuFceqLsAwsBeSKXOXX,iv:IfgJQfskzMlBtSK+215SVOpu7tpc1QeDrclZvmyE6oM=,tag:9p48gfeWwaqAsrdTTwy6sQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQmN1WkJLM1oya052ZTV6
            alBZNWc5amFoUCtZN2Y0cUFZN0haeHVrNVM4CjN6VGdndFJDTSt0dlE5ZExENHVq
            dTBsbVRQZG9tSFNmaWN1ZGdHRzV3MkUKLS0tIFZlMXlvaDFKWUx0ZjMvTi9wa2lC
            M0hZQjhuZEVYS014SFNzUTFFOEFuZGMK2ESLLe3CWJFYZ9FI2eKUlO5Z8s1uvVlf
            R3TtnUOBJaEYlix+AYNTHRlQpUR27/DZSyebS5hDWqTNZyZzUmHavQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-25T17:02:15Z"
    mac: ENC[AES256_GCM,data:ulpuav4oMeXVl3vb7YpKYGWLknx0oYtTed3agCxHIMInaxikWunCkEyOAOHbGgEukh5VE7x47Yut2vKFF3V+mfaUc9ZuqMeqaqOL3vlcOqdPhN/LMR2r2B8UVeLDFkfmjHsmmE4xfzQ1KPkpGvRw/Ao5ylVvOBs8jA92unJswNo=,iv:wdMQuG+pzUqHeHtkdx8Bt4mKsw7XKmEaTdwMDr9SjJU=,tag:d4b0LedvODvepgDpUmg95Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
