apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: redis-secret
    namespace: databases
stringData:
    host: ENC[AES256_GCM,data:Q3pwwo/P98jyZDCm3+0MP5rTVt2A9Ktzl8wO/AEwmi+bJClvW2lZog==,iv:PouxgrQepp4XK9Qsuu9+kzYJ8bQcvrYtqS/PAXkYuBo=,tag:thQhmy2gvuVxc6dCl7pA5Q==,type:str]
    port: ENC[AES256_GCM,data:8CDyPw==,iv:JeIO02k4xgWY9ms17Kl8JCH9V9AoGspVbcxTDb1xciU=,tag:+YVuoIZMpmMsiG4hTWSMoQ==,type:str]
    password: ENC[AES256_GCM,data:DX1C4JmdpeK65Mjzyk0=,iv:LeOZtbW8Fdd6SIPQV81cfpbG5l2teO43qbmh6CiEqic=,tag:7qEFKfvwsObxrvIjbMhVBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWDc2a01WQ0xnVWpKRnl1
            aXFJRFZJaW9yRlBoUEwwNjNlQitYcjlqR2p3CkV0N3NnRHVDaU1DTHZsbXg2UTln
            Q2ZzZUZzYVRpcWhPWm5INm8rWjJXOFEKLS0tIFUvZzd2cjFsTnpIMEJ2R1VVTUdP
            SDFCaWNzY1Rob3MxZ2dsRTNMZHllWW8KMAkH9rWmJr//GnGUc2q5h4eBtWUWb0/u
            Fg6SnKZTfRTxI1bo9vjmWJq/95fRQDzU92SicSrgZan80KwQch/kDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-23T23:59:51Z"
    mac: ENC[AES256_GCM,data:V+i0jrfVWQlRFl2HbZoCJmO1oXzBnxJCjqp6pUcBn4gPW2dPHHrhaaCzsek52W3uEkoEsUMvukpjhVuh63c4RnsHQs8lHxyoczUA+i417k4mzEOWjoAb5WbwUBM39fybVWaHZGFGH2p4uAch2EkaHcLjw8mK9EmMX0UKTzpFB1M=,iv:sXX6prXsXobWqZ6N5g1bQVNSBSVcR3q+p+zckGFVYwI=,tag:/QnnsqURYuz+Gxlmb97rZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
