apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: minio-data-volume
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 256Mi

