apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: middlewares-minio-headers
  namespace: networking
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - OPTIONS
      - PUT
    accessControlAllowOriginList:
      - https://w.${SECRET_DEV_DOMAIN}
    accessControlMaxAge: 100
    addVaryHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: chain-no-auth-minio
  namespace: networking
spec:
  chain:
    middlewares:
      - name: middlewares-rate-limit
      - name: middlewares-minio-headers
