apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname smokeping
  namespace: utilities

spec:
  releaseName: *appname
  chart:
    spec:
      chart: *appname 
      sourceRef:
        kind: HelmRepository
        name: nicholaswilde
        namespace: flux-system
  interval: 5m
  values:
    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: dev-infra
      port:
        port: 80

    image:
      repository: ghcr.io/linuxserver/smokeping
      pullPolicy: IfNotPresent
      tag: "version-2.7.3-r5"
    
    strategy:
      type: Recreate
    
    # See more environment variables in the smokeping documentation
    # https://github.com/linuxserver/docker-smokeping#parameters
    env: 
      TZ: ${TIMEZONE}
    
    persistence:
      config:
        enabled: false
        existingClaim: smokeping-config-volume
        mountPath: /config
      data:
        enabled: false
        existingClaim: smokeping-data-volume
        mountPath: /data
