apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key-staging
    namespace: cert-manager
data:
    api-key: ENC[AES256_GCM,data:xMctvl5u0V02f5fR1m2lI00FnIeFmVw51i1rODe5eoNbyobw/83W9x0DLd4Of94jlhlcVw==,iv:iCzhQAz37EIvwBgl+40+AaNt0i5+HT2MtJLxjFwSbMY=,tag:hn0QFCdvyiXV8NmgAaxwjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaek5WVVZOYk9FTkZ0eEE0
            ZXk5Mmc5NzV1cm51ZFJYOEYrbTI2aWY4VUhRCmxxa0FxaHFVUUlVYjRlRnRwWURY
            NmtEeURJdnRpWFBPc2QzRDcvdjlTcTQKLS0tIDI3UFh4SDZ1WWpnUnUzakRhdVVv
            dnNLSlNEVmVsNHMyWTdSWGJ0UzJJckEKTsMHlPNMy/KBndLDp740hiwq88gmPgZW
            zaO1tS2l9ERgDNemeCFnGw9xUollZdJm6PggH+dgzV/cwPDADBVZOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-22T02:53:16Z"
    mac: ENC[AES256_GCM,data:OuOgOs2Yjhl1LE+jJ+5IAm4wHpoMpbf3TMWfQ3LFxh50JK/yNIk/Wzkww1Og+R5zeJvHZMJNj6mQuPDAUFb+gAnlluW/2+gr9z2AGaJjdv9g6hDaYN0y2+VoDhjS38wvy3akAjpmOVVojFOXB/u6+cNuZGW20z9bUSsy/57pqAg=,iv:OiKec1INHU8iiT0gX15AuBJpfFDHVMa3SFRhbjZJu8s=,tag:Jukg1rAuER7LcPihWZeT3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
