---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: defaultpg
  namespace: databases
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: longhorn
  superuserSecret:
    name: postgres-superuser
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://cnpg-5wxuej/defaultpg
        #endpointURL: http://minio.default.svc.cluster.local:9000
      endpointURL: http://192.168.0.120:9000
      serverName: omoikane
      s3Credentials:
        accessKeyId:
          name: postgres-minio
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: postgres-minio
          key: MINIO_SECRET_KEY
