apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
  namespace: default
spec:
  sentinel:
    replicas: 0
  redis:
    replicas: 1
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - echoserver
              topologyKey: kubernetes.io/hostname
