---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: shared-vol
    labels:
      app: shared
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: local-path
    resources:
        requests:
            storage: 1Gi
