# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_MARIADB_PASSWORD: ENC[AES256_GCM,data:+f4vfXaZgAbJqs0U2M+HLsqQ1Q==,iv:HWRLQAwV1Iz7qxOCfsNzGRuHspu5NBpitKHsDweHjZw=,tag:/6Lf7etrFYwAAYd9vVhLYA==,type:str]
    SECRET_MARIADB_REPLICATION_PASSWORD: ENC[AES256_GCM,data:n9c3AwnI7ZYFI0NynBW5HCM3a9L/i4FjpX6tBjg=,iv:ly8pSkHSFhRwlBi1MJTHdnK3mn/p8yCtm9IFLJj6pW0=,tag:rGNLtmQEsOmNKgLX4AAMjw==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:16CWltZjIdY9V8bhzgn0/O40pNodKEy4GfwbiLqh1O91bbA20w==,iv:UCBCv+/BHhtEZrEXJz3Zfo17T4npiMp/0VNJ5JeQWiI=,tag:6NDrI1XKjF1s0yupWD2lmA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:faJgtJlEBPp5FwIdw1okR0qvCnaokJQ=,iv:PKRUc6MyqrzF5H/8cO1osNjwPvTsQMbBgSNS/nlCWF0=,tag:X6/Xvo358hbKuK7GykjzNA==,type:str]
    SECRET_PROD_DOMAIN_MGO: ENC[AES256_GCM,data:gl2cxYp6lMxC/iCMfAib,iv:G/0mFApBGjlDzZlZXZH0IAaNVhgq+rb1L+txbqP6zCk=,tag:Khk6rpO+oNf2AfFdnjvt6w==,type:str]
    SECRET_PROD_DOMAIN_KF: ENC[AES256_GCM,data:y4auMyqDgJ60bg==,iv:c6CBSD6HzcpkzfhzQnr+TJAxB+kM2vg7KvxMDVeYqfM=,tag:n+JCMl2R8GHRMAlApJ1PNQ==,type:str]
    SECRET_PROD_DOMAIN_KFD: ENC[AES256_GCM,data:hxWdiZdsX/nv6DFAhpc=,iv:BPMe2bMTwXlYmKTVLBEQwZcKVPrE9MrKtDwXzu1N0KQ=,tag:ApvxHPp6sjcREoI0K9fdyw==,type:str]
    SECRET_DEV_DOMAIN: ENC[AES256_GCM,data:DkWP0LqOL3U=,iv:RE7JpfNHlSZa2bYA/OetZY0i1wFNIwBdClp1lUMV4o4=,tag:k+sof9SE4+f1WoClSLs9ZQ==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:9xicvu3mMlbDEgU=,iv:Z/SRtHkjaVSjG/555Krgk5dXvevpl94vUHBdUONzd2E=,tag:wCoq3exCqLBTBKxw3ZaJwQ==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:9/6RPHeZ5KIK/t0=,iv:iu5QM9XXPyHpv037M+xrQA8J786azd2b6LMdDo3nx5I=,tag:YucYG+GD9InrpYGcSvJ20Q==,type:str]
    SECRET_LDAP_PASSWORD_AUTHELIAUSER: ENC[AES256_GCM,data:cVrif/NIf/ktlEkZn2Y=,iv:yzXnrax+L9WbhqW1NaoQLZjOLNfvJxcLDmTptMMkdb4=,tag:jNGZBSXAeuqnh1dTmKAH1A==,type:str]
    #ENC[AES256_GCM,data:adNvhSaxyAmfoElap3UBIqBt5C+SxRDp4Vyw1nyS/NJ8HWEVnuauoFwI2BDQoybxwZt/+kZDtagl70aocw==,iv:3f1yQ6dRsuyCBezUbWMMaK5Uvjvs1AD+L1bLkaCYomw=,tag:QjKk7qkrJM+8X1fuyiT6hw==,type:comment]
    SECRET_TEST_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:S+bI1SeIbfLu+gYKQ6+mGUZOlO1kViVAydq/KD8O8+jKKLnxElO+pmQLW0oRu9TSr7V7mrb5uf34qPkiDBgk/w==,iv:QRA93TiQABw2i5pkwDLE5YSOMSyZOcvriCAJdtPGuqg=,tag:XJOd3764Iu/ClzX4Bioosg==,type:str]
    SECRET_BOOKSTACK_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:jVWcu7pIFIJDsCJUK2YqUJOZ2tR8j2Yoj3/f3gksKeuCgnx0ir8vA34+W2Gv538QZtu2apok8PIWD3ecwX3gdg==,iv:wBFbdjBgXlAYSyZb+LbibgUZitv0RVgWTJLiBPgxo1s=,tag:VO59vTvHVH2yucsJ45rvSQ==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Vs4d7wMV8DjBnWztHlXWhiiRxTECWlIaHaRGHnoOPETH9ENPhgga6d58wEvIjWBAG5lR/ZHMROFsKUQNhVQC5Q==,iv:z3IiBChVynuwbANhi3S3wKgnSl7Fyvdqk6lIJze7quk=,tag:qseD5Z7t+YGAYIT+tlfu/Q==,type:str]
    SECRET_VAULTWARDEN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:s+HtHXfUBT6TBlVfFLABdURUOqpqZU23CP7EpVm4OMq0U7KYbSVGCEVVOvLbLNWiXxkGdI44hlOtMrB+Zfmmrw==,iv:Jr5EQuN+lBqfL7pWbXL655mfVSYn6pUFsuXNxL9JQX4=,tag:qcYElEjzJehfyzimV8Sbsg==,type:str]
    SECRET_MINIO_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:sn0Knrgj78H8BJBme1bgIyCTm210glfv3ceg4srryQYKkohTkVvyIpnl1RpvJH2BfhbkI3iRXV8oG2aFlz+Btg==,iv:2D2EvSTL1sM2JphRLKSzBaNVFBheqnKs61+RdjGclpo=,tag:dwqWMR9XQz0bsSwr/A44zQ==,type:str]
    SECRET_LDAP_ROOT_PASSWORD: ENC[AES256_GCM,data:yLRdzu1cCTY9,iv:WDaWDoMeCjFWF5+uadhtf49VdXxLi69YQVGbOGcWOxw=,tag:8ERaXXbZ+2KOr1jqSV2Vxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnK0ZGQ094OHVZdUZVTXdW
            cHg2VnlWWUhjQnpXQjZkNy9PRFdXQXhRYWdvCm5yK2V4T1B4NjVxVzlSRWJtaVRu
            K25UVUdvOUloRXlud1ViallSZHVBQzQKLS0tIFo3MkhpUGIrS2ZHUTNPdWlGQkFj
            ZzJ0N2M5UVkvNEIzNnRrdk5WOFZJUXMKoU8p9RFlxxQSJ6KP3/x0LZcI5LPmWS97
            L3B0AXGCioe04uFZR7ZadPZrD0n3uBD01ufnlOHkKC0Sqse9L4KdVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-12T18:10:58Z"
    mac: ENC[AES256_GCM,data:10m1K8PK1eXZkNSJ/Hl+FgRoI/GInR2qYcGlwRF7fAaegg04SO3SZLiWp4BGMcMYc0uoaxvAXPJoxHe/Z2bG3ewC6rAm8OAOPXfJvMihcf0yT9qnXLT7wcgI2CFBkI2T7bBij0XfJU1MuAIVwfPvfIccf7tlWCGxldNMRK1HE6I=,iv:yDWXQUC8kKIeg3bGefJQ7xGIgANIQ1M7mICJjGvYQqk=,tag:AlSoq5XZPiAhhLvTJwG1UA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
