# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_MARIADB_PASSWORD: ENC[AES256_GCM,data:t6j7x7prfEwrpt69AVr0wUl4lA==,iv:jqZfHg+ELLTamBaqH54I2ahYD6XZoH1kNKj6v7VQhvI=,tag:GbG6DdT0r9cgvrR0HVpLzw==,type:str]
    SECRET_MARIADB_REPLICATION_PASSWORD: ENC[AES256_GCM,data:XrDDLFjpMy9EzrMr82Ju+JvhZTgjHxWjilSF83c=,iv:mmpW4m7tYeeRTBYk/S99p0maiB/OqLgycx0q87UCwN4=,tag:9ATmiUdtsYtxcJXzD/eTLA==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:bUwluvUnT2dALG0P/vCtRvOdDMiCgdrNkEwealWDnfHcIb2rBg==,iv:EkTCAPDi27blVItSikdaW9O22l8tQEIc/ZvdUNjpeiU=,tag:Ywogh2czDLwQeid5cfM78Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Ab9E4FDmuL2qkq3NY8i4wcZsaEczlXY=,iv:BTsl6yX7Un+0P0BpfOB81jmRfpHAlauJ1gIzi2r/YHU=,tag:KSYfrWTVKhiQB7bdxLlLrw==,type:str]
    SECRET_PROD_DOMAIN_MGO: ENC[AES256_GCM,data:D/P5zLqLbPcziWnongth,iv:mmjnWAWiLwKqJxsVm+ZxzRt8rrtv8ePfO4/Ar9JTqNw=,tag:mr2x4IbjrYuwT6pBMhd9zw==,type:str]
    SECRET_PROD_DOMAIN_KF: ENC[AES256_GCM,data:lz3y08bsQEsANg==,iv:jFLZYqd84Ffc/CoSG9GKOBTNlgiut8beeneZFQzjcQ4=,tag:GFqY9SgseILFfZogsk8cAA==,type:str]
    SECRET_PROD_DOMAIN_KFD: ENC[AES256_GCM,data:Gwf5eRUIwqTfgl5oiDM=,iv:WSKDykSpKluL4nqxk3aduY772ZaPLcuUoCAL2RHxJ/o=,tag:MqHHKLFA9Wy1Y8BmvP6Mow==,type:str]
    SECRET_DEV_DOMAIN: ENC[AES256_GCM,data:Kcae3vFy90c=,iv:mbI+nYGyKxrDZGHfQTzpOLeS+NFwnyRxymfGv1ws1uk=,tag:JY/bvNTnSmkc/RomCLKNOw==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:+UFJ6R3evJA/q/g=,iv:Of+7xcsqj9PU86kLmDoN6gTSnNu9V9lnbNPgshgVk7o=,tag:JokmcKRhfxEnKQ4dAYwLVg==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:0EJEF8NKo+qgs/s=,iv:s4vaH3j+p/gKsIemn0C5eMAVAjwwN/4Vq5TEtJIPVmM=,tag:ni/VV4SX5cuVPTGvCpF5tQ==,type:str]
    SECRET_LDAP_PASSWORD_AUTHELIAUSER: ENC[AES256_GCM,data:as0FiqmdcGAee7DdYS8=,iv:EjuP18i/f1F8ez7UuhS2lE0jpF8HI+4z5MmCjrk6XSU=,tag:don6Ah81YYK1R9doKHx9+Q==,type:str]
    #ENC[AES256_GCM,data:cI7+FodAj4cCtpgmuCAh9as+9NPVLQiMZ29rHevHW5bI7tyFDY1NmSbaCu3cYjxopczb2jzz57Ywk6hUGA==,iv:J0tBd7YcuxY/kroV8vW+bBEbUXRGw9TrxRmL16u4HF0=,tag:alPfvjLpUYFoZ/95PnNllQ==,type:comment]
    SECRET_TEST_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:5FjJOo4w9UwB//faDmxtAufLrBdxI2khcmGKlKkI7/z+/09uKxwW7+I/wolOQJWQdtdPCeuqZ/bt/Vs/zADktQ==,iv:wtVaHkBGtwhh62/lTGRoafWJ+wPF8thEIuaOefX2KUk=,tag:rJwRQKxsvNSVvv2vdUfV6A==,type:str]
    SECRET_BOOKSTACK_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:FQpcns7uTjSv5S78XnwTj8xWlVgv2AedSm2wzSAzSdfS79Sa8imZMepfSgjmXZtYvbnFM3s1yqVrMjYSnb3rPw==,iv:V9pyQLs5VhdCl7Gc9xEJpmrn4M5/o5JCDbB6GiMRNrg=,tag:idjUAfrby9p4eIbq8ZKjMw==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:udPqjb1Wbna49YSIYG0S47oKqhg3rqIAGbpgNoirw7yX+mVRw3VbfOhLiEInZ2lrGgNgcoGYkAVKI7LJiKYu/Q==,iv:evcWv/qEfYdIE5MRWOHFDptTMOQAWhWca5eyf0ToEXU=,tag:VM1wU1as0eeSDwy8wwVSmQ==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:NDKwCowoGZK80Biv+yBpApoQW4hy3CgqWrmz8ZL76CjaDfndjDxC0iVUkJcZPKR3sfAglZ+Vos9wLgKiuNx1gA==,iv:yr44DHPPRQHyKPBS+zC153qwAS5qeIf6nI7xv6V9xyM=,tag:BQtnTaOLwnw4T3e0gWVeLw==,type:str]
    SECRET_VAULTWARDEN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:kT0kDyvYPbQJVFmPQz+b+MKEGEwZNV0OdkPh974C7vY21U9uTTL5RHi/iquAGKHY0+/aKw80SNG7C27HJgGLsg==,iv:VcgZ9cxGumsp6mLplk8V2lg4CqH9C1x4yJzkXC2cpRc=,tag:dMMQjIB24VzODYOD0ycT2A==,type:str]
    SECRET_MINIO_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:uJ096ncjhqsVgOSfybI2E74jK/imsdUWVsPKFuXYbAx8Vtw7ZdMcE7ZATSHRu2WG4khYTtR+IkdsB1r7Mp6HqA==,iv:Fo46Y78PAvNiQixnxI0qdjbBUyF/7cYQai2lhC4vkcA=,tag:CIk/jJt10xf5E0XzyHREfA==,type:str]
    SECRET_LDAP_ROOT_PASSWORD: ENC[AES256_GCM,data:WqKzjrdZMH4u,iv:qyMvBzKnw00sx8rZxPyJ9Ncbf85fK4DcDSIDiDv01/g=,tag:xPACZkBENhZfnXZNcBqJ5g==,type:str]
    SECRET_SMTP_HOST: ENC[AES256_GCM,data:nt2fFcYO0qokS1gS8w4=,iv:NZA+5hfGT/+mXB3Kc1L+EKJ9Vo9bYs5pQ1A5CipOGhE=,tag:9QeHdpqywN3HxvPCsI2TCQ==,type:str]
    SECRET_SMTP_FROM_NAME: ENC[AES256_GCM,data:npv4ibJWe75m/pcMBA==,iv:zf+LUjpbLWfZaK7gidcdxbbuc76QWeDKmOXYni+w/C4=,tag:ZuJwq+NMyg6s8FqDnv1akA==,type:str]
    SECRET_SMTP_FROM_ADDR: ENC[AES256_GCM,data:ykl6buxQmLqWCUhy9/iBC05uyG2K,iv:+T4u9KHmGUPDWO0UxsulBtN6anp5RwgV2HFuZqwDwH8=,tag:E6VdsLYf3xjQT5B/OBK/xg==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:TGcQO/7RAA2PmUlzqRfI55PlXUW3,iv:3rLW2QxQsLu+IW8olb+OveKuUxH1fEuCvI7wb6a/EME=,tag:EkSo8yiHAZKMc8En9Wdqrw==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:BCu4KJC1OWNF4jEDlIWCzA==,iv:xoOwAUzm17okoiQTw/UjOZwmmFjhUlWD38rGtSSkL7Q=,tag:wCybbQGPuOjtp772CCkOoA==,type:str]
    SECRET_SMTP_SECURITY: ENC[AES256_GCM,data:Sf3NT8vijag=,iv:vGnQNN3QGXPC3CCEBJLkNzXjRt0YD3Gv/WWPe01NntM=,tag:Vk1tnYDiLrp9mDmnyd84Fw==,type:str]
    SECRET_SMTP_PORT: ENC[AES256_GCM,data:Iu77,iv:6oZUCRiosyUrdCjy2Ef4H1IBYRDyj1fhRIAh5GfFUMw=,tag:t9xPWJR45sEkPwazymzy8g==,type:str]
    SECRET_YUBICO_CLIENT_ID: ENC[AES256_GCM,data:NrfglVY=,iv:3o6TCiYYtVM1j4N1HfiI+mdO85QyS+XXaTyRO6vf8CQ=,tag:l9cCl2/nH9GE9oEU76sDNw==,type:str]
    SECRET_YUBICO_KEY: ENC[AES256_GCM,data:XYZuAgp9zgiaEYGt5JD8FBg+3ADSN12vKi+JIA==,iv:eTBwm1Y8bX6nZWA7PjpG8L+T3RtflwQRHE9vP+sIkQs=,tag:LMMaFyHkT0pKknZXVUYYyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YlM1Z2wxNmRXYnFEU0hX
            WXNwZE10NlcveDZNanpaR3UxSGg1OHZmUzJVCnMwRTNOaDhnTWVHU0taendkWlZy
            anVoV3Z1WUZTWkp2Z1lKZEdpV29sWU0KLS0tIFptaU12eHF5NFdtZ2cxVDhsSFVY
            ZE5Bak1KeS9SVzh4U0NFYllVRGRJbDAKul+3pvbN/fDg1KpFfBPtx8otvjNnH0Gj
            B9+OxYStRYBzj6iBjQ53dfPi9EtBkbR5NCbrFaBxSzOinqzsIMDIdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-02T01:45:48Z"
    mac: ENC[AES256_GCM,data:Sd2MbO7Q3S/tvYg+65r2x7C2/q4zU8ir9YSTGYoFGhIwxdKIVn0mYcfzWxhAGu4pVl7eKqzCPIo+cd3yjRIijHZYalmLK350/cJXNFsg8XkDeI1My7fK4pujFEc5ix7ReL/gDiCE8Oy8rOOt3CqopFMpvz18Zeoc1Y1M8FU6K8c=,iv:kYWpVGYGPjh9drYIJnfgI/yPXxPV5LeR6cl/hMC0NUs=,tag:QKBiUl9Pl3vY5Bv+CIegAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
