# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_MARIADB_PASSWORD: ENC[AES256_GCM,data:Y8yigINauI4E4fP+QjH9EI5QBg==,iv:jp27oWlxQSolXVH4A+ZyLcjRPeU50osrsaHm6PfzR6w=,tag:VXDuJjg89X7dp8AUqtyn4g==,type:str]
    SECRET_MARIADB_REPLICATION_PASSWORD: ENC[AES256_GCM,data:1p9iMjQcazm14anXUOhY5eWzPSpzKSVmL+22RbM=,iv:Nbg5pXcOn65A7Toh5mEPXyp3O7ywosD6rdXh6sZOgbc=,tag:+dOGxwcrhPasr6r/6QEKNg==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:4kgt/KleLHYbfNhP1433988J0fMPvg1uvVC+Gg==,iv:GJ2wEo29fkqkoI6HkcoMi9cE7Dldom67lI9jkoQ5Uj4=,tag:Bc+LX1iyD8mpnT2rM1DrUg==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:M+r0Saygv55MqwGHm6lCCtEDxyHrNiOLlZR4KX5aoexCTYMRmA==,iv:XD4MNTxzErH925Myx8QD8ZyiNA/GkC88j+jxyRsXQpY=,tag:Rjv0RAlHNfhgU968Twio5A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:F2soggazpLrvJZLLWm7T6++vbGE38zI=,iv:tRDqmFvk/mskDiG0hqp1HKRMK3h7D3bnJWvyeQ6fPfc=,tag:0fx1TiUPuz8CKdLfpGtQpg==,type:str]
    SECRET_PROD_DOMAIN_MGO: ENC[AES256_GCM,data:euXZ8yrxcjct3V0Slzu4,iv:n8RTiSnN76FzH9vwE5KOsw39p55cP4Mnj058skYhqt8=,tag:Vses0KaDzMXOOgfDK6/0DA==,type:str]
    SECRET_PROD_DOMAIN_KF: ENC[AES256_GCM,data:mn6KPlcgwaLvng==,iv:a1kdzqa+gSDtxeNDVqDfXRnYtEGC5fZj32bN93m8u4U=,tag:vDbCEEh8HSCnyPYBQhS16w==,type:str]
    SECRET_PROD_DOMAIN_KFD: ENC[AES256_GCM,data:tl/r3z8Nd+bF/e9aCo0=,iv:Oveld2L3qX308BoJBTat1gn2RYZlgskorka58R9hkJo=,tag:jxNqaztBj2fJuulUoa3/uA==,type:str]
    SECRET_DEV_DOMAIN: ENC[AES256_GCM,data:WB1+tnLCNuk=,iv:x6hBnPPBwMdsJisZJUHi5cjZKUTf6nxu3EUknk243n4=,tag:BE7J4Lm6uD+8JLdlZzreZQ==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:yT5bjvxqgFej/Sw=,iv:tcFDTe3Xgp/w9HPbLzEjOQQ6VO9s0EhGUgE8wmED2mo=,tag:0xxQbV9kfpgoanyT5VARUA==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:60xQgm46165R5og=,iv:LVc1GPuepXbOgNU0+IKkM/RSG9r7KFB79KcvkDXoMx4=,tag:7rhTKJ35wrk16PHGuS1uCg==,type:str]
    SECRET_LDAP_PASSWORD_AUTHELIAUSER: ENC[AES256_GCM,data:EWQuLCA2R/VXmHzpY7s=,iv:0lkwJCkO6+GBmSmJdWNNFukp5It+xDCMEY8/EjtfW+s=,tag:Nn3I/AgUc2Jj3POE9nDbBg==,type:str]
    #ENC[AES256_GCM,data:s46SS7wBkylVmyrH8Ke+o4GMBY0FoLs2Ua0k5zTWRTkx3xfWWTMRhK6l9veK0PfGc2IEDfBfHzEIpAEGqA==,iv:9ucEuB/mPGO/Ywe+FCs6IUPETwp10NhIF1f71RVL04U=,tag:IktssNdJpjqlvSMtMUoUdw==,type:comment]
    SECRET_TEST_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:8AzrxwIpWjne7ZBXibUVkJ04EdoAySfczyIk7tEcBQZb51R2y19pqe3v4T3UUGobm5YHhhjZvYtx9FVrLAqwkA==,iv:EJatCDTL8uzfOwQMccjINMFQDlEB957q31B93KHA3sw=,tag:QDNQwvQtloRX1TEvZahUNQ==,type:str]
    SECRET_BOOKSTACK_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:s5nsKNYuaN7cBfUCA+0xn8yxP6YMly7l8TGaarYXMScjVDvVN8Zq7yFJlUaQ9beJ9EqV/O0ZUSu8erBnopfNcA==,iv:7MgkC6ygMrzxk5GMt51kkbxRJMl5P7au0OWhLbMSSEw=,tag:ZO8xyDHwXHWOD/+PsHLEeA==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:lMkZyt30n5/owyc+TfVevPjt4rvBCEvNqDD6UXXUzU8npcINaze6TrmVVmHtVlMVuhYvxVkT5aZWz2ice10kVw==,iv:1pOBGDVYIn+LnyGatLu3ALrUOFJEBAPZOALzDpMGURw=,tag:KU/TPUKVLmOC2VpUnUE3pw==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:KHs2vVAQFsgngYAytfboanC07OazV6jDD/OfJ3Fn/wyjHg2n/3ANceishO3IJXl62+XyGplIDhpRQgpVJBOnuQ==,iv:baSguRfu/p3Z41y1inEwutfWSiHHbLVb2Bhfjtxo0Ck=,tag:CQPoXgMzP7Aff/IXLDWGoA==,type:str]
    SECRET_VAULTWARDEN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:vqcmmbCR/q0JF9ogX3r86SAca0sxbTJyr293NnOFgA78RkXks1I3wXsLV/xBdLLUF+99ul0GOa60K+DV2TH4hA==,iv:1EqNQ5XPyxOmT/dq6cKkTYNrnelMvMhyr6XBRuWhJwY=,tag:vU49Clj2WssGLc9xmmR7ew==,type:str]
    SECRET_MINIO_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:W52y/78H3xv+CVeLJOH1WwvoSpV85Rxu/hYAC3Iidhy0VsUKESFmLkzXU1GyC9w1fV5H0CdcLYWWxkSoWX43Gw==,iv:VMr61rM9dXvBDXS1X8IaJEFzbUkhWQIiD8/dHAPfHg0=,tag:Qj9yTwZycImxm8xGV/LNSQ==,type:str]
    SECRET_LDAP_ROOT_PASSWORD: ENC[AES256_GCM,data:PJP7wEyxtG5S,iv:A7lJCiMd3e4ZWgmdXjzzUqPBqr6gFWlNazwvdqARWeg=,tag:orw+YlLXy1/5YkozS3pYSA==,type:str]
    SECRET_SMTP_HOST: ENC[AES256_GCM,data:iSCVhymOGvf8zp0wcAg=,iv:EFoncFoSDPtZxKKXYs+QlDs8bhOdzkTF+kPKzhzLKNY=,tag:RvfT6MR7HwvfoTx0AvQkmQ==,type:str]
    SECRET_SMTP_FROM_NAME: ENC[AES256_GCM,data:qB7Mrkocm02S8pbEvw==,iv:6NawgiQscbHMtRcadrbZONDwlAgzGCONF8F8H+2eiP0=,tag:+/lc0icg0nhVHyJrwS/Rvw==,type:str]
    SECRET_SMTP_FROM_ADDR: ENC[AES256_GCM,data:jEsMKggoHjfs1r/BFChLwnB/k7n/,iv:AsMzpEUFqgcgdLI13eNZ/z4dUh7mXNCLRm0vMmovjTg=,tag:Ol4zb4L2MCxiJdUmzpF+LA==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:HlNtcjKSRqixeYtfIopTh7vSJ2yF,iv:oopzSV2o6JhnSmFdLLEmUk7bmqJ5phuqwCdHk/dLOyY=,tag:/Atzve3OVAs9enhre1WnQA==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:Yq3C5+l3shjAuVuLKePxfw==,iv:n38nksQEDPGYR6TLDnECHQfdmSyOr7um+rcatmcXuFA=,tag:OoFTVh64KYJMEzq7kDfKsw==,type:str]
    SECRET_SMTP_SECURITY: ENC[AES256_GCM,data:/4tVaXx8ecM=,iv:6CtqruFqyZth5LN4lwecDV8qH/yUMDMXdTlVzX4MJxU=,tag:Y8IiplVlw2AScgHDzL5HoQ==,type:str]
    SECRET_SMTP_PORT: ENC[AES256_GCM,data:42nN,iv:EhgcIV7VVpDisOwUBC9ZA88to265XRUs47rTZYCz4ww=,tag:ntZavlA3YnBWEKJlo5f0Dg==,type:str]
    SECRET_YUBICO_CLIENT_ID: ENC[AES256_GCM,data:KThuN5I=,iv:wptZ/zvrySIz8og73AFHVhtXou+oLhK3j3PEf9wSSIk=,tag:oKbFoTqxxWfJs4CrIYfLgw==,type:str]
    SECRET_YUBICO_KEY: ENC[AES256_GCM,data:tLyN3fGMKWOmpLgB1bCj78apBeXyCbMFJFVN1w==,iv:nLoBXhOmuorTOVRUW4cBRA/eqhvwSs6PPn6/0CeffCo=,tag:DGvYMXjh9mFxt65+9jM11A==,type:str]
    SECRET_PUSHOVER_USER_KEY: ENC[AES256_GCM,data:MjpWQsxGrNm3ecWbWFjYMU72XoW2maXCMfYt1Svt,iv:UOJ/rBNgVP8//b7W4w86rFNTRQYfhpFzROHO94c1T/w=,tag:VCvLh0H/eo9iFBOvPNkXNA==,type:str]
    SECRET_PUSHOVER_EMAIL: ENC[AES256_GCM,data:NzVla13VmjBC36zpAviln41f3adD,iv:pGdAgcXG8HVGkG/ginTe1uQ+uiy7SYLMqQ21acOG/ls=,tag:m1wmU904Ge1l6KQY+YfZpA==,type:str]
    SECRET_PUSHOVER_DEV_TOKEN: ENC[AES256_GCM,data:hEXfCQpKX1TXxQIzuRQBtM4mVS8kpGq88zcRnryN,iv:ohy5TSwvFPfNXvSkBepcy3zA9nYcDkEFjCwvVUYH/Ys=,tag:VfYcruUinlCkRMqWMjx/Lg==,type:str]
    SECRET_PUSHOVER_PROD_TOKEN: ENC[AES256_GCM,data:/haBVxQ195MHpkx/d1Zy41nTf8T9z65dsbEv5Kck,iv:hNjbLGZvU9z5xNKo8AoxzH4CnNcyAltX/274fycgi+E=,tag:XRmMaDSf/3im4tdO38b1Uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UTI2TjE2cHd4bnptbi9i
            Ky9Ubm9VV3IxTXhsTjZEOTJnc1RIcGVqZkRRCmpNeE9Oak1QdW04TXZISVJINzV0
            STBFS1crcTRQNFFyVzd0VVYzZlVJakkKLS0tIHJ5Wkk3ZHg3SDZhdnZiczU1VFRn
            WWNDbHRhMHFPR2krN0NSR2djdWFyUUkKmd2UZL1Y1zyRmCrE96nZy5+NObmgpEQr
            m4oW6gCgkeBRGBZd3voL3hhE4BkozfQyab0M45D47LyIe1w1xQattQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-09T21:58:04Z"
    mac: ENC[AES256_GCM,data:d13fF5Z3ljb+9aR2hg9l7CYLxFWRojin2DfXq+Dh9yVjKYvfg3BFnMufS2aWmbPfzKBRxidBgTUljVp43Vk2b5uNSDmcmDMRwgy7NcCym0PHPOoyjDE0jmkWIuwrw4rLRKFPQkIUFJQZLAaU2sXiuo7T48/1/PGhpre3wD/8oEA=,iv:6XdY0IhhqhnShgU60XUuUW5LIZ2z+Rqa+s5cQhJt+FM=,tag:xgVqzB2zTtMATWUK4JC5eg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
