# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_MARIADB_PASSWORD: ENC[AES256_GCM,data:F5QU7Rno8E3vVOYGJDNSBogGyA==,iv:Yv2eBPERHqBhxITRwj7/9S6s0bWKd5KzpL0M/lvfMTY=,tag:dGPVrpSAZBzqPJZSUY6pgw==,type:str]
    SECRET_MARIADB_REPLICATION_PASSWORD: ENC[AES256_GCM,data:IKtgSGZK5IsvTayl3Xb2eXiWklxiZQzuJMciLO0=,iv:dssIm33c66O4sFNrAjWTD4rDzuj5Vz6Y/Vz46vFIwes=,tag:S+/jNkSs974LHT+q85F1RQ==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:jWwuLYfffQ+MEeMA+9eoZ08zreVOyGk6zf/E/0B9BjauhlZtSg==,iv:JY+KuT3JCjQesCrLV0WLizDo9QJL5NMEQo0A7imEMLY=,tag:uWNgAn7kz5deenpL4zW8zA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:uTITNKSPa5aM4wVRIw0sdAqZ2a0UM4Y=,iv:3rXAQYKmSfuyiSOFkS3WYMmKZJryASYtYdKyxdglopg=,tag:BHW7s5rWnBKWEWBtNO/E6Q==,type:str]
    SECRET_PROD_DOMAIN_MGO: ENC[AES256_GCM,data:6XuY+K7VIKAVnVXHbLLX,iv:FhJRLh6BOG7MTRssgnSd97r5uUNZL59j6SBk14a1Cv8=,tag:iAg9n241HGQje0Suyk/zkQ==,type:str]
    SECRET_PROD_DOMAIN_KF: ENC[AES256_GCM,data:Ka9nYbILYGBMPg==,iv:NjLr3vdAUpXv8zwb2E9BhzUa9VfSUUO9FY3G+hOj7mU=,tag:A2DWgQ9uxu/EXh/GUb1ntw==,type:str]
    SECRET_PROD_DOMAIN_KFD: ENC[AES256_GCM,data:Kjg7H7ll2/fJ46Zfgyc=,iv:O+qRqjd8PX8MjqCD/tNV/WtQyXZoXY0NOIHU+E/KmCw=,tag:f2RZhDv6FhJNbldpCV16ZQ==,type:str]
    SECRET_DEV_DOMAIN: ENC[AES256_GCM,data:bF34q9fUz80=,iv:upgUMt8sc8TeGTsv5A+S/H/S1/gu0OWGtHNM0eCgR5Y=,tag:0v96dgwgWgkPGcK6teKxMw==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:9OL8qt7goRw5lMo=,iv:C9lZwXLrC/KgPzm9wXJSl1LeuVqdjndoK1twbC6/ank=,tag:1nmTfTvEohre8t5ctxM1UA==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:/PpCWzkAlR8z3q4=,iv:t/QWKCnsLXFPzGp3xrPiXskF26JQrNXGCP5/PN4m9yM=,tag:S4+97+yjED2Q1gHHB6OMWQ==,type:str]
    SECRET_LDAP_PASSWORD_AUTHELIAUSER: ENC[AES256_GCM,data:ORku4ifsF2/MGppHB5I=,iv:M26s0SHqzm6YCoyBL3VjPW4po0IEXVkMC+NACWxneSU=,tag:U9hXa9Y0xBCpx1KXs+XC0w==,type:str]
    #ENC[AES256_GCM,data:r3MGM/+MCLp7IgPnRxMwyTB+VSBQOWE9rm9flO5AyjpjBbJdG/M7Yj5hQOiozi+Dg4ciRa/5Sh0M1cqF+g==,iv:bhalLDR4xWptSqeoR14TFV0NSNu5fnsPnIUD/BSse3M=,tag:NOMiQ/f4LVC0E0P/y5PxTQ==,type:comment]
    SECRET_TEST_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:CtuUgOMtFRQ+qyoHyIq8AiBJLAASz9+WfAnS4iQ3RwV9to/rUwbkn3LGz3szdOHvqa+JJIsEcT1yk2DVb4aOsg==,iv:u6vZ0fsubGHXzq1DFetbk0cvuA7IvboZVh+kzRfypIU=,tag:qLaFD2BmnN2uZjLVaCTosg==,type:str]
    SECRET_BOOKSTACK_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:FfraD+Wxoa2125REHHMOKL+7VbYgUSiFQLodI1canW6IYyuJaMDjdCCGTPvwTBuZuiPNpoWmcPG8O7nNTiL31g==,iv:GFhuICp7fWTFE+84yF9KZzZS207LVvnr9bl4UnXWeyA=,tag:ma9yNge8nuaBOVnsPp9/0w==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:+Ho3EbRho1BDtZ7F8pmtOdR6wZNi9xMr9I1INPxOSKUk/VS968FiRPlJEPtaj4Ppriw9MuYlImEIG2mFkDD2wQ==,iv:BKY2Nm2wOEuCTr5Cy5+uj0q5VDqTDVaFiKa1nPvGbpw=,tag:7R/jSBNmEuydcUlR+AQJeA==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:7MW/UW4FhHMvY6XINJzD/FBUS026CLOShhuKbbaEDzVSRuvg3bnXAIFRZuP2xJH2TxaVISUm2PVxh5Wvms1GcA==,iv:EbNCCCwhikM+YtHYLlV0bv6P3prftgimXfZymeToZ9M=,tag:+WwvnU/Gfm7iOI+CFNrx1g==,type:str]
    SECRET_VAULTWARDEN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ChtoWB71tYyUx93cZAzaXSmZWWLPTYhxW860lHr+fAtkutzXkN6aln+UygUY32uN4cf8no37aIk/DMj92wSiMg==,iv:iBuk/soviSxy553Lwcpc9S7j5wX6inNoH+H6HSjqIek=,tag:3Nmkq63tNi2yDxbp/fraag==,type:str]
    SECRET_MINIO_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:gOtBrsBrR9SJD451GlBzu76iDCRILrxQev530ZuItg4joNturSzkbi9QKa1yiWrD36sk5uOUdst45t8MyEaZgQ==,iv:tOqQ3Zp+b6Z6+ukNi2SMi1MX2RGevjG7K8bkqy8eWF0=,tag:LGjGlP7bmB0z8iPBxWANOQ==,type:str]
    SECRET_LDAP_ROOT_PASSWORD: ENC[AES256_GCM,data:D8m7ELJ0aRGm,iv:FsUQFZiicIPhj8605TAjq46Ox7CnwIMyo+hFREqAA8c=,tag:mdt821D3j7t5U7PAhrfRmA==,type:str]
    SECRET_SMTP_HOST: ENC[AES256_GCM,data:kVg3TtgPVQZ5guqWk1Y=,iv:b5Q5HjWJtBJBHWRQ2fBFQo6Je7onPi4ovyKJmE7MoME=,tag:IqTmcOWRfq4i00xlj7zvLA==,type:str]
    SECRET_SMTP_FROM_NAME: ENC[AES256_GCM,data:yg0Qz/JP7z6nbHyDRQ==,iv:r/gtUp9rNu3tSR3M7+fQ8WW1Q+TPIYnWrge9wEM77yM=,tag:Z6Dn8vc3RuQgTVFRWyJoLQ==,type:str]
    SECRET_SMTP_FROM_ADDR: ENC[AES256_GCM,data:OHyPqHTkFGFe3bc5fm+FzSls2PVL,iv:JJFJbTH8Ns8wrThTmo+TVBsC+Q+vKbuqsUg6TSi5rOE=,tag:/Wn84Vil8xvUopkNeEUZ5w==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:OiJpzMPeRulOsl1BcVfg+EkB2o7A,iv:FVtMbBWyMjuoVy8Jv8lqjdRDXvglzuyoZocR2IkCzbo=,tag:qNUSGqncVatFdEa9nDPcSg==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:vjrTrxBxdytwXHeg1LIn/Q==,iv:Zi0jupb2r1PGMIPtTVZPXLnUVmClEHjGHt4SnDYa1KY=,tag:9rY5JRhJP7Eqp11A40+qYw==,type:str]
    SECRET_SMTP_SECURITY: ENC[AES256_GCM,data:ZCh1LOmW32Y=,iv:O2ttsHcd/dk54ReDyh1XbHZjD59aEzgRzu5Cq4FqKWo=,tag:i9x990Y+O79AKkI/ht7iAA==,type:str]
    SECRET_SMTP_PORT: ENC[AES256_GCM,data:4E9N,iv:EhxT0n0PoOhN4z4exNaL0nzI++Nf/nQPnXPL/vpoz6A=,tag:HG3SjIh+0hpCgnArXVEVWg==,type:str]
    SECRET_YUBICO_CLIENT_ID: ENC[AES256_GCM,data:qd7w678=,iv:5o71Dk518LNWpEAdFpJhSGoUaTnSFTVDjDO6vFGyZ3I=,tag:n/q8WwMPOTOOkRdQ49QJ3A==,type:str]
    SECRET_YUBICO_KEY: ENC[AES256_GCM,data:ZWtJ2febiVncKVwXNZh/qBrpxLo6UQCA8mawdA==,iv:/4Dzm4JbpuQZufMmFscTnWUjxoxVxtTdxy37eoZGqU4=,tag:mYivv3gJGDdmlOINM8uw7w==,type:str]
    SECRET_PUSHOVER_USER_KEY: ENC[AES256_GCM,data:HibWI1ZXm2B9Wxacadnydforz5kQWXYHI13umKIU,iv:rEj+TMqnBqj4uqjiYRPx/HY7QXUrOta76zFjSbYgFRg=,tag:j7MAjt2PaoNA3Ggdh86+bQ==,type:str]
    SECRET_PUSHOVER_EMAIL: ENC[AES256_GCM,data:WROCk+KuyupVUURvuRoMxDzjSuy2,iv:EXz/b+ikq7gcW0+7F8UrMap2nZRxs4rgm3BoVwrR0Hw=,tag:IvqWxctFckijnZClq+qE2g==,type:str]
    SECRET_PUSHOVER_DEV_TOKEN: ENC[AES256_GCM,data:f2KImAqSE3FPbBTCtMv9nWKoWH/TpkF1GnTY/n7C,iv:nrNRHS3kZOCaRHakajPolfQQEc13J2DAK/jWR5AJ1qo=,tag:fo8CXdbjzPRMrFposXEKiQ==,type:str]
    SECRET_PUSHOVER_PROD_TOKEN: ENC[AES256_GCM,data:bKommdi6/RNtFtFxWedeFmftkuP+zOLRcAV9pvdU,iv:NJzP3xXGGuKwK8AWudtZpO47KEzl/4sJcVqssMkGQS0=,tag:dEhARu7ETv6cDR76pPyp7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTGJHNTlDSlB3R0lKSnJH
            NHJIVUlUaE5HTnlwSTlETERZNmUyeFE5VUNjCmIwbFYvSjdUT0FhcWNKSjd0R3la
            cmpEUzgrMmgraFFlc0JjVGxuQ20vQm8KLS0tIGx2U1NxYzRzSnpOcmlSZGh6Q0to
            alF1OVBDRHNhRGpINXZRT0JJVmZhSkEKi8h1Uv6DlRnUwQt9X4A3AMlRN77yYTAd
            0HzUwCqwwrj7Vau6OLLo+HRShCgUOXkhCflrMOrV/ZmdY7tqXsCdGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-04T02:05:59Z"
    mac: ENC[AES256_GCM,data:+hze7oJBjtg0LDdVvTdgpoUeMAN0YrBbTZ5p+TmkgD2Me4k64nVajWLcgB8hR5ptEf9ycr1XpxNQELstidR7A8QbfcH3qoqkd5de+ZFkiodKvIG2tR1IbMhsJHj3NfDKsxGmgxnKX7eFuI4zt0aXJHoxkb3yMV6XpZqvRFdZA0w=,iv:KTg2q9k8rL2gNP5Ejm2nbiyiWakj7Oz0+bFZ+JUnT9U=,tag:95Ixsxl7q/P+HTfXJ7Utww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
