# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_MARIADB_PASSWORD: ENC[AES256_GCM,data:E2FAj0RLWvFtJjJqqicQSG/g/Q==,iv:AsVszX5A1bO6dFm9uvPe+Thit1XCu2JD+zv7EDivH/I=,tag:1hthAZOMSYsUbEYHz6MP1w==,type:str]
    SECRET_MARIADB_REPLICATION_PASSWORD: ENC[AES256_GCM,data:8SxGe/Qja35TjX+9ya6DlAZ7V3bpJSKKk2zVR10=,iv:/wxwFn3eI2mMRQm31rQWahVqh9CGgXOwMq69/Ndp+WA=,tag:Qw9vEU5y1818clM8KBO+JA==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:j1nb4iE32gtN6LWS7/Bt0xKmbz7pLa0GE6dBMmFqCdgIuwgt2w==,iv:oKQDVJZJlALsSGGnZ0Iga4y0E1nNI2AkWGieOTnuIME=,tag:jqzRnSp1kW1C0kSA7ieKng==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Ro0MOVkD3lZZeSRdNauuYam7CXb6JbU=,iv:KXdGLeC4SeqczCenIWtb3pObcIvPA1hC1GI3bF5fxys=,tag:rd8T+q3eW/2ueGqY46q12A==,type:str]
    SECRET_PROD_DOMAIN_MGO: ENC[AES256_GCM,data:10YCqAVelUMds7H7iBL2,iv:Is2kxhU5ymJn4yb5blK3UEbWHtpBMDXfdqgM5p4rkcU=,tag:hCSuGUspGMPEXo7ud4Zhfw==,type:str]
    SECRET_PROD_DOMAIN_KF: ENC[AES256_GCM,data:xSDa+WFtF8f9Dw==,iv:7wLP8oEaUBbyJ9aNW6Zz/EuXIgSFltUVae+KbfrQ6a0=,tag:jFHe5JARdL3o2BbRA1M3bg==,type:str]
    SECRET_PROD_DOMAIN_KFD: ENC[AES256_GCM,data:9EjaG1a+QdEQ4Cdzcpk=,iv:SOQdpYjjMciWXycej5hMDhVJe1O+Du7hBH1qc5oW0vI=,tag:JMTGxMlPCt+BeXRVOaBE2w==,type:str]
    SECRET_DEV_DOMAIN: ENC[AES256_GCM,data:5q3GgQLbU5M=,iv:RS6P/jBdrv2hk/9faM93/ou/2cAgN8fVDW6QjQqFy00=,tag:wKLCqWzyNp6KfpsopXUkHA==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:MRJn0gmVf3H89wM=,iv:R8vloMaz5IWHrvHknon1kTVr76t3z35iGFT3qKh40Qo=,tag:zWU7sYfUJjZ4QHSLNXKrdQ==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:e4+UFYxLhbQWh1U=,iv:2gq2Q2JsmYHW2Iz40/OkKPv/TlRQmgpzFpkhhqJ/9jo=,tag:FF7/fBI9saTZvF6nBR95ZQ==,type:str]
    SECRET_LDAP_PASSWORD_AUTHELIAUSER: ENC[AES256_GCM,data:PfYacNCfP6qdKZlZ9DI=,iv:Z8jpREYNemwZyikXjC4A+hHRR0nzVt8vem2qqNKK22Q=,tag:DX0J6D7y97GgLAklWNvtCw==,type:str]
    #ENC[AES256_GCM,data:tP4py6wxOcyUVRyFksXg/qQ6KeOHdUjmiNAzhJri3h+PZJYo9B30EWda2pBe7Z/xv+Z9YMwe+5SBejOcDA==,iv:oav/7EMAdPcpgomQa5Q067ndIox6qNe6JiFqgvPutoQ=,tag:0aYoqqOVxnh85GSIJEX8UA==,type:comment]
    SECRET_TEST_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:KNcMgB0YTUIuEtnMaAo6CHhiWHu5FhpUs7/pbraalL9AwIU1WxidJKz6WXwvtVK3fjtuolhHOgVPKyRR6MqGVw==,iv:lMhtP55ez86AFuF5rmPR8d8wu6uhdA8ExJK55gL4ucU=,tag:PVR6ci8svANWKpqjnNPxQA==,type:str]
    SECRET_BOOKSTACK_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Qnjz6HLiyeP5ylDc1a9zhYVXOVd8j2AzuIOrWkpF+4pAkLa8f9fC/XouzMLD4glOk18M4UQJ89+ZFrB/9KjM7g==,iv:Mh3UC0p/xH8zj+xWsdmPehYaXKdyvxyx0lV26baqMcM=,tag:nLb7mjqwcfcFeSG+fUen8Q==,type:str]
    SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:fzCnx73f2fdAN2E2vebexv65eP+jMnNCJFCsVzpjJWKEC3G7U9qgj0tKXbm9pY/g7GAj6H1NBWkQoPMSSCtW3g==,iv:KXawOZTB0gYH7L4sfjf8b+4hpvtAsinGpGmH6hQqU0Q=,tag:L9orivEY6RahJsmXk3dItw==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:H64Q/6x51bPq7KxxKG4JlZQobzL+mc6MwDXdupIZtWfnP7VPOJSRbG/4dPNQTfkOvQoYopkVctRw4tOfTo4W0w==,iv:X9N2dJVjXtvyDVh84fTnRzeMf+clBnydPUKNPbASwH8=,tag:McSlFQx/Bp3cENi2FaYi3A==,type:str]
    SECRET_VAULTWARDEN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:lUJeIVzYi73aOs8oYg0GOk7g0OLuJy3VJndupbBhjWlDpUvCnGZnGIHLsLbKo76Xmc7mcalrTmQaycnV7jjL7g==,iv:Z+Bkhm2OcW0nxeOUNwg6HJjT6mi6q3Y8oxWFbOn5zuQ=,tag:mO0XEI+LCHxj3Pp7J6d+tw==,type:str]
    SECRET_MINIO_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:T+z2NPOInUlLLYDNdiY6TwLazXnX8+5/RZ+7/zNnm+7S4L/MqNDxbUkJRTlK6kAZCgiZyXJsfbfbY5l8SNpL1A==,iv:/5uEhyiU/CzjXturTICy3QaZ2mRHDbGcz/ImvmBOxqI=,tag:w96GjMSlirdlytwWrvsR5A==,type:str]
    SECRET_LDAP_ROOT_PASSWORD: ENC[AES256_GCM,data:5M3XQgwl6RFC,iv:wJ2cSwF7ve/bHZvPA9zXwEQTDjgd11A6XbZZTWvziHA=,tag:hoJ+UooPW6cSZ+3bol/sew==,type:str]
    SECRET_SMTP_HOST: ENC[AES256_GCM,data:Jdkz2WWAbrY+XZvZ9Vk=,iv:4D2teAF5tyRkvPh8feP+nNap6sEJ5/qMfSFxA5Yd2sA=,tag:/Z14kp1vERJ+ozT9Ao1pYg==,type:str]
    SECRET_SMTP_FROM_NAME: ENC[AES256_GCM,data:rh/4d1zGYOr7gHCWtg==,iv:T92ghtviGrOd08GPxpxI19qo6J5zWXQDPcA8K1L2NLg=,tag:nBBEq6INWJvMfp2sLzdYfg==,type:str]
    SECRET_SMTP_FROM_ADDR: ENC[AES256_GCM,data:cQdPIK+D9KP6oIzE/19Ilg/AuG0k,iv:o2/WUDnxaVWvziaQwCwgUsm+32HUZ+ljn7cgabGb7h0=,tag:kjpoBHQr+MGrsOTDbjKemw==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:pzh2G4TLYozg6nKRl2xhzag2go/x,iv:YGwwId1XBz3ORaPcoBRGlz0wEpCkMPt5A5K0AFHTqtc=,tag:XT0JAYLhW3ucv3UDzkxrLw==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:PAdl4pY0368We5lU6TyfWg==,iv:wXFxBpUYXdxKDqz86efpe6K/xi7jNpSGvr/ddqvQ0L4=,tag:5pHmJNWVgQ3vaqyW62SMbQ==,type:str]
    SECRET_SMTP_SECURITY: ENC[AES256_GCM,data:DgMo4kxnzPU=,iv:u4TuWAcf9oCi38MNkK0LqAX1cRhAX8Zt3asBwXMRFJ4=,tag:7DNQALipTcV9ab+L43C2vw==,type:str]
    SECRET_SMTP_PORT: ENC[AES256_GCM,data:nWFD,iv:/YQso2JOAES6IWoUE7/VMRNY8CfXACZ2W8WBQyZ0xHs=,tag:51Fo7Hy8mEo5z/XS5vvaUg==,type:str]
    SECRET_YUBICO_CLIENT_ID: ENC[AES256_GCM,data:AR1TMq4=,iv:h6sJ0LKJXaWZG1nKUE//R/XPJuc8qSJv6cpeyyNd+Qc=,tag:imqiRxAwig6eWgoqL61E1g==,type:str]
    SECRET_YUBICO_KEY: ENC[AES256_GCM,data:JlY1y0AM/TqbCnf4mK7umO5Q/D2iCRyZyUOr2g==,iv:zqcGKLcQwzHsXKHC8s6z9EctwQ5ZzKfS61apxj9PV4w=,tag:IAh11apYq5XufXVfsGo7vQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWUlWdjRXRmpxY3dVc20v
            R3gxWm92bytDaDJRaVBhcDZ5dmZ3WDdSOFZVCm5LdEZ4OGlnWTRxb21QZDQ0Qk8x
            aGgyUGg4eXZMbkJRbWx0QmkwNEZiS1UKLS0tIFMwSGpJNW1MVFh0YUVpMTBQMTNK
            WVhRTmxzYWhKSlZtR05IQkdqTlZXZWcK8Rgc2ludFyNlhwKieTmrQubwXiD4Wg6G
            Es815L/AAvyryl7B45orQsPzEXBKjIjowHAZwgKZQcCM+3idjAORZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-21T19:43:42Z"
    mac: ENC[AES256_GCM,data:a9IEZuGR84uotq71kwLGHhWQUYFwtmTZmZkOguViHUOik7gWRWD9zH18rkypWDm/kOlQEnXrE+epsR99rrAu4PueJGWqxk3Y9rNK2kCd4kqhZITcYbuyQ5OLTf7Dfbx/e0OyOMH7rH2ko7iKQCPiAEv41W/jEMxds3apCbnVPhE=,iv:4bBv5ZTjUshGfjisO4J2PcdxCVqzWZpcTb4n5idw5Dk=,tag:j7CwepCruKORqTqHVpOrQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
