apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: unifi-config-volume
    namespace: media
    labels:
      app: unifi
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 256Mi

