---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/install
      sourceRef:
        kind: GitRepository
        name: pgo-examples-helm
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    debug: true
    singleNamespace: false
