apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:ge8a9Btqpuw=,iv:OKDMZcejLbVj11qXJJXkqFCo82M3O28kIIxvU+6QnYg=,tag:0EiJO/klQE7UfKq487gF+A==,type:str]
    password: ENC[AES256_GCM,data:8pACbnq83sYsAz/r/hC3,iv:TRoVXFiIAmfUU0wYaPCd85rubciAsKsjL7vwDzlauxE=,tag:BfHbSvwQ+8fNos+YCDvxSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQm9XalhLcFJHbi9LQ2Rm
            QjEyVU83dXg4dHdtRGR6ZVkrc3ZWbG1TaFY4CjZLVW1DSXg1WTNwZjlxS01LMmJE
            UVNxUFdZbHVKMkpmeDBXVTNZem9nTjQKLS0tIDBveE5kNDh6RVpqSFMxQmZQZmJ3
            UW9yWEt6VWkvOUtMK3lXY2tNUjZvSlUK/WBYQvUckzHW106kxAGDbrxsLH1h/prA
            ocet9vycLlTPLGizwztMb5M4CXv0iS+A2t9LaEkzl5YmVKgsOTv0DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T00:26:50Z"
    mac: ENC[AES256_GCM,data:beClsuKOcnyRPfLiCN2Z4rX6TcIyeKS1T7irWLjiEfz/1dMHNbKBFcTboR++jj1sFFn5ZBQaXD8jkjQXHUgjVYd+9jgthK0YjYJL3gHb4pyBc6B0LmBOsrSjAcF2+5tu6SHKOlfv/aPJkL/Jt8GGNdgOPep4k9wmTsckLoQaafM=,iv:g2/g+zwSFYvAZFDwLi3sM8emqmEZ/4nC8YRFigtKnw0=,tag:gIuv8tk5UAQjPMtJyvOJTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:JXu/tdgs08MtfLmFdA==,iv:Nd+DXuW9tuWISebacEQmJnnsEL5FUIyrGigvQj4ho9w=,tag:KOnuolFwMG+PsS+c4GdLhA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:hx3Odd1V8HVfbGdzcMYMRkBqjOo=,iv:oufJ4gDeM/Q0WNG2Jntvz+640nAf60vaJS9aNutHecU=,tag:NY1oTi1XHW5TD0iqaHbBeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQm9XalhLcFJHbi9LQ2Rm
            QjEyVU83dXg4dHdtRGR6ZVkrc3ZWbG1TaFY4CjZLVW1DSXg1WTNwZjlxS01LMmJE
            UVNxUFdZbHVKMkpmeDBXVTNZem9nTjQKLS0tIDBveE5kNDh6RVpqSFMxQmZQZmJ3
            UW9yWEt6VWkvOUtMK3lXY2tNUjZvSlUK/WBYQvUckzHW106kxAGDbrxsLH1h/prA
            ocet9vycLlTPLGizwztMb5M4CXv0iS+A2t9LaEkzl5YmVKgsOTv0DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T00:26:50Z"
    mac: ENC[AES256_GCM,data:beClsuKOcnyRPfLiCN2Z4rX6TcIyeKS1T7irWLjiEfz/1dMHNbKBFcTboR++jj1sFFn5ZBQaXD8jkjQXHUgjVYd+9jgthK0YjYJL3gHb4pyBc6B0LmBOsrSjAcF2+5tu6SHKOlfv/aPJkL/Jt8GGNdgOPep4k9wmTsckLoQaafM=,iv:g2/g+zwSFYvAZFDwLi3sM8emqmEZ/4nC8YRFigtKnw0=,tag:gIuv8tk5UAQjPMtJyvOJTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
