apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:X+SsPHarJmyrclwH5ABXiQ==,iv:/uhO2O5h99UZdUguDHk0JHX7snSXNkQ2zh9rHlpH9Sg=,tag:Ct9S6D6SI7zUXtiPzq6KvA==,type:str]
    password: ENC[AES256_GCM,data:TSUvZ/ap4SlLakn9BLYM,iv:GhYGqXKiANJZ8/29ZB6EY4tfYKvhPjcNc9+xR3KjK/U=,tag:0aeIX9IYRqhKF6Awk+Vxhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTXpNZmJFbEphT0RGam1x
            WUpJcWhGdlRveCsycVhuREpuNW9SbnYreFVZCndDaVovM2JKWE9McTFWU05LSE15
            em5PdUZPcE5CRGNmbjdxdFNRWXVBMGsKLS0tIFlra1FZZkZoS0M5eUM4TWY2bzdT
            czY1VXBiODhYaUI5K3d5dkZpU240ZTQKQG5rvETHjxac5RUu2dumCL07S39nAk01
            zDUYupJ9mAi8uqdFStO8cwyVYPGKeN7UZtrUQgLiE/bp6yIEUCehdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T23:41:10Z"
    mac: ENC[AES256_GCM,data:QFsTzMDmVVlCJuLKa7RbYTArQwVOKuTMgWRGcOOv67sGXmyFMlGjijjJGdR2dkITznka7iChq+XzfsnShDDNNgWI5RBHQyZl0z1FuSw8hPsQd269Hza8iPqTmzC3JNyjcmNvJjMIw4c/FirD+ILE/MI5/Zp7qLNwLNf1nCax/es=,iv:L8jHgWPnE9NPOaxwEPROGDro1SjyFI01Nc0uV3dNPEY=,tag:v8UA8uUSDs3nANrigAs21g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:JZD16/bi2i5O819WHg==,iv:4uEbzY21JNwxIZ4qaRW0UIL5CnjCOJjizoqE7+7Yr6M=,tag:ZXnLxjGQig6aDn3Qz9/C1A==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:8CvX2RG2tvhFNJJq6PsAurRg0Gk=,iv:N9IHX5lpjiuoSD32s/vuP/8NstCFQ6p7OVrtpKeL3cU=,tag:qq2aGequHV5t0HQTDVQTdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTXpNZmJFbEphT0RGam1x
            WUpJcWhGdlRveCsycVhuREpuNW9SbnYreFVZCndDaVovM2JKWE9McTFWU05LSE15
            em5PdUZPcE5CRGNmbjdxdFNRWXVBMGsKLS0tIFlra1FZZkZoS0M5eUM4TWY2bzdT
            czY1VXBiODhYaUI5K3d5dkZpU240ZTQKQG5rvETHjxac5RUu2dumCL07S39nAk01
            zDUYupJ9mAi8uqdFStO8cwyVYPGKeN7UZtrUQgLiE/bp6yIEUCehdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T23:41:10Z"
    mac: ENC[AES256_GCM,data:QFsTzMDmVVlCJuLKa7RbYTArQwVOKuTMgWRGcOOv67sGXmyFMlGjijjJGdR2dkITznka7iChq+XzfsnShDDNNgWI5RBHQyZl0z1FuSw8hPsQd269Hza8iPqTmzC3JNyjcmNvJjMIw4c/FirD+ILE/MI5/Zp7qLNwLNf1nCax/es=,iv:L8jHgWPnE9NPOaxwEPROGDro1SjyFI01Nc0uV3dNPEY=,tag:v8UA8uUSDs3nANrigAs21g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
