apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:/VHF8MEPDPM=,iv:Qq8p/T1ahLkbPMkA+QtM44nSaJKFT4oDLK6d9+4ZRqs=,tag:uXiRCbpo9QUw/amyaErwkQ==,type:str]
    password: ENC[AES256_GCM,data:lOUAmqUSR+0+iIiHXho4,iv:Vw/5ezsu/cAbs2PiuGhaff1AZbmvs8Oase/s7D4vfYY=,tag:zTsJep+v2jOEY2Iftkct7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbzEzUjdPRXZXWmpXVGs3
            dm9aV2NWTmEvdFdCcGd2dTkxV0RqbHFKWEV3CnpKWXFMN1BOcHpsWWwzMFNBMEtz
            SXYzRkh5Y2pZR3ZhWEZuK0VETkdZYlkKLS0tIHBlVS9neEV1LzJRKzd5d3J6cElB
            M2Vja1F6cnJxaEwwVlhtTktHZ0lkNWMKHOBW3MKshgjKFpiJRisr/fHR1M3lVacz
            DUE2fmR3T1uUx4uCI6bNq1NsZIh0Hm4ihtrWLveDiOkatN3UeP6hJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-03T03:19:53Z"
    mac: ENC[AES256_GCM,data:zdsNpj9dFXF3U+4l12SmRUZP3X5z5Op+4CF6Oj34aChJfqO/st8ZOzajbZPTYyJVkpwIrwuhOmYaE3fMg892wjT9VwvD5xc6ai9rHivWjc/e1DoSaZQnaW+jao+vQoDe2zpcjPYB9UvTjAskHXxf42JIKOKFCbUgtMsjhm9g4kI=,iv:XgwaVc6vLsms27m08hRmO1NQNY8I8EoFVwGJrVh/qtQ=,tag:su9SQIr6LwrtpWqVSXh/xQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:vBFuVSxGeik3bTiKbQ==,iv:VQtB7pZkvnEdYKpWyHSOtAuI2dxDI0SZDYBfRKJ4h08=,tag:LoPGJ3JMmFONscsuDN5rhA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:m480WcguWlj7v2eSFYMNbDzO1ik=,iv:hI+q3X4CrCfvwVSPLp2VQ68HZhORUSpmmpP5sptpItY=,tag:f5r6tjCeLZ6lwIXuK8wLuA==,type:str]
    MINIO_REGION: ENC[AES256_GCM,data:azgJjf4=,iv:lkbcgvtjhx0CEe5C9z4MDgrQ81XUaIGZWZqRM6HnvWs=,tag:9As6C0YsOoLppt826E/AzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbzEzUjdPRXZXWmpXVGs3
            dm9aV2NWTmEvdFdCcGd2dTkxV0RqbHFKWEV3CnpKWXFMN1BOcHpsWWwzMFNBMEtz
            SXYzRkh5Y2pZR3ZhWEZuK0VETkdZYlkKLS0tIHBlVS9neEV1LzJRKzd5d3J6cElB
            M2Vja1F6cnJxaEwwVlhtTktHZ0lkNWMKHOBW3MKshgjKFpiJRisr/fHR1M3lVacz
            DUE2fmR3T1uUx4uCI6bNq1NsZIh0Hm4ihtrWLveDiOkatN3UeP6hJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-03T03:19:53Z"
    mac: ENC[AES256_GCM,data:zdsNpj9dFXF3U+4l12SmRUZP3X5z5Op+4CF6Oj34aChJfqO/st8ZOzajbZPTYyJVkpwIrwuhOmYaE3fMg892wjT9VwvD5xc6ai9rHivWjc/e1DoSaZQnaW+jao+vQoDe2zpcjPYB9UvTjAskHXxf42JIKOKFCbUgtMsjhm9g4kI=,iv:XgwaVc6vLsms27m08hRmO1NQNY8I8EoFVwGJrVh/qtQ=,tag:su9SQIr6LwrtpWqVSXh/xQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
