apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    password: ENC[AES256_GCM,data:0idMv5Mm5GGCRjsPzF1u,iv:IsXttnY0Cc290lmtEW3JjiVDFSZNrdVFFWdOznq6um8=,tag:foErTH4St7nstwEUtrk9pA==,type:str]
    username: ENC[AES256_GCM,data:3YbbDnQiP9pC9jglQrCDXQ==,iv:scuJqz3HmUvvn1meKM77VaThe9KiR8pO/+XshB+oj2s=,tag:8AlTu3Yj0bHCp/U8k3i+1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxa3p4UFgrR0hYeEhlV2JS
            Y2lGZ0ZWVEVneERSM2h3b1Q4TCswb0RlTnhzCjdBUUxRSWZSNnpLS0JNeE9vc0lh
            VXdyRkJZQzd0dkE2RDZaV0JjTzhGazQKLS0tIGw1RzBVOGQ2aDE1anAzNjFKT0N2
            UnZFNkZoSFZudXpwTTEzT0MxbXNaWDQKH+x6qsiKXHM43eedfv+5J+Ry89VPQBoV
            Tdsv1kL0ymWtlIeqhr59uGHMvIFoQwwDc7+Qg+YcKlskATOgaJaBPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T22:46:49Z"
    mac: ENC[AES256_GCM,data:fJYUWi3xjkxCaxGjSKGa3ysbIDiG/VQ/hmgGT6niyJKk4/kaKbYZebhdrETU38X5f69Xl31wk4l+Kz66KbSBLDm4+TNS7sGnD9d37GzPF7V8vL/2mvjb9IUf0vsFbhAMfSu3YgrjS9YLz4do8UvxhrSfEUzgVD2K6+T8c3FuN4k=,iv:iyRotlMXTxaDjv+onZsKregv5sCCLrayIMyVMknG+84=,tag:xH3tm7sGCjwk0dhiFCS31g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:5CLUDjwe4jmGQu3Yow==,iv:dV2fU7uln1TdvlvPcVxWS2h+cBErCqZ50PJ3yLMAeNM=,tag:lmSB5nz+RfCNO0MuduKwIw==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:hm5QOkqhuPhCucnyT6ORQ3jQb+k=,iv:RSZpQkMM2IxHq/d82jS9+zMeZfvjigEDYluPEwcPTCU=,tag:UfS2ICPDElxkorkU1ydwRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxa3p4UFgrR0hYeEhlV2JS
            Y2lGZ0ZWVEVneERSM2h3b1Q4TCswb0RlTnhzCjdBUUxRSWZSNnpLS0JNeE9vc0lh
            VXdyRkJZQzd0dkE2RDZaV0JjTzhGazQKLS0tIGw1RzBVOGQ2aDE1anAzNjFKT0N2
            UnZFNkZoSFZudXpwTTEzT0MxbXNaWDQKH+x6qsiKXHM43eedfv+5J+Ry89VPQBoV
            Tdsv1kL0ymWtlIeqhr59uGHMvIFoQwwDc7+Qg+YcKlskATOgaJaBPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T22:46:49Z"
    mac: ENC[AES256_GCM,data:fJYUWi3xjkxCaxGjSKGa3ysbIDiG/VQ/hmgGT6niyJKk4/kaKbYZebhdrETU38X5f69Xl31wk4l+Kz66KbSBLDm4+TNS7sGnD9d37GzPF7V8vL/2mvjb9IUf0vsFbhAMfSu3YgrjS9YLz4do8UvxhrSfEUzgVD2K6+T8c3FuN4k=,iv:iyRotlMXTxaDjv+onZsKregv5sCCLrayIMyVMknG+84=,tag:xH3tm7sGCjwk0dhiFCS31g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
