apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:ek7uwAv7n9Q=,iv:nK7s1Er1KjZBT1/OGUuAoVp5EL92IEfTQR+0TY5xPy4=,tag:j73mwMY4dAwdAR+JQHWUqw==,type:str]
    password: ENC[AES256_GCM,data:1bYJklp1rMpSsTFZV5jf,iv:lNeGMae5RRzDUPlOM22DeXhRrJp/S+BZvT24yu2dMuM=,tag:cTfZbKlGx8blrXASKlw3Mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWnZxY2xRR1JHWTJsbUFW
            bk1ocDZyNmN4MXM0ZENTajJ5b3hNdlBUdkFZCklickpGUkVqcWNLVGZsRGxLMHFi
            cGg4RVJxVUM5dGtUV1N0WUZtYUFCbncKLS0tIDc5S3VkK3p2M2VaSjdlT1ZCQTlU
            ZERzVUFHY05HNDVYc3o1K1NXZzg5UmMKB93ysLY/9I8ZRZuyvTuIy0ev1vUHWt4a
            Paw420iR/D0rh9P8gU05nBSTTKq1HS5whRarBRObtbG/shvusmUOfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-02T18:44:56Z"
    mac: ENC[AES256_GCM,data:Iyw/Ep6poK4YjoiB65F+NPdrxApNEDgOgxp68MieWf5D4b3CeMskUB+pNSg5a4O8CNbE+3l5/XdTHEu+c8jM57bK2HIUigPdOLxH3SkUd1ZSYiy4BA8QeV9gcgSARjKhNPwQFwJrKnSqd6RPXPOdUrKFA9tMtEc2iW23z2k/NDg=,iv:ixFiz6w3W5rsxYTyUBgEnufAzS/3fPCQSeVjK0bVHSU=,tag:e/zrOtyH0ScCb0nYApjP/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:/CeMDq3L8U7ICzhBDQ==,iv:ZVJxDvs+3oioRzIWKU/O+mbrrVAKCesAzOdHGDiV3Qk=,tag:jJ8+lUeAn+jvz4rHZZR86Q==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:8KLqBrOVUy/w4IiYRrdUZXyXR9k=,iv:2VdQvX1id6aDaENgYP1/R8ic4EdXMPlOPvhAh7c1IuA=,tag:LepIyz8+kCfPh9U6HJYLVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWnZxY2xRR1JHWTJsbUFW
            bk1ocDZyNmN4MXM0ZENTajJ5b3hNdlBUdkFZCklickpGUkVqcWNLVGZsRGxLMHFi
            cGg4RVJxVUM5dGtUV1N0WUZtYUFCbncKLS0tIDc5S3VkK3p2M2VaSjdlT1ZCQTlU
            ZERzVUFHY05HNDVYc3o1K1NXZzg5UmMKB93ysLY/9I8ZRZuyvTuIy0ev1vUHWt4a
            Paw420iR/D0rh9P8gU05nBSTTKq1HS5whRarBRObtbG/shvusmUOfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-02T18:44:56Z"
    mac: ENC[AES256_GCM,data:Iyw/Ep6poK4YjoiB65F+NPdrxApNEDgOgxp68MieWf5D4b3CeMskUB+pNSg5a4O8CNbE+3l5/XdTHEu+c8jM57bK2HIUigPdOLxH3SkUd1ZSYiy4BA8QeV9gcgSARjKhNPwQFwJrKnSqd6RPXPOdUrKFA9tMtEc2iW23z2k/NDg=,iv:ixFiz6w3W5rsxYTyUBgEnufAzS/3fPCQSeVjK0bVHSU=,tag:e/zrOtyH0ScCb0nYApjP/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
