apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:FKTol1YHx1oY5JZRnR3zUA==,iv:y3HKEmH9SrQmw2hRA8Dq0Nf9X6Xw8eTuNLcCnQpkr3A=,tag:x/K/eDTlzODHDE8up4Q8wg==,type:str]
    password: ENC[AES256_GCM,data:tkZpmHubjv2nxlUMM92k,iv:kdx1a72wA0zcIhMghnaSKdgdW/MR9JYvobozxD31o4w=,tag:AYSTp0DeA8lglm+CGp43Fw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WHBVYVZIYjdYWm9qL3Jo
            eW9IeVZjdXU3NnJsNEtxcEFGTFptQ0VBNHdrCmZ1NnJ1aW1UV3dncVNmUm5jck0z
            emdta2NXSUZkZVd2dU9JN09SWTIzWlEKLS0tIFpnT3NhM3gzOUI1MUYwZE9ma1dm
            SHZXMDZMaTVRclptS1pQRldINWpZL0kKJIyfaGex+W29LwOyKP3g8FL+pvpHiKPH
            giNVKOjWYaIBaA64gY6OE1qMcOCYKklqvmbcG4Lap9RHTI3rsZH+Fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T23:17:56Z"
    mac: ENC[AES256_GCM,data:FeA0BeUtlu+kaW2wW1Xdb/6C2ot62xdX+/gQKL80kLl/ta7wiafuswdU2SIo+6FC4wNSzYDFi1oz9GzE+LQGrQiqshu/mCBbnZAJKF+kH/n6pSq1OdCXvpuzTk73iP9TBnrHqlw8ay18L4VRDWW4GrPkG0st3mgY75Um3rRwTxM=,iv:mYD1l9u2J2qgyW9aKXgqarYYVJ9MNuOu1QB/GNibE4Q=,tag:urRkf3glnqLoppZFxPMIEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:nqIOd47+yE/JSUrJXQ==,iv:+Iz1vuXwDaGRVi5okcE0hubLGWySSvKexWWoer+TfkE=,tag:CuiMv43cedZS8JEsJU+pTQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:qjDWR4fD2YVsbsZ5cWMr2L3PjvI=,iv:zZbZGjLlahi5qbwHEX8S5KGY0g+fJ90TSLoWB4AfWOY=,tag:XXMS2GHiNMoIRh7mf63S7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WHBVYVZIYjdYWm9qL3Jo
            eW9IeVZjdXU3NnJsNEtxcEFGTFptQ0VBNHdrCmZ1NnJ1aW1UV3dncVNmUm5jck0z
            emdta2NXSUZkZVd2dU9JN09SWTIzWlEKLS0tIFpnT3NhM3gzOUI1MUYwZE9ma1dm
            SHZXMDZMaTVRclptS1pQRldINWpZL0kKJIyfaGex+W29LwOyKP3g8FL+pvpHiKPH
            giNVKOjWYaIBaA64gY6OE1qMcOCYKklqvmbcG4Lap9RHTI3rsZH+Fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T23:17:56Z"
    mac: ENC[AES256_GCM,data:FeA0BeUtlu+kaW2wW1Xdb/6C2ot62xdX+/gQKL80kLl/ta7wiafuswdU2SIo+6FC4wNSzYDFi1oz9GzE+LQGrQiqshu/mCBbnZAJKF+kH/n6pSq1OdCXvpuzTk73iP9TBnrHqlw8ay18L4VRDWW4GrPkG0st3mgY75Um3rRwTxM=,iv:mYD1l9u2J2qgyW9aKXgqarYYVJ9MNuOu1QB/GNibE4Q=,tag:urRkf3glnqLoppZFxPMIEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
