apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:UjZMGL28pks=,iv:/UjGyQUZSPXyMvSqFWpwTvMec0VgU3/wiOGlTqWfW/A=,tag:8sw3LEOFebXx570tlxEVdQ==,type:str]
    password: ENC[AES256_GCM,data:VeHNkFVeZdl+KiGcK49Z,iv:5fze8qaClT91Iio7pfWU7Bn3MDgBIj3JWw4LjBkk/YI=,tag:5dNtwHzmvTlwHPmhouO76Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZnByVkpxZGoyTmV6VHRq
            SXdVanp2VCtWWUN6dGFTWXFVb1pDOUxpUDE4CkFUNUtPRDJscURuVWkxUEpFbEFU
            Um0zRko2ZGxueVM2N2pLUTlFU3R1bFUKLS0tIDlJT2ZQSzMvWWdSSzBlL3E4VDRT
            NU5nd1JadWkxVm9qWW05aFVxWHF4TkUKpznp1b3xloq07WOFL6rFUKl9nilsNY2N
            BSRVOF8xiig3ZAu8RTBgdcP3pmLnit1Ui/MncPeV3q1jLyivgcH2NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T17:57:25Z"
    mac: ENC[AES256_GCM,data:flOLWH+iMi/2BaMwQ6U2HJWsL2qzYTXVjqDa1J2TH2YyhGA0YExpx2dpZnlzIyv2WhmNdcOek98GVnhWev1grSFcg0e0KO4353A2jYixGSXwi3rh7wlqWrfBL7vEL6POyo/zfAbUB3TD1bxywR/XuAcvHR3DBAkZOqVOwWtRiUU=,iv:BivCC+mGIqNxMzwPOAfhZR4FjcOYQGdG0VmMPOjI654=,tag:yXv7zxq78lIRx7HmB49dXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:zcMUE5Uc6+2Q/EkbMA==,iv:8kUjf1Y0HfDUCpl0DyxtWGP34QxHEbpznQJp/E5IBG4=,tag:pGjAIxibZaLg8lOfT5HbHA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:K57Wd8CcotKir1gm4DF3OTRinf4=,iv:GXn9AZBFzC6MTDr2HdYxyU2EkFCKhWu5TxUN7+jNfVw=,tag:Y8QSthJwp0a/e6K0dnJjkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZnByVkpxZGoyTmV6VHRq
            SXdVanp2VCtWWUN6dGFTWXFVb1pDOUxpUDE4CkFUNUtPRDJscURuVWkxUEpFbEFU
            Um0zRko2ZGxueVM2N2pLUTlFU3R1bFUKLS0tIDlJT2ZQSzMvWWdSSzBlL3E4VDRT
            NU5nd1JadWkxVm9qWW05aFVxWHF4TkUKpznp1b3xloq07WOFL6rFUKl9nilsNY2N
            BSRVOF8xiig3ZAu8RTBgdcP3pmLnit1Ui/MncPeV3q1jLyivgcH2NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T17:57:25Z"
    mac: ENC[AES256_GCM,data:flOLWH+iMi/2BaMwQ6U2HJWsL2qzYTXVjqDa1J2TH2YyhGA0YExpx2dpZnlzIyv2WhmNdcOek98GVnhWev1grSFcg0e0KO4353A2jYixGSXwi3rh7wlqWrfBL7vEL6POyo/zfAbUB3TD1bxywR/XuAcvHR3DBAkZOqVOwWtRiUU=,iv:BivCC+mGIqNxMzwPOAfhZR4FjcOYQGdG0VmMPOjI654=,tag:yXv7zxq78lIRx7HmB49dXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
