apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:igxtk0NbA/c=,iv:BrFb+l3cuZzYpJapRSL8BL7V2r6uPcU4mbb0ug+TvZ4=,tag:5Cuy6WZEm+J9hPHrxE3y9g==,type:str]
    password: ENC[AES256_GCM,data:VFX1khZ4jHwL87YOkCoN,iv:4IZHgLm7Q99Zf9VH3pmwlhCsuOLcvsCLQxPwV3H7LcQ=,tag:gz4hwKjmlbwo8yFqhF0DzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLY2N2N0pvL0NZYnNrZHFt
            Ky83Zyt4M214MTNEcXRHWGF5MlhTdUQyWkYwCk5tbUFpT2ROekQ1VjNLTHRjOEo2
            cVFpVmk4ZEZKMGtYSkt0MHBrYUdnSE0KLS0tIHlyWUtFK0pBeGR2OEl2REkxb1dT
            YUtXa1dtRXZUYmRUT29oV2RZN0p0dzQK/HM3F0hnzVOGmzsrACJum2OwthHj5i71
            nXDdTd3r9tGRPmyzfzV82XP+fGfMADKuGRrcMaRpq7fb7rlks6Wuvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-03T02:57:47Z"
    mac: ENC[AES256_GCM,data:UxCEAXc+g05iDWi+JpqU1U1JLKyuIjNx3+PPVlnfhx5mqC6bTjOUCmRNodS96PfeyKtIMVT+xDD12lAXhk0bd3ta4kalsBDHCCrKo3cv93W8mEWldTpBGzrZaALlZRZx+/xJ1VuG9LAhrZU5DQAPK1xjvwKO6/4CMGUlDqhCdbw=,iv:PLxIzQQdSDjZRrlaKRxekTsVzj8+YOTt6Qe8X7lceng=,tag:gmQ0h+cLnUO2MsQPsWT9jw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:2/21FWL/6s9hoXW3ng==,iv:LrHZm1ggXb2EGyrst40zsGFM3vQDSMni2pjG0C+5O5Y=,tag:a5p7x95bsGWKbu2qgXbN8g==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:SVEyYGL2/+Fp7HftIEDIYK8aRWs=,iv:Gtw+P4CQxnzLP5vIBxwTlCQ0GLI7uXmDIKE3XekSh/g=,tag:6rPsSmaHuqr8rgOOl7KHog==,type:str]
    MINIO_REGION: ENC[AES256_GCM,data:pHT7ccI=,iv:BVNYgmpfx5hl4oVWUOuFwQwaGYb3L3Bmze2Ak4oVjuQ=,tag:CCrbZTFKQVu2HrgyHOlQvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLY2N2N0pvL0NZYnNrZHFt
            Ky83Zyt4M214MTNEcXRHWGF5MlhTdUQyWkYwCk5tbUFpT2ROekQ1VjNLTHRjOEo2
            cVFpVmk4ZEZKMGtYSkt0MHBrYUdnSE0KLS0tIHlyWUtFK0pBeGR2OEl2REkxb1dT
            YUtXa1dtRXZUYmRUT29oV2RZN0p0dzQK/HM3F0hnzVOGmzsrACJum2OwthHj5i71
            nXDdTd3r9tGRPmyzfzV82XP+fGfMADKuGRrcMaRpq7fb7rlks6Wuvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-03T02:57:47Z"
    mac: ENC[AES256_GCM,data:UxCEAXc+g05iDWi+JpqU1U1JLKyuIjNx3+PPVlnfhx5mqC6bTjOUCmRNodS96PfeyKtIMVT+xDD12lAXhk0bd3ta4kalsBDHCCrKo3cv93W8mEWldTpBGzrZaALlZRZx+/xJ1VuG9LAhrZU5DQAPK1xjvwKO6/4CMGUlDqhCdbw=,iv:PLxIzQQdSDjZRrlaKRxekTsVzj8+YOTt6Qe8X7lceng=,tag:gmQ0h+cLnUO2MsQPsWT9jw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
