apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:BEA4/DGIVmI=,iv:X406kLxJdJ5ByM4i2lVgMxOI4d2aDT6Gr5ppz+GO81o=,tag:qDTIkrFy9KVIohg0WF83ag==,type:str]
    password: ENC[AES256_GCM,data:UfakfsD7nhQ4SFaf0TOz,iv:mMlalQAiVxKb1Q2/XtqPhNHiWc5XDJx9PENN/2kohSE=,tag:WES/RxcsZ3aJFzTBEZWaHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeW9PSVYyN0xIdlBMRFA3
            cjRVNHlTaDVzWURiQTFLTGRBdGhUQkhNSmdjCmVMOWxKZk9FZFFDWEliK3lMYWo4
            TUdlN3g0cGhiS2xYVXNsY3hPQm5kOTQKLS0tIDh5UFhZZEpqczIycmNTVE1JQVFy
            ZVpkQ2JHZEZtWDJtL2lqSG9EbWk5WHMKouwMFpa9cY95QMgGfmbAtVlH6xo/RlXp
            gfKKfiByFIiznq9frpDFS1m5ImtW69klH7/kn/zK1zhj0KZFfnwwoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T05:16:53Z"
    mac: ENC[AES256_GCM,data:7GLrxv8O9zlrXbE4CalJnJzjlauDQ6vwcR6R6NMC87kzpHZKXGPQJ7Iv4Y2ehL9cE+SEi5EymqUjd8AKjI6UrFVICADaocYbgUPfTte1zcdDgK2ybs+qyH+0anSwtj64oG99keaDcHstd6dnYCMx+1MNJFYNTZ8ryuoyqnaaO9k=,iv:aiu1cqctKD5UuWDx151Am2q3yzMH0h/sdeQmorK7jXM=,tag:gHz5g2EvsTKAu0ZFk2H2aQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:gdj36zjOTlYIS0Xc4Q==,iv:6sUf4C9v6KwHpbTjb8cKitWgCDTFlk0I6skHXKknL6E=,tag:FoWhl6ihQiy5lcA+zMJ98g==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:J1hC7CkeR+uDuBSMJ042VFtnVTY=,iv:Dtckrdq+sl2BmOcllh6e6YbDxDCMfV852S5iqyaUlZk=,tag:sSrMpd1s8GZPIF2JK0fGDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeW9PSVYyN0xIdlBMRFA3
            cjRVNHlTaDVzWURiQTFLTGRBdGhUQkhNSmdjCmVMOWxKZk9FZFFDWEliK3lMYWo4
            TUdlN3g0cGhiS2xYVXNsY3hPQm5kOTQKLS0tIDh5UFhZZEpqczIycmNTVE1JQVFy
            ZVpkQ2JHZEZtWDJtL2lqSG9EbWk5WHMKouwMFpa9cY95QMgGfmbAtVlH6xo/RlXp
            gfKKfiByFIiznq9frpDFS1m5ImtW69klH7/kn/zK1zhj0KZFfnwwoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T05:16:53Z"
    mac: ENC[AES256_GCM,data:7GLrxv8O9zlrXbE4CalJnJzjlauDQ6vwcR6R6NMC87kzpHZKXGPQJ7Iv4Y2ehL9cE+SEi5EymqUjd8AKjI6UrFVICADaocYbgUPfTte1zcdDgK2ybs+qyH+0anSwtj64oG99keaDcHstd6dnYCMx+1MNJFYNTZ8ryuoyqnaaO9k=,iv:aiu1cqctKD5UuWDx151Am2q3yzMH0h/sdeQmorK7jXM=,tag:gHz5g2EvsTKAu0ZFk2H2aQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
