apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:nKIeH4shL0c=,iv:bYNVQcsb2bJraF0x1J3skAGfFYtOBMkuROQ9XqocWi0=,tag:vNFS+jOMWND5Dyh5eJLAkQ==,type:str]
    password: ENC[AES256_GCM,data:lrqvEvKHTTbcByu8E0r5,iv:97sWhgmw4bpasndGCwYz6IpxfhYiJ5mTOyr9dVJy0KE=,tag:FclH1JDuFodVD5KcOCuN4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyM0tLNnFoZ2J4dHhIUWIz
            NE5FcjgyVERqcUhid0JKZmhiYlFkaTl5aEJNCkFPZUJYL05RNFlaN1p4UzBuckRG
            bjNjaGRxbjhlb1Z3a29pZkE2alk5M2sKLS0tIGNxNFkveEo0bUZXTWo4WTJ6aDFh
            OEl4OW0xOHRUUlBJc1VuQmlLbEZtcDQK50bCSni8Dn2g8LeQwRgaIxnXiaFRaDzD
            Gjj4OrPntGKRck9DTo7wD0mZ4jE6//KTBbExISD1B97pYISi49piuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T00:24:32Z"
    mac: ENC[AES256_GCM,data:GpLdDr2ORQ5761rEi8N1z7TsR9Dc0watH5oSaQd91qaEj5OcZVsCxBu4ZHHLjqtUgv0zv/zTzyT+XBVKcEQ/eZEUYqTJqGIAIkCpsYZc2nR3rTc4rez2MbfPAhJt+nLzWloTT2DGhEZhVRQ8mh8T/6hbHbVqixKl/mrpIxq9prA=,iv:3y21rTZcDU8OP6IIyeNra11Fk4MaSvoXs2//OIe5WiA=,tag:eijvYv3Lg+WbQZpqVg0CcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:kiFpCSDcNAqMwiHZOA==,iv:l92353HVGKjYRLTTNxz0d/5n0D7eekP34mrGF4fFkCc=,tag:k0czr/+qkyHeqL7JPTJSNw==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:EoiyH136JM2DS9kT4jiC4UhNMv4=,iv:60Re/3/nKFNBPoRcrPQNBCWVl0bQ4GETjHVx13Zef68=,tag:7nP/7PCkhn3szkjCwLSauQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyM0tLNnFoZ2J4dHhIUWIz
            NE5FcjgyVERqcUhid0JKZmhiYlFkaTl5aEJNCkFPZUJYL05RNFlaN1p4UzBuckRG
            bjNjaGRxbjhlb1Z3a29pZkE2alk5M2sKLS0tIGNxNFkveEo0bUZXTWo4WTJ6aDFh
            OEl4OW0xOHRUUlBJc1VuQmlLbEZtcDQK50bCSni8Dn2g8LeQwRgaIxnXiaFRaDzD
            Gjj4OrPntGKRck9DTo7wD0mZ4jE6//KTBbExISD1B97pYISi49piuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T00:24:32Z"
    mac: ENC[AES256_GCM,data:GpLdDr2ORQ5761rEi8N1z7TsR9Dc0watH5oSaQd91qaEj5OcZVsCxBu4ZHHLjqtUgv0zv/zTzyT+XBVKcEQ/eZEUYqTJqGIAIkCpsYZc2nR3rTc4rez2MbfPAhJt+nLzWloTT2DGhEZhVRQ8mh8T/6hbHbVqixKl/mrpIxq9prA=,iv:3y21rTZcDU8OP6IIyeNra11Fk4MaSvoXs2//OIe5WiA=,tag:eijvYv3Lg+WbQZpqVg0CcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
