apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:2//cl2atdew=,iv:NXIT4lm6mlLRlBxypMawKkqjbnMOzBu4GVWSilImgXU=,tag:sOD7mo5osyd62pwy5ZyKUw==,type:str]
    password: ENC[AES256_GCM,data:2M6+wDd3+y39Yl/68dsA,iv:9dYslC8K7E8w279jvLECzbf/wY3yhG2FJ36F54aqc0Q=,tag:yKc499pBj64H7GTCosSprQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSUlTRXJ3UVFNdmNFODNT
            Q29Ib29LTkhMU0ZSSlhRMk1HVW9oNlZNWm1JCjRWNlRWUEVmaHgzRkhVY1EzVTU4
            b2l3NU1VZ0hoMy9FaTRha0t0MW1FVjAKLS0tIHVYUG9xa1BKaitkZVM3THlKSUpu
            THg5YUdLVGxNbE1VSURCWVlJTVFWbXcKlpLZqQTwymqPDL02tO34BtMcl+lvdagu
            OH7RGZkUe8TByJzXhv0YhmfRLQZW6T5Bd4i0Lce9zq5Ovkxz2IczRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T07:02:54Z"
    mac: ENC[AES256_GCM,data:+Bih73TIFs1e7VbSIAnhWWHdkD8bXe/X4kUoOqfj4+t5+kq/M48GfoKs0Tmj1RJXwyWmrXq+dmUVMPfUseCYNTAHp43H/07t5H7SCTmKzWMaWgVv02k0D1ypGOGRnUfl/6vhO35jZST+Hzay8LmUaQsK7r0ILzadrFdTn4SwEls=,iv:wU/5ALkXDCbVfrOfyzXbQEsHrJbGCdKdJrD3MeipaeI=,tag:Asv4QLlm8D2CYvzZ1S/cig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:SWhYMNpLhkoMuKHgJQ==,iv:oXJJEHHX7snkg6QoiTik5I2YVJXMzqu3mVa6ksYI3uY=,tag:4tzapFMiYQp4GyJ/pjqN8A==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:tJ1lJlJbbXQ2Zxt7HY49mt4qIsw=,iv:po6pOTdoe+IMZK+TT3mUOF1CPh3bCDJg5gpT+oyhKW4=,tag:kywayRmbjNIvvy13EuV1KQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSUlTRXJ3UVFNdmNFODNT
            Q29Ib29LTkhMU0ZSSlhRMk1HVW9oNlZNWm1JCjRWNlRWUEVmaHgzRkhVY1EzVTU4
            b2l3NU1VZ0hoMy9FaTRha0t0MW1FVjAKLS0tIHVYUG9xa1BKaitkZVM3THlKSUpu
            THg5YUdLVGxNbE1VSURCWVlJTVFWbXcKlpLZqQTwymqPDL02tO34BtMcl+lvdagu
            OH7RGZkUe8TByJzXhv0YhmfRLQZW6T5Bd4i0Lce9zq5Ovkxz2IczRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T07:02:54Z"
    mac: ENC[AES256_GCM,data:+Bih73TIFs1e7VbSIAnhWWHdkD8bXe/X4kUoOqfj4+t5+kq/M48GfoKs0Tmj1RJXwyWmrXq+dmUVMPfUseCYNTAHp43H/07t5H7SCTmKzWMaWgVv02k0D1ypGOGRnUfl/6vhO35jZST+Hzay8LmUaQsK7r0ILzadrFdTn4SwEls=,iv:wU/5ALkXDCbVfrOfyzXbQEsHrJbGCdKdJrD3MeipaeI=,tag:Asv4QLlm8D2CYvzZ1S/cig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
