apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:jKDbLuIbkSc=,iv:Dnntw5IOTQg3403b6osSCNhTDgYmnFGinEpX2+JqTtc=,tag:3pJc5Qs1ERP1O64Gdd8Zsw==,type:str]
    password: ENC[AES256_GCM,data:paXGspw6v+Yy4d1LImbp,iv:oMClLQY1PIbJEt0G9sDsUSK1FSBGS6GtjlZqBlKSgSU=,tag:CVK93vw66UScitWTK6uJNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdzlVRnU3aU03VElPNGpR
            N1htd2ZVNXh2M1lRSUI0MDBsWmgxTjdHb21NCnFHdWo3OWxKSk1WekQ0dGx2a09B
            ZVFHcFUvejJndmUxUEhQVUNrWTEyY1EKLS0tIE1teHN1eWl3amlzZVhoeFMxdFlL
            blpFRDJtZnV4cnc1UllMQjFQcVFjSmMKELhj2eW/m+IfAETdqpVdtAkuwS+OnKOt
            UgK4K7LXRpZu/FgjXoLjvRZOU97ttNul+m31ciIFJB5YNovGv5CGMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T02:37:10Z"
    mac: ENC[AES256_GCM,data:Ea5lNcE8qyQIaYZ8Nr9A2AAACIVkUhv0y2FubzSrNUYNuP1CA32bIyGd87mBt0wl9JnhOMZVSDM0iATX/w/v0Sk+2zyCfwQknXuuILBqCQ+uDLbLkHaR/cN101uwo7DWiHO58fbfS4/Nnek5tUAWpXFfemEoMXM/vvOLVlohn4w=,iv:6tEmHgWHqUazBUDa72mS+91ynAtJ2JdFSd2yEdwnB5Q=,tag:+BFP5Ue8ueyE/Jj73NSX2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:UW1YculYlz7Gnk3XBQ==,iv:lmBIuTEx4vuek6U9kzuuY0b6pnaCA1LLYRyG9LSEj7Q=,tag:JSUsVlc+sBozWWs/cvELCg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:ccZBhmmo0wq/eJ8wSPix8BK1ApA=,iv:sokYAfTMyaCs6zg7cEKVdgXWtIxIiDtte0VsLg3R+fk=,tag:r3KLTzwdp/MIDrvNx+oQrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdzlVRnU3aU03VElPNGpR
            N1htd2ZVNXh2M1lRSUI0MDBsWmgxTjdHb21NCnFHdWo3OWxKSk1WekQ0dGx2a09B
            ZVFHcFUvejJndmUxUEhQVUNrWTEyY1EKLS0tIE1teHN1eWl3amlzZVhoeFMxdFlL
            blpFRDJtZnV4cnc1UllMQjFQcVFjSmMKELhj2eW/m+IfAETdqpVdtAkuwS+OnKOt
            UgK4K7LXRpZu/FgjXoLjvRZOU97ttNul+m31ciIFJB5YNovGv5CGMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T02:37:10Z"
    mac: ENC[AES256_GCM,data:Ea5lNcE8qyQIaYZ8Nr9A2AAACIVkUhv0y2FubzSrNUYNuP1CA32bIyGd87mBt0wl9JnhOMZVSDM0iATX/w/v0Sk+2zyCfwQknXuuILBqCQ+uDLbLkHaR/cN101uwo7DWiHO58fbfS4/Nnek5tUAWpXFfemEoMXM/vvOLVlohn4w=,iv:6tEmHgWHqUazBUDa72mS+91ynAtJ2JdFSd2yEdwnB5Q=,tag:+BFP5Ue8ueyE/Jj73NSX2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
