apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    password: ENC[AES256_GCM,data:5DE6D0HiIZoNnoXAKYpG,iv:SldTE764/rsVhgoivy+Ek5ZzUj4hVup5s3UYhQbYk1E=,tag:Q0uQQXuGk4Owy5NWSBp4dA==,type:str]
    username: ENC[AES256_GCM,data:2UUnNqycBlBIIrhg1owhrQ==,iv:3wmff5qAdRJjqyr2ImgaKskbuize2iFejSdXUYkNie8=,tag:+DRq4DDGIR/7+KBXxM4ByA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTmE1bzFLNUJRR2ZlYTZE
            Rmg3OUlFVVhONU9LQ0xTWmRNd1hDOUZmNXkwCnlJemFQSWdsSkZORmdxM0ZwcGF6
            Vk9YbDhwemorUXVaK3Y1VVdCcEc3RXcKLS0tIDUzS1F4bHRoL0thTVlKRzUwdjNV
            TnpEdzBWWVRvOVc1elIwNCtVNU5veGMKWeFrC/gLI7MzEnkHGwj6yB6AkiNYrkSn
            jEmSLYNPKi5/gixd1Lw/UaYgoQ8Vz01cASctJaD8CV0ETl1fDIqP5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T22:33:24Z"
    mac: ENC[AES256_GCM,data:AhYWOfRGoq+S5mBZgt0ickKNJ6/+otRRelGlZkoRuXGSmGiEgTDtV9HvNk1R3iU7kaYCZhlqiECgljk/v8Y8QcW53ZFySzEhnpO+fG+Fec+s7SMitL66/4XLia95DamXcHHh6HmlVVUZv4OuXa8JY8y5nH8Yxx+J3Fra5Bu4Oj4=,iv:tD3g2evQJ+dlLfnsHqFnV4oXvFBDrAba6fftqFQFt2o=,tag:sINMXk+oycBgI3ukLLbhfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:M68geEwKF1/cIUD0gA==,iv:VQ+Y97fbrNSq+4g3RBoYAbRkr2VPvZI6cgF34AMHAl8=,tag:0E00PqJVMIOeRckT7usFEA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:a3sTz+NnZl1la+xNvmtW9FIxDHQ=,iv:HrPB75SzxHFM82WopJhXTQPvLUnzlrlYbESD/6OwxA8=,tag:IprJS03NcI933T2QMYzyYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTmE1bzFLNUJRR2ZlYTZE
            Rmg3OUlFVVhONU9LQ0xTWmRNd1hDOUZmNXkwCnlJemFQSWdsSkZORmdxM0ZwcGF6
            Vk9YbDhwemorUXVaK3Y1VVdCcEc3RXcKLS0tIDUzS1F4bHRoL0thTVlKRzUwdjNV
            TnpEdzBWWVRvOVc1elIwNCtVNU5veGMKWeFrC/gLI7MzEnkHGwj6yB6AkiNYrkSn
            jEmSLYNPKi5/gixd1Lw/UaYgoQ8Vz01cASctJaD8CV0ETl1fDIqP5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T22:33:24Z"
    mac: ENC[AES256_GCM,data:AhYWOfRGoq+S5mBZgt0ickKNJ6/+otRRelGlZkoRuXGSmGiEgTDtV9HvNk1R3iU7kaYCZhlqiECgljk/v8Y8QcW53ZFySzEhnpO+fG+Fec+s7SMitL66/4XLia95DamXcHHh6HmlVVUZv4OuXa8JY8y5nH8Yxx+J3Fra5Bu4Oj4=,iv:tD3g2evQJ+dlLfnsHqFnV4oXvFBDrAba6fftqFQFt2o=,tag:sINMXk+oycBgI3ukLLbhfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
