apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:Pl+ddmTsWj9eol1cQULt7g==,iv:WBazcDgxUokb+wNUi8FbTBoNkyQ9+XfiHnE/ABsen5w=,tag:6n3BeybTLA9Z44Ctl2dOXw==,type:str]
    password: ENC[AES256_GCM,data:xlBVgAQ4YCbdFePNMkmT,iv:xOlFPC2yVIDr2x7FY4boHcHd34IZkCcFfWQCiPBuRZc=,tag:aJ/Ziqy/1z4jFAfkaBjuJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWmR1dzFaNTU5V1hxQTEx
            NDRTSHZ6SXpaRm0vNGx2cmw4RDJReDJSN0VBCmVUc0dXKzEyREQwUTdKb0xDUk1X
            Z2VYQ25yNUJSTVFSTE4rZnZocllwU0EKLS0tIGcvKzRVV2RPTkNReURTUElLZExI
            Z0dLSUVSS0NQWEpFcTFRMEhsMmFQQmsKtQjrh28Q5LG8BABr5fGyuoHS9Lq0eU4q
            W6fgce95cBpnKzahDpDbq3ojkxonBoHgBGPE7e59GYYRrvRwdSqyAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T23:54:52Z"
    mac: ENC[AES256_GCM,data:r3N2w0d8N5EzCeUfzZNpuFWW/1vx/dNTXGRPLQsw1866cxL7V6sG4q4gX34ZJNarbFDI6CbT+IaO4KTsTR7IPtaStyzhivE0l6VhcYzDEmu0aKe4ijKeQhDZSkxT2Py5Rigj/2H5IWp9EHnhvWJ+BpAcd0mhICTkLIlnCC0sWA0=,iv:IFGP/OHkbNYbd3FCGlczB47WPdliLrXWta4A0dAljbM=,tag:Iii78AV/J+8TjTgr3yvBeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:A6yomg0VH+HTPGdh4Q==,iv:KOAwNvJNA2ayjPepdqQALbwMqBZHn5cmXsNS85hCDv8=,tag:JAp7X0yozUiup79hyRgGAA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:IVUB+K1QncxlxPCS7cJeS7c7fx8=,iv:7NoffFBRxaHedd87wVXoJ7QCguC8MiIq0D5EqOgoTzo=,tag:IloTSBMhmIoPdL9rLxU8TQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWmR1dzFaNTU5V1hxQTEx
            NDRTSHZ6SXpaRm0vNGx2cmw4RDJReDJSN0VBCmVUc0dXKzEyREQwUTdKb0xDUk1X
            Z2VYQ25yNUJSTVFSTE4rZnZocllwU0EKLS0tIGcvKzRVV2RPTkNReURTUElLZExI
            Z0dLSUVSS0NQWEpFcTFRMEhsMmFQQmsKtQjrh28Q5LG8BABr5fGyuoHS9Lq0eU4q
            W6fgce95cBpnKzahDpDbq3ojkxonBoHgBGPE7e59GYYRrvRwdSqyAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T23:54:52Z"
    mac: ENC[AES256_GCM,data:r3N2w0d8N5EzCeUfzZNpuFWW/1vx/dNTXGRPLQsw1866cxL7V6sG4q4gX34ZJNarbFDI6CbT+IaO4KTsTR7IPtaStyzhivE0l6VhcYzDEmu0aKe4ijKeQhDZSkxT2Py5Rigj/2H5IWp9EHnhvWJ+BpAcd0mhICTkLIlnCC0sWA0=,iv:IFGP/OHkbNYbd3FCGlczB47WPdliLrXWta4A0dAljbM=,tag:Iii78AV/J+8TjTgr3yvBeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
