apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:EgdV1BaYRlc=,iv:6GYxzeDUMMnHGhCCFxcAdmWZx6pNBeOuX+DB07tuWBQ=,tag:+J+EfIkarMLD8f96T5ux4g==,type:str]
    password: ENC[AES256_GCM,data:ep6iWkNF+8r0K7qGFzu9,iv:1pdikaPaiEiNzZLaJ57u7DbgCWKsKDUXNTD2Y9Ghr7M=,tag:NA8DYHL9xvItPrhzzAgXxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQnVEVVpXbTBrc3MvT1I3
            eXRHNHRuZnV1OXF3ZnJ4WE50enNNTkxRRHhnCmtxTDVDNzIyWjZ4VUptVkQ1TTNW
            K1FaYVVic2lFRGFReEpvOHN4MFAyL0kKLS0tIG9EVHExakozaitETWl1VFJjZ2Zz
            em16endKYVRwa2pIc3NzMEFGN004Z28KxKzaG8p21vNdkSjLjqX3X27ia0cLAr2v
            38NjMS/AST/ELXD0yZ3qQNY4/czd9Ir3+uJCNbcuTPuvB5icgA3nwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T08:00:48Z"
    mac: ENC[AES256_GCM,data:yRtfZsXNJG402/nO4iRyJ0nyXtLXvrEnBf5h+S7cWD6S9fk1Dz2gQ2xhuzCurqW5yrzeO/fO14V7xoOg0JjfKYoaa3c3/uj9E/Osx3wSJ+Ov5wdpDztwRan/7LzHD69mHM4N6RMwbYlWcKFFO+TL4hYwphkOkjABJWLXORsFLG4=,iv:v63F7Ai1zOhogAwXhoC/djssJT3BSMx60tg9SsVdUks=,tag:cW6A81+kTx/QgR6Zek4vKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:0ijxhujYpfrgy8RoRw==,iv:RHYl+NmxIwgiPV/B2jokql6t6zXDYEafaGOH7tk15YE=,tag:34f97GT+SqqaVfAoNij8sQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:TzjcW9bD4SphQpKgrbofSc6K+Uw=,iv:9RAPyJ373NcqeMi5Cs6Q310jEfODFtAIpTN6/h4rO2E=,tag:jkJe9NLB4WNI5ej97qs75A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQnVEVVpXbTBrc3MvT1I3
            eXRHNHRuZnV1OXF3ZnJ4WE50enNNTkxRRHhnCmtxTDVDNzIyWjZ4VUptVkQ1TTNW
            K1FaYVVic2lFRGFReEpvOHN4MFAyL0kKLS0tIG9EVHExakozaitETWl1VFJjZ2Zz
            em16endKYVRwa2pIc3NzMEFGN004Z28KxKzaG8p21vNdkSjLjqX3X27ia0cLAr2v
            38NjMS/AST/ELXD0yZ3qQNY4/czd9Ir3+uJCNbcuTPuvB5icgA3nwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T08:00:48Z"
    mac: ENC[AES256_GCM,data:yRtfZsXNJG402/nO4iRyJ0nyXtLXvrEnBf5h+S7cWD6S9fk1Dz2gQ2xhuzCurqW5yrzeO/fO14V7xoOg0JjfKYoaa3c3/uj9E/Osx3wSJ+Ov5wdpDztwRan/7LzHD69mHM4N6RMwbYlWcKFFO+TL4hYwphkOkjABJWLXORsFLG4=,iv:v63F7Ai1zOhogAwXhoC/djssJT3BSMx60tg9SsVdUks=,tag:cW6A81+kTx/QgR6Zek4vKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
