apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:fY7oweZc38c=,iv:qTPQZjBAycweZVy2UjIktT/ktWv5znTEh9rexVnlKrk=,tag:DWLpDrJAydyWRjunUy7ApA==,type:str]
    password: ENC[AES256_GCM,data:pV1Qp6eWPqfg6v/UG8yn,iv:Gye0byG8t8ivXN7MWQxc1OfELUpbmESz8UJY3TcIaFw=,tag:PC+vOK7Qlzga9NisPRZd5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZGI0ajd4OHhEeWpCRVZi
            TzRqS28xRTF2UWp5S1ErSGhwWm4vYzk5eWhRCjQ2L2xPdkp4QVVnVkR0UW1acjJ5
            bXFSQjNJQkdTcTNEbWxwMFVuZnZnaGcKLS0tIExLOFJSbEZrb3FNWFBicFREOUIw
            ZjY4bEgvV0lkYVcvSzFYa1Ftc1pubDAKcFg0+B3Slw9OxblsCutAFc/iigkD0XR9
            UNt2sEqeOkBL+3I21Yx3IOmJh6eHNLmyZjCJhaSSvL3jlXTKS1RDeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T00:28:34Z"
    mac: ENC[AES256_GCM,data:06KLU91v3d15HaVDmNoXAkobdCRrloITsrJgvZlUpB/Kfl9fM8E4swkO8pjIg8K43ic86lPG4ll5fl6w7D0LEFvMASpKIUlEGKgsVi9mYOvZfDaJxSui7e0gfRw7LaXE7AufMzNSNzD/G5T5MLU7BsMiK5kWOtuYmUtFFpoggL4=,iv:cjpC1Thf8EloaFwsi3bzenCXf4F5B8f8H67E8n6sW6E=,tag:bGvOBp8Erw/KVe8Fd9P4Hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:cRhzXvtwLAO+4V5xOg==,iv:yOFbABpTrBfqyJp6qaA//o1gDLaXLrO/mUwKKGgIBhU=,tag:LfvATQTS9SDW78hO3qNKuw==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:cJvIWi+NqwEdm7KiVGZ47/hTg3g=,iv:K2fCU52yfgMgHjbQH2gYL3hKETMAN5iYU+c4KTRh/R8=,tag:mieTiboeoS0ppeM1Bj7leg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZGI0ajd4OHhEeWpCRVZi
            TzRqS28xRTF2UWp5S1ErSGhwWm4vYzk5eWhRCjQ2L2xPdkp4QVVnVkR0UW1acjJ5
            bXFSQjNJQkdTcTNEbWxwMFVuZnZnaGcKLS0tIExLOFJSbEZrb3FNWFBicFREOUIw
            ZjY4bEgvV0lkYVcvSzFYa1Ftc1pubDAKcFg0+B3Slw9OxblsCutAFc/iigkD0XR9
            UNt2sEqeOkBL+3I21Yx3IOmJh6eHNLmyZjCJhaSSvL3jlXTKS1RDeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-30T00:28:34Z"
    mac: ENC[AES256_GCM,data:06KLU91v3d15HaVDmNoXAkobdCRrloITsrJgvZlUpB/Kfl9fM8E4swkO8pjIg8K43ic86lPG4ll5fl6w7D0LEFvMASpKIUlEGKgsVi9mYOvZfDaJxSui7e0gfRw7LaXE7AufMzNSNzD/G5T5MLU7BsMiK5kWOtuYmUtFFpoggL4=,iv:cjpC1Thf8EloaFwsi3bzenCXf4F5B8f8H67E8n6sW6E=,tag:bGvOBp8Erw/KVe8Fd9P4Hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
