apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:30KlSDR9wIA=,iv:i7F5nF7gDW77OVd9Ifiva1im3rI8q6lg0zP2A9wRtkc=,tag:UWm7D5tM4IQcOxxeDkXjTg==,type:str]
    password: ENC[AES256_GCM,data:w4OJdq3oh9Mfw6zwVdKb,iv:yQ1llBfWK7c3jhLRPFFuyl/yOhhoFUjVw4tzG0d7Z4w=,tag:y+5rJaJZZjYnj6knJ+9nOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTc2dtbFVMYktNL24yQzFZ
            NjdMWlpGKzhVVmFSQzBaczdLbGU1WHF6YmhnClBKYmF5QkdFSWc4eTlPbFFxVFo0
            NjIxZ2p6cUlRN3VwLzF1S2s0bGtYWVEKLS0tIGwxQXY4OXFlYXpveXN0cUJOZVJk
            bW1JRDJ6NEFNSm5FaTl6eEdqeUlkckEKrcoHT6pQDq0icVyvDEpwU+kVlLuL22tK
            9d39eFzjRB3kjBAv4oqqQLeq9QEto+3NEkbXgLidsDZjA064gxX3PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-03T03:07:03Z"
    mac: ENC[AES256_GCM,data:hk9UfN+Oy9pC07VP3+jZPP0iSEGLmx6dsRmgFAyTgtCAEDwA9yEg3aF8AzhPwP8QRsroGTD6IhQwUja3DgO800NTVFFpt+zXJg1sCRipeyC2u9Q5BQ5sUaSHUJ7vwJ7zJnEDr+3vB0jhbx1zupqZYLHC7e8RLRTuSF6g+wapkuE=,iv:8dSvRkqzTZF1b52eKSqFB6j4wB0JAuwojmHY8YRoHw0=,tag:bFXa0YbFn8JvJPIg7dhMRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:si4Jz5X67OWwKiYhuw==,iv:jbYP/So1cxTa1scBQAMePXOlkVs2L0w5sphoq2x/Z7M=,tag:yjVwqO6M82EHdrruKuYVdg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:Z4hfEhPHaWV5dJ6pbwH4Y4Wreo4=,iv:ceI6odpSWk8YkZhtHtKPDf2WPWc54kj9fr6f4E7U5LU=,tag:UPSR2KO1mFGEm/T+WEaPAQ==,type:str]
    MINIO_REGION: ENC[AES256_GCM,data:nfaMEY4=,iv:eZ+kAAMVkAdbDA2HCDA0teyXgHVbmOvdo2C4Z3imE2o=,tag:ZAsF6KBsImtsGUbmA1zVvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTc2dtbFVMYktNL24yQzFZ
            NjdMWlpGKzhVVmFSQzBaczdLbGU1WHF6YmhnClBKYmF5QkdFSWc4eTlPbFFxVFo0
            NjIxZ2p6cUlRN3VwLzF1S2s0bGtYWVEKLS0tIGwxQXY4OXFlYXpveXN0cUJOZVJk
            bW1JRDJ6NEFNSm5FaTl6eEdqeUlkckEKrcoHT6pQDq0icVyvDEpwU+kVlLuL22tK
            9d39eFzjRB3kjBAv4oqqQLeq9QEto+3NEkbXgLidsDZjA064gxX3PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-03T03:07:03Z"
    mac: ENC[AES256_GCM,data:hk9UfN+Oy9pC07VP3+jZPP0iSEGLmx6dsRmgFAyTgtCAEDwA9yEg3aF8AzhPwP8QRsroGTD6IhQwUja3DgO800NTVFFpt+zXJg1sCRipeyC2u9Q5BQ5sUaSHUJ7vwJ7zJnEDr+3vB0jhbx1zupqZYLHC7e8RLRTuSF6g+wapkuE=,iv:8dSvRkqzTZF1b52eKSqFB6j4wB0JAuwojmHY8YRoHw0=,tag:bFXa0YbFn8JvJPIg7dhMRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
