apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:E2e+OWgI6Dc=,iv:KV2pYA4OwZa6fVoroqVEdtMDgk/ULCculMx8v7DnWpQ=,tag:dSTMHJQXIczn9f80kHDooA==,type:str]
    password: ENC[AES256_GCM,data:km7P+pgIOAw22C4uen7E,iv:kzUOmHMF5++7HrLjdpuW6oQOyguqoX1Qpw2HK27rTm0=,tag:KgpuBqHckW5iatziluH4uA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXU29WbEJhOEVRdmhUb2Q1
            NzhQc0xmelNlRVUzOEFEbVlDa095Z1o3Y2l3CnF5L1c2ODZaNEtJa00zN0VtMHlx
            Rm1qZ1UzTThkQWpuZVQydk5RTG45SDQKLS0tIHlwOWJhZFcvWjJiRFlQWUpML1l0
            Q3FVZS8xWm9XcVBWbHE5NEJaTzN3dGcKzJyX8TEW2A3uJVJA4QQ4iRhYOGIq/2pb
            OnaR+wj2tjltK+IvAL/1R83feshHvVeZqp3qKDaYSI8ZAj7HIuOkpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-02T19:40:15Z"
    mac: ENC[AES256_GCM,data:h0gCm+47q1usYtFPr8YLv//f7cun0DZ3lDhGykgAQ5+Hafk/iO1Rp89FFuk8n2pu0IaMEAH1o8Ur34izTZZguztU3wQxD4RW8L5CzQBXhy9/kwhnlsvhUzUeoNrwDg5eGhI5NNu4lITTE1VDPUcE+J0Umg/jUtmxGM9y4rnDXNE=,iv:3klm+wJYfN+oe1Kz2hJB8FjqB93ZLG/JPd8wOfJ3zKY=,tag:GZRbh3R8Pb48AGZD/RNYIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:CRdEwdb4/CsE57vniQ==,iv:8tfhMAWeXqyjHYGCzTOMTht0Zyz4QObWHejNyvTzrzA=,tag:lIZdizfV4H1tgRi3VKO5LQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:uGK7Qf6RWqPUhCMxquVf6Tmnql0=,iv:2XobxVvjVmBN4ZD83BbvG3CGsg5ZdooDmn4XvS4F6zI=,tag:q3nHg+JG9yZVFoIBqCLh7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXU29WbEJhOEVRdmhUb2Q1
            NzhQc0xmelNlRVUzOEFEbVlDa095Z1o3Y2l3CnF5L1c2ODZaNEtJa00zN0VtMHlx
            Rm1qZ1UzTThkQWpuZVQydk5RTG45SDQKLS0tIHlwOWJhZFcvWjJiRFlQWUpML1l0
            Q3FVZS8xWm9XcVBWbHE5NEJaTzN3dGcKzJyX8TEW2A3uJVJA4QQ4iRhYOGIq/2pb
            OnaR+wj2tjltK+IvAL/1R83feshHvVeZqp3qKDaYSI8ZAj7HIuOkpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-02T19:40:15Z"
    mac: ENC[AES256_GCM,data:h0gCm+47q1usYtFPr8YLv//f7cun0DZ3lDhGykgAQ5+Hafk/iO1Rp89FFuk8n2pu0IaMEAH1o8Ur34izTZZguztU3wQxD4RW8L5CzQBXhy9/kwhnlsvhUzUeoNrwDg5eGhI5NNu4lITTE1VDPUcE+J0Umg/jUtmxGM9y4rnDXNE=,iv:3klm+wJYfN+oe1Kz2hJB8FjqB93ZLG/JPd8wOfJ3zKY=,tag:GZRbh3R8Pb48AGZD/RNYIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
