apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:AxUT35SHeCs=,iv:eEiSyP5zpwFJCV6PAPD81kE3bM1V1HWuDhZUC3d5QiQ=,tag:R0Fm9zZp6WJVNC7vbiNhtA==,type:str]
    password: ENC[AES256_GCM,data:vV9/VLsKF0/emGhy3UMD,iv:9757BksaOlNxo5HghpufSWOaR5nKb+E//8YOy8D9e48=,tag:Ld6JTJL1u5EJINOhPTlVbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eWxXbFl0bXpOdmhzZXpP
            S0FwbzRCTStOaGtOckVSR0Z6WkRyTDIwbERNClVVR1AvT3ZRclUrdUJoM1JFTzJV
            N1E4RkIwRG0xWm91Rk1KMkw3WXJtQ1kKLS0tIFpjdHMyb29tYmVzYUlUeGJobVM2
            Q01RUDVBQ2l4Skt0MUVxQjRCMW4veDgK0/qkNvVdFOp7uU4Zn4ObcdCv2StRw3Mr
            kKS/YSPwL7PhfPjgo8epkEGZlJyOBP780UpoodhcRsIWlnvLW+P5Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-26T02:50:55Z"
    mac: ENC[AES256_GCM,data:tEy7smFekyHLAjS0fiw63d6MYtqzYthcdBm982dFpILXn8zdEx206p4+3WW/h48nokn0y98Is/4vB1Jk/36pDORaZXd1wgJ9/H2qOcWogTYZHuCAuvnkVPbwlPs8FHysFllFnfYnoi0e1Gm+dqFUzwWtkbGu4535DkwWRoaQvNY=,iv:qtpJEs54Uj47A7FfYkoEtmOi1a8HiLYchzpG9j1F4Zo=,tag:lGYwCqdd8VhQftee1Ky9SQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:gIwWMwawuKFGXOSfaw==,iv:MnQyVXEvj5U2bmvp5TfHS894+7oWQ5PvSPfRFSIqlOg=,tag:psnyzEBaKgNex5SXw05c2g==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:3AED7xymI2Uf+VJFLI18tDKqHkc=,iv:x+oR4EnpxN1tuACQ6np72R2pFQ+X+/I5hZ6cGybjBc0=,tag:k8OFP3IRI5WV4yamsP9iTw==,type:str]
    MINIO_REGION: ENC[AES256_GCM,data:sUILvIQ=,iv:CDw6m/F4/ZQzCQnc2oVi8bLaY2O8ZREhF+icTaJ8kgI=,tag:H6IvN2ipX6NJHGBbOj8wYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eWxXbFl0bXpOdmhzZXpP
            S0FwbzRCTStOaGtOckVSR0Z6WkRyTDIwbERNClVVR1AvT3ZRclUrdUJoM1JFTzJV
            N1E4RkIwRG0xWm91Rk1KMkw3WXJtQ1kKLS0tIFpjdHMyb29tYmVzYUlUeGJobVM2
            Q01RUDVBQ2l4Skt0MUVxQjRCMW4veDgK0/qkNvVdFOp7uU4Zn4ObcdCv2StRw3Mr
            kKS/YSPwL7PhfPjgo8epkEGZlJyOBP780UpoodhcRsIWlnvLW+P5Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-26T02:50:55Z"
    mac: ENC[AES256_GCM,data:tEy7smFekyHLAjS0fiw63d6MYtqzYthcdBm982dFpILXn8zdEx206p4+3WW/h48nokn0y98Is/4vB1Jk/36pDORaZXd1wgJ9/H2qOcWogTYZHuCAuvnkVPbwlPs8FHysFllFnfYnoi0e1Gm+dqFUzwWtkbGu4535DkwWRoaQvNY=,iv:qtpJEs54Uj47A7FfYkoEtmOi1a8HiLYchzpG9j1F4Zo=,tag:lGYwCqdd8VhQftee1Ky9SQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
