apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:UJszhucLGNI=,iv:d61ss1ItRJLY3A3pU7A5tbD45qlpIaZWwEcnA3P9JSM=,tag:BYDKhBAcAdjRvSXyUcPu/A==,type:str]
    password: ENC[AES256_GCM,data:Wmdj0pnqKz9pZib1S3Bs,iv:ucgO3wJXPraqtHnU9gj8dT7dCoJ3zAayNoon63pBYSA=,tag:Vj2Zm8zWNlsmn9T6IWKrkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNHJveWZZNGYrYW41Q0M2
            dFk5UkFUdlRlYTFvWEFwemZRYkVuTFlpS3pNCjQrRUEzdHZWS0xPaUIrQUZJdmdw
            QTNRcmhsUWJqdEdtN2JFUFlCdXI3OGMKLS0tIGpLUjloV3ZnNGxua1ZDL1c1ZEpr
            VFpHZmhlZEZEeDlNZU1KMEhEd0dHVGsK5hEcIOdffoymGc1T4XtnGSt6sMMp/9pO
            OBvy1u2BqVwhb4tmBVt+XhJcFaqt+7QsYDXd4jilhMlioxX5LdICQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-22T04:14:47Z"
    mac: ENC[AES256_GCM,data:xQiYnqZdgPidYRcivoX/rd6fGXBhNSkjZ1YFO9UMC6ppGImdFatIPUm3FNOc7xM9cLOpF+ltupL8nS6oxHywlo4DgeI7lOHw8YoxziKgAkQgEornIWEMzvBKHNJbAvSGDR526LCvxBHtZuZc0DXhhfH3gVn22CyIlQLzSuI/VV4=,iv:f/h46vr8a+KG6+nu9juWQi6sCN22bvlpr1oDWvdywlY=,tag:EQmOo7ifVI1IMV01i0h+Xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-minio
    namespace: databases
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:qgopdSCEets6ljWngg==,iv:yayIsV5vHiU0vS+E5ABf6XreuFxIgSbiECvmqfp8Seg=,tag:pG07/BBfZkq3cDa/nvljxg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:1S1jHAQ+X2VERARZRfz3IZvDky0=,iv:fuGq6MvExYHe0ZRDJJ8cC/QT+7nttiHxJKh8zhD/QAw=,tag:qbYIVP50Op51MZAdazAluA==,type:str]
    MINIO_REGION: ENC[AES256_GCM,data:rwAgxGQ=,iv:CKGal0Bez/J7nN/bro+bkH7RHe5l6w71HXAONZlsbPU=,tag:o2UQJqHQqH6ONafPQypzog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNHJveWZZNGYrYW41Q0M2
            dFk5UkFUdlRlYTFvWEFwemZRYkVuTFlpS3pNCjQrRUEzdHZWS0xPaUIrQUZJdmdw
            QTNRcmhsUWJqdEdtN2JFUFlCdXI3OGMKLS0tIGpLUjloV3ZnNGxua1ZDL1c1ZEpr
            VFpHZmhlZEZEeDlNZU1KMEhEd0dHVGsK5hEcIOdffoymGc1T4XtnGSt6sMMp/9pO
            OBvy1u2BqVwhb4tmBVt+XhJcFaqt+7QsYDXd4jilhMlioxX5LdICQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-22T04:14:47Z"
    mac: ENC[AES256_GCM,data:xQiYnqZdgPidYRcivoX/rd6fGXBhNSkjZ1YFO9UMC6ppGImdFatIPUm3FNOc7xM9cLOpF+ltupL8nS6oxHywlo4DgeI7lOHw8YoxziKgAkQgEornIWEMzvBKHNJbAvSGDR526LCvxBHtZuZc0DXhhfH3gVn22CyIlQLzSuI/VV4=,iv:f/h46vr8a+KG6+nu9juWQi6sCN22bvlpr1oDWvdywlY=,tag:EQmOo7ifVI1IMV01i0h+Xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
