apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - longhorn.yaml
  - traefik.yaml
  - ealenn-charts.yaml
  - bitnami.yaml
  - metallb.yaml
  - podinfo.yaml
  - k8s-at-home.yaml
  - grafana-charts.yaml
  - metrics-server-charts.yaml
  - minio-charts.yaml
  - prometheus-community-charts.yaml
  - hajimari-charts.yaml
  - jetstack-charts.yaml
  - node-feature-discovery-charts.yaml
  - fission-charts.yaml
  - timescale-charts.yaml
  - vmware-tanzu-charts.yaml
  - authentik-charts.yaml
