apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: pgo-examples-helm
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/CrunchyData/postgres-operator-examples/
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include eck-operator helm chart directory
    !/helm/install
