# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-creds
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:FYtGtI2OQA==,iv:VKmW05joEgJlt2591xRy/SEOQ5lx43Mwl9NSCcxz0y0=,tag:EAF2zyFw/qO798rAVyL+Vw==,type:str]
    admin-password: ENC[AES256_GCM,data:LPit9fmRkNjU,iv:XjyPz2Ia8S0MpoLH9j38guV+KFPBgYOV+l6uovufBdo=,tag:ycop1QLUoJodqyh5KypaIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTm5ZVWNGalB1ZFNXNm4z
            MlRjYzBqZnVDUnc2MEdteEdhanNrZlZmU0ZjCktzWlVLUjdMa3ptU2ZKU01ySnNN
            dDFhNWg1SCt3ZWtqQlVBc3pYR1hwbU0KLS0tIFhXaitGeXVuUTFxc2dyVkR1U3p2
            V3BWazVYeVJUZHNNWVNUK29lOVpEWkEKvErcFGxMTzOuACYjNmTIqri3HfQTy4j5
            ZuCBhAOTd0VL8pAKcxevhFFtVrhlvBD6T95QKOnMQkvtwM5yVAhtVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-23T01:27:21Z"
    mac: ENC[AES256_GCM,data:E7HcepW2+uvHnAteTfK+KzH+bHGAlIdHfr2rLl0wCZ27yJDPfKmPdAi5ywM2gtkKKha0WaegQGgwgFL4Wcr3bYt+1Pg6tOIf0ZvYK6dKyMdiQD6d3p5q74i9Bx1WOMJjZxP6MzmKEOpj98DdBa47tyuoDcNA5cIW7b2vzNSKFFI=,iv:Bzlz7FC4/9Jcz0dJcG+sr/H+/tOURzFVwnw2JqBf7mA=,tag:ahwU/lQD9zG//0P/0W/Hbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
