# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-creds
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:c/Uf7YgfDQ==,iv:DBAWmfgG9GSbSLg3eVUpMxq8eNMSTWdxHqR9eCgjn4Q=,tag:hb3rl0cZCI12DYuUp52cMg==,type:str]
    admin-password: ENC[AES256_GCM,data:tp9hkqVNgFJP,iv:TeB7akMLW/uyRc26nfrtqOmgmyXsP5J6qe6kLgzqTno=,tag:1SiQMqET/S0I0KBzcoqXnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UmUzOXJYUXB3MTFiQjRE
            TmdoRzB3VXNSVWVkaEJzdGFOZG50YWd5aGk4CmxOY0lSbmxtdUphT25qM0M4ZVF1
            Z2VuUW5Ob09xYjF6Njh4Z0UvbktycDgKLS0tIDBXcTdpRFNjcDc5cFliK1FnNHhs
            NmZGa0R0MlV2amt4YTJWRy9mSDNISGMKR0mZrNp/XA/DZyu2aKoNSo3VAUmg1TUO
            YnIiE5VZTteiNx+JhZ71hXUPpdG03YvejU7NMJuMDmbC5qNei1YliA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-23T23:33:54Z"
    mac: ENC[AES256_GCM,data:xfaXE8EPQdn+XTL+zI1tSwaj7d2FzaYV3sVWzIe4wfzpxH/4mZxR0xiXiGG99/l0FwKU4bRTtQaUSqalmHcQYa//CsKq7en1+0PXMQPXF7H5BW1uE6gEDzWdelwm9Xdsd4FQ9hzRMNM9joFcyyB1L+3kI+lNMEYd/Wx1VL616Yg=,iv:aeLrW5m6cmY7EUonuBi2BNOy55Fzefh94y/KNxyZj1c=,tag:Rq/G7AjwoknYBkA3H0NL5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
