---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app csi-driver-nfs
  namespace: kube-system
spec:
  values:
    kubeletDir: /var/lib/kubelet
    controller:
      replicas: 1
