apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/longhorn
  - ../base/cert-manager
    #  - ../base/mariadb
  - ../base/networking/metallb
  - ../base/networking/traefik
patchesStrategicMerge:
  - metallb-values.yaml
  - traefik-values.yaml
  - longhorn-values.yaml
  - cert-manager-values.yaml
    #  - mariadb-values.yaml
 
