apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/storage/longhorn
  - ../base/storage/velero
  - ../base/cert-manager
  - ../base/mariadb
  - ../base/networking/metallb
  - ../base/networking/traefik
  - ../base/networking/authentik
patchesStrategicMerge:
  - metallb-values.yaml
  - traefik-values.yaml
  - authentik-values.yaml
  - longhorn-values.yaml
  - cert-manager-values.yaml
  - mariadb-values.yaml
 
