apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Networking
  - ../base/cert-manager
  - ../base/cert-manager/ca-issuer # include self-signed issuer
  - ../base/networking/metallb

  # Security
  - ../base/networking/traefik
    #- ../base/networking/authelia

patchesStrategicMerge:
  # Networking
  - metallb-values.yaml
  - cert-manager-values.yaml

  # Security
  - traefik-values.yaml
