apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      version: "1.3.0"
        #  valuesFrom: 
        #    - kind: Secret
        #      targetPath: defaultSettings.backupTarget
        #      name: longhorn-minio-secret
        #      valuesKey: AWS_ENDPOINTS
        #      optional: false
  values:
    service:
      ui:
        type: LoadBalancer
        nodePort: null

    persistence: 
      defaultClassReplicaCount: 3

    ingress:
      ui:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdiPlayNetwork"
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "longhorn.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "longhorn.${SECRET_DEV_DOMAIN}"
            secretName: "longhorn-dev-domain-tls-staging"
              
    defaultSettings:
      backupTargetCredentialSecret: longhorn-minio-secret
