apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nzbhydra2-config-volume
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 64Mi

