apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname nzbhydra2
  namespace: media
spec:
  releaseName: *appname
  chart:
    spec:
      chart: *appname
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/nzbhydra2
      tag: v3.14.2
      pullPolicy: IfNotPresent
    
    env:
      TZ: ${TIMEZONE}
    
    service:
      main:
        type: LoadBalancer
        ports:
          http:
            port: 5076
    
    ingress:
      main:
        enabled: false
    
    persistence:
      config:
        enabled: false
        existingClaim: nzbhydra2-config-volume
      omoikane:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume1/omoikane
        mountPath: /omoikane
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume2/downloads
        mountPath: /downloads
