apiVersion: v1
kind: Secret
metadata:
    name: librespeed
    namespace: utilities
type: Opaque
data:
    MYSQL_PASSWORD: ENC[AES256_GCM,data:FNTm7GH9YU56x9sgD130NA==,iv:vlJ7nR/pIumsUcZAVo7/r3Kqci+Gb+6xQtqShCUzdFk=,tag:zWitFGL5UIB3a84bJ+FHRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Z3BpeVdHZzY4Yi95WmRN
            MEgyVnBPb0NWdTVVY0xITnRhSDlJeEc0b3l3CjJzSlp3RVhYTFdNU3MrSGpEbjM0
            YW5aMm1iOXJsYmlRK3ZoUDAwcGtFTEUKLS0tIE04bklET2JvTkgvTmYxYkE1Nzl0
            N2cyYnZ4S0wwM0JQMFFpRnl4Y3IyblUKZk6y4qlTe3n2lUTxYJHOSiVu0/r7YOgm
            4i4uDVhBiStlMQr3x0LdwJpk6JOxs6yieivhzZzv/RSM8tNVU9JMBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-20T23:11:10Z"
    mac: ENC[AES256_GCM,data:dMRexuiJrY/lpkHY+MunZjC8unL5+W0hl2J7en/gQceKNI6jF6OrWGQtvT9wvABysq7JxGDQPDq4R0CDuLj8aozdirq24ZG78OTkUMpCVgUFJDcg1z6fdmERoTFAKW2ZiuPZ5rKkuPTvTgJrF1AfErtFXKK8ESIFIWxxJpK1l6g=,iv:r16V20tYHqKB5BWptrOxi704CicgaktpEbkYPRp3OFs=,tag:hxz89IXRhAd7CQKU7oTXjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
