apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: networking
spec:
  releaseName: vaultwarden
  chart:
    spec:
      chart: vaultwarden
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdiPlayNetwork"
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "vault.kao.foundation"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "vault.kao.foundation"
            secretName: "vaultwarden-kaofoundation-tls-staging"

    #
    # IMPORTANT NOTE
    #
    # This chart inherits from our common library chart. You can check the default values/options here:
    # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
    #
    
    controller:
      replicas: 1
    
    image:
      repository: vaultwarden/server
      tag: 1.24.0
      pullPolicy: IfNotPresent
    
    # -- environment variables.
    env:
      TZ: "America/Los_Angeles"
    
    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        primary: true
        annotations:
          metallb.universe.tf/address-pool: dev-infra
        ports:
          http:
            port: 80
        type: LoadBalancer
        externalTrafficPolicy: Local
      websocket:
        enabled: true
        port: 3012
    
    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      config:
        enabled: true
        existingClaim: "vaultwarden-config-volume"
    
    # config -- AdGuard Home configuration. For a full list of options see https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration.
    # @default -- See values.yaml
    config_ldap: |
      bind_host: 0.0.0.0
      bind_port: 3000
      beta_bind_port: 0
      users: []
      auth_attempts: 5



    mariadb:
      enabled: false

    postgresql:
      enabled: false

