apiVersion: v1
kind: Secret
metadata:
    name: authsecret
    namespace: default
data:
    users: ENC[AES256_GCM,data:XZEfxaGQkOQgpaJ3VbmpQFwVmY8VMu1wYvSDNtivbMAf5w3bHj/vw6kC3r2khSNFiGK/YOQ5zbJ61ob04Q==,iv:nLs0ykZmZWV28I2OopKGAavzJsEg/x/WmAcrOyDDQ9E=,tag:rzQvPp4gl95O9jqnzes1Vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWDdob3VHa1ZmMzJZMWM5
            MzJQaXdjTGVPZUZCaW9PVE1pR3VQR2V6VzA0CkEya1dDa1ZrSk5MeDQ0TmlNZDhC
            bVVmM1owNmtVSG1zRy9tMEI0UTNoNk0KLS0tIFBUQkV6Q2Y1QmdqNmU2Zi9aeXo2
            R1ZnZnRQMTRLNGpjS0JYMUpSZTFBT0EKr/yl7XX/TRRQSr6iMC+CcEB5FvrwCgQF
            btsLdhXRiSMK+m4LB4TKmkY/GH8V9o1FC6p8AAGrGNYiKUBEPf/lew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-18T00:15:42Z"
    mac: ENC[AES256_GCM,data:pR2RVIkWMrEZXz+kKgZyj6iW6/GyVlDvoaSz093A6ZfynDGgJnPypoNuoufEuoZnAmBO5zuSlZMJa8iaLS3UMQGY3wSBfVjIJx6/yAU37zyWlTiQQU9Vi3Hz8s0RmPvy73ynv04wNSNbgbiLcg/5ShO0yzmL8dKdNWXlJSR9/N4=,iv:jOKAq9G71IvQxdh5JFooepc4rQq+JQADHg1QX8kpJQk=,tag:TEpZmtGJ06VRZBr8fNvAYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
