apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.4.120-192.168.4.255
      - name: prod-infra
        protocol: layer2
        addresses:
        - 192.168.4.5-192.168.4.63
      - name: dev-infra
        protocol: layer2
        addresses:
        - 192.168.5.5-192.168.5.63
