apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-config
    namespace: storage
stringData:
    postgres_username: ENC[AES256_GCM,data:a1FrW08l1WgO,iv:FFlQRq0yfoby2pdBLfqD/f9WjbKWq2zdcia/GYlFt38=,tag:DU8YHabmT02W+zNBCScvdA==,type:str]
    postgres_password: ENC[AES256_GCM,data:FuGtfrtwE+CvJGagU/0xNQxpuv7K,iv:P9CLfzXeCKV2y+oD3ufeCPdDRWxVVnyELCcmQ01kpQw=,tag:tVsJ9xKZTIqrwVGpKN7m2Q==,type:str]
    admin_username: ENC[AES256_GCM,data:aYiINJZdZQ==,iv:oePGQ1D2AGYNd4Nc9ub/FB42E6DLoUfaE3BgpjdD1p8=,tag:lJJWg7j6qOLLQHSmEabTdQ==,type:str]
    admin_password: ENC[AES256_GCM,data:6HUE7rB3I34J,iv:b4f8beQ+sYRGJP7c9qeUeicmKERnAW4a1efw77/oVNM=,tag:O0p+NmYUoXqi6yImzme/qw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUXBBKy9rcDhJaWFYY3Yy
            MUxQbmh0THNPSWxPbzVMd3ZsV0RSTVNwNGpnCmpDdjJxdFoxekVSU2l1TFVFNlBo
            Y0kyZWh2UGNKODNENTVCdU02eVBXOFkKLS0tIFdQY20yb3RlOTlnN002MktMdjcw
            VzFwR3lvS1lSM2hWVXRVN09WS0pKWm8K1GuY4fbU++juwQh+a000cVZSMWEs5ufz
            CSeUYRBOWisLJWR41fyq5yBx7e9DxRlt2L0EXe9xNCtlOxXigFEa2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-31T06:58:48Z"
    mac: ENC[AES256_GCM,data:Zv0MzyeEb6tayQRC2UvYKKAccVAhj3if5Y40r3SAF3zxH766it5/+UaCdcih/hpeel1xqYCZ2l83sOSqxCnPPvAJKz/6/QQkuvEhk6c4zRuEs0MtsKzku8M9JEW6OrnoqzrfS4to5sIdwPZM8pQuEEZCLwYCw7WuMdO837goVAg=,iv:bQ1gpEAfTaE6v7wkX4NBwDuRCKo4/jRBUtycY7zIWec=,tag:eWsFg0ugNEplnA+XbSiaWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
