apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-config
    namespace: storage
stringData:
    postgres_username: ENC[AES256_GCM,data:qfDmlpdhzhZZ,iv:x0RUHpmqpEU8L2fYA0KnR4DefVwfsv79wcQby0PqY8k=,tag:IXfsMXLtf+G5ZltEHmWxvw==,type:str]
    postgres_password: ENC[AES256_GCM,data:jq5SGaF40ocGT9x+szcJI64WREFc,iv:Q01pPgbFniU4JESZFSNiNa4P/BZI7NUN1pUZf+Y+wjc=,tag:RDhiBHLgn4d1yylohPaKVQ==,type:str]
    nextcloud-username: ENC[AES256_GCM,data:lvXAVGzwbg==,iv:GAvo98efvQwIffxQ6V0TvYxz5xDD7iQnfq7FNqVwRRg=,tag:IAml2CjZiZzWVBiT5lwuBg==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:hoGqjsRETsFK,iv:0K6GzWgckHuaBKlwqnvnWLK62yUX5CBhZ0UAZzvK2uk=,tag:p7eazrkwfFg9n2u2F9NtRg==,type:str]
    redis-password: ENC[AES256_GCM,data:FPvHgMkg6HtV9fF3jwU=,iv:CD5Ov/kaQMiwHmt51LWOk3zhi0PQXg7Qwcxn7ADUdGM=,tag:Ol9f+3ZuUAuyWTboco9rxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRG1zdWRKM0kyU2plS2Rl
            OUV5Rk5HU1RaTS9GclhKYzFTK0hqTFgrNVV3CnFGa0pLbXh2a3FTZFB6TVQxWVIy
            UmpYeXp6NXM3S01UcXMvd3RwTHpIUWsKLS0tIEhPR3orQjcxVGFOYmVUdWZqV2s3
            bFROK0VPQUJHejFTd05SbCtiYkdoZkEKbeyCbZnVmemD6duyEDJARy0OQAjXDaI3
            hAEyF4Mk893IZqphQbbsllTG5vIuZa4n6ef1hkCqE+ZsmDsXZPJOrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-24T00:04:53Z"
    mac: ENC[AES256_GCM,data:ghV/pxYiAJhSiPQziACFUZPrkzQkMeXgLTUK0dIGU5iyzwFm3HFXWhSEb0T0HzgwWn+jCdA/VPyBzLD/Kh7lE8k5xGot00WnPlJ4EGpVbHI+yjbjZge7tq9K2yXaEgRQcdKCZoZFqwVwSSCq+Gg6v3zjprYjmZmVJoxwnsu6kYY=,iv:qj1QNZDSHSBoFh1rI1mF2a4587FWmfAy/V1JpQ7Eu90=,tag:ZQkjjOzG6C4GKB55131maw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
