apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-config
    namespace: storage
stringData:
    postgres_username: ENC[AES256_GCM,data:i9UggYj43lWE,iv:Bi/h+Vr/nvfCTaM1SHV3Su9iFf2VThqouqsgu2DkPDg=,tag:KYx0u+878NGywqUFHUTuxw==,type:str]
    postgres_password: ENC[AES256_GCM,data:sBCV3K6rWHP2ZqWnDWu2JNAdzeiR,iv:BulXHxpHCnwrUq3AQYBpXy4y4ORp32zTVZqfRy4zFYU=,tag:XaQ/pXvZIHGn2INJQ3d3Tg==,type:str]
    admin_username: ENC[AES256_GCM,data:MaNoCShBRQ==,iv:mleCM15niZSwrBvbjUeiMhpGUjPQ5WjSeLQiwBl9aFM=,tag:yZGrhbTQfqwVcQbZMP8srw==,type:str]
    admin_password: ENC[AES256_GCM,data:cbRX3RajNdiT,iv:rVpmeDaj9ZpVpRrUhebAp23X/WYV5dHZQiUClqwRYsw=,tag:Apzi5+iRuaSiRMpx+mewCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMHRYa2NvLzRnMjBkbEVs
            aXNMekdYZlVLVnp4SkxCLzRPQnFHdHpxaUV3Ck55QlJwbnJJZ2YzSkRTSmRXZmdO
            V3NnRGpXU0ZhWEhHZlU1ek84VVJVLzAKLS0tIHc2Ty9peHI3M1V1OGxXUTVRWWZl
            S01sNnJjL2VKejU1bTNYKzNjVllkWVkKM5t88fAzezC+EUnhvEi4yo3LGRGNo36D
            AqKKKmoD4JkIa41+7E5NkhG/2da2unh1WB0b1Qgebqb6lJC+P5nUiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-26T03:16:00Z"
    mac: ENC[AES256_GCM,data:9Xy9hn8hWo3g1syR4r00UVRRjbe9eYiNpOuXjsApr4FA6NgKEEWgXR2Wr8+/izfcjcu0iy9ljEr1dJGUg1eYr0Ag3Hn6R5ZRnBabLXTz43dGILME3MMCaRNoCle24P+gS8RwhzyXOLGrjkO616MaQaOF2tsye6fZksrmhFSQ5gc=,iv:Tdt16pHagt71wkRfogNbYL+0ros5dR3DAPT6UTuU/k4=,tag:U4Rxo+EbxLZHpsIZXjLCZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
