apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-config
    namespace: storage
stringData:
    postgres_username: ENC[AES256_GCM,data:0kcp9ux2N858,iv:HCySJjHKTuspIJsoP5TNWQx1CBZxgIe9KMCKh1OP5OY=,tag:mcww1Coz/i0ydo8B5zet7w==,type:str]
    postgres_password: ENC[AES256_GCM,data:d/yrMDjJgmwWn+3B+h3H2GEFFYFi,iv:rrkPZTKVYtocIjaXU1y4ndZCKhas4iC8ICVdAuhk6Ws=,tag:xKkHUB15hGEYEhyZJZ8c0w==,type:str]
    admin_username: ENC[AES256_GCM,data:QmRpgvHF4g==,iv:mz5KWIJ1qtYHnsDuHKNJqnAS5AX9gVeUpgPXgEC6TXk=,tag:B06vhDlE7IEqaja8ICUotQ==,type:str]
    admin_password: ENC[AES256_GCM,data:LA6UY2LffH1w,iv:v93pVtZLzXVtHD3YWDS+YCx6XDrSzl2P69IQyB9feyw=,tag:YAKXi9V/GWcsAVNLJ709ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRHJBNnJBSlN4cTJsZTJo
            M21tUjhnalBuRW8xU05jMWs0YVM4Ky9nZno0CmhHTTJmaEswcUF1Tk9FZU5uTldm
            ZkhnQi9QVnFlR1diT0JhMVo3Y3ZhaVUKLS0tIDVsU0VVL3hFVXV3bmxCWXJMdFI2
            UlppeWFCd2VWN0FLY0FMNGZjbndtS3cKqw21A5AbW4E0x8cqPJP6y3T2uobzCxnb
            mdum+C0V8iedN+RrjcvYpLaU5r6QQaV49LrAWLZjYMQggbarXxc72g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-23T03:20:34Z"
    mac: ENC[AES256_GCM,data:1ASQazMGvJDJLFIhYAhUf2yYFhnF1I4MJDnWPFR4t3tFGg8MlzbwzHv+DXhFseYlN/1hKiBOmC+6maEwq1SHNBGw6wQlFaT6IlpPEsP1dbbdm+6s1oC3MD8houmXKWHyJt2vTHhSqNXjS8FdUvCsi5bEmkTFs3m1yjfMxDZjye0=,iv:THUv9uB/6/lrQD2ys2+mT3uKzUK5K6Tl0lFcmnPuk38=,tag:7b9V8sc7LkFebbSPYh+R2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
