apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-config
    namespace: storage
stringData:
    postgres_username: ENC[AES256_GCM,data:iE/uJYVx+IUp,iv:D8oj3+NhZdr+Od91eaehq237HgPo5psFODIeLP7xQUQ=,tag:YlgOUjgxPs8PiVGgQkPfog==,type:str]
    postgres_password: ENC[AES256_GCM,data:hWKXvMpwlC9DIoSFTk/e1nBTKnNB,iv:yeEc5KiZTJVxJToQ09/NtnVXydDP/YbznSTLMQIbER8=,tag:PyYzsURLuzjTLoLQJVzf7g==,type:str]
    admin_username: ENC[AES256_GCM,data:KrBOsFZiTA==,iv:fZOA+vNZSxpPlVjokMGkDPM1+i1/OFDDjGRlF4yLY8I=,tag:Oe0Ft/LPH19BjyttiZTsVw==,type:str]
    admin_password: ENC[AES256_GCM,data:KkXhCVyTMrR7,iv:pbcRlNvfX2UyM5u1rtk5sBEJPHfcjnnCKO3oe8BW7Bc=,tag:AnV0+2i0wcW6Ed6WE0IUdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZ21UK2R0cHZ6VmF4SzBU
            dmxXNWlqak5rdjZwMVh0a2xCYnpqRWNYcmc4CnhhMUljOFMxeXZHWE9TcGlobmZB
            ZXhYTUFjbXMyZ1ViZk41N09UYUdKQW8KLS0tIG9MZzZHQkdMa3BOYkY3MmNBdzNM
            L3MyeG5ZVU5UMjBJaWgvdmNlWHFvRXcKeWlDm/FIZS0jdNOe0S2Mqn0vGM6iGYNL
            J9+fxaIxTxK6MCHlEtrxtTUMJdju7wRpIZ40/Tz+tpDrASli3r+pjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-02T05:08:25Z"
    mac: ENC[AES256_GCM,data:BERTjmlAmZkQuL7PRLDM3lULy8r0Rvrsjcp3TnqK+9nSJZzXBFb44NR0N0xL9u2CJSSpUYvekOIJfrKe6dP5UIXkqaINo479c26na0Hicnz+jCNaMhaXHckRdZuOk3IEyCldx30XnDPGvGC7fwSCbjqP8qmJYSlpX1GMHwpzV00=,iv:cz3xbuZrIXUiMa+QKzWWoVj1CYgIKXFgaLw9VFrE0zQ=,tag:zro7yxCKw/0nSBmC9SMWTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
