apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-config
    namespace: storage
stringData:
    postgres_username: ENC[AES256_GCM,data:69ChYRBusZgd,iv:XWOzjZtgF7WmzLrjW0E5iklJPEcJTLVAv5jEi8KApQI=,tag:FHoMHNU2NDVF9xZPTWRtNA==,type:str]
    postgres_password: ENC[AES256_GCM,data:CXcuhY2gUqlQcjGs3/oMDXOoRnlo,iv:rXSFnx6nKJnesSoHSxc6N3+GqT9SmAuQHNPqn1+lXDw=,tag:Gdo6er+9TCDTyTBZjUpuNQ==,type:str]
    nextcloud-username: ENC[AES256_GCM,data:YGe/ejZubQ==,iv:63u72mH8ayabwfj7ZH4Kzvr1PfUtIkdCHPU2r9lG/7A=,tag:3bORKIPcRXk4wvbnZuibrg==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:BtPabARQWrkG,iv:GptdxeaU5jOyqLKCHEwEnUXBb7yTaUNoe5hbOr4EhJ0=,tag:Vz4RYwNZzO8zuTLg6xgIgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZzlHdEg1eHdoWURpbFFH
            V3VRd2wyVy9ySUs5ckFWOHh0ai9oVytZalhnCnAwdVA5V2M1aW41K1luc0pOcnV2
            VVRNOVM4Z3U0U1g1YW9tUEcvOXE3d1EKLS0tIGlOSENEQ1NHbmNDdjBubXVGNFpa
            QkZrdzhJMDlFWjNHdUVZc01idEdIV00K3S7Vy7qO+lzEhVwJqEb/j2k0KSPvmLuU
            R+QkXKV7wnVr5/qyqIAhHTNhMbuOm9GsqgcUuI0/5kx1rJ1cXM8cLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-02T04:40:06Z"
    mac: ENC[AES256_GCM,data:f2FHikbmsy2nwINqLoOA3LKN60lNtH9xTFB7Lzvj6dYLJtcXFmOHHSCc72icgtpCiYLXDCEane0e9REv/MwzwmYJdq30UgJKlMEUP5ynmaK1zUTKLWRYwRSA2WkoyHeKTIn2/LSni+PiRJKiAVCnc57vrrHyP9JyEZGcGhkg6fI=,iv:donrsOPux4LgwQXBO0s5ZLQCCAbdH4yJ0EHmyHVE5J8=,tag:dYXL06quS7YZllCdUOaMag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
