---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname authelia
  namespace: networking
spec:
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  interval: 15m
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.5
        env:
          - name: POSTGRES_HOST
            value: defaultpg-rw.databases.svc.cluster.local
          - name: POSTGRES_DB
            value: authelia
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
                namespace: databases
          - name: POSTGRES_USER
            value: authelia
          - name: POSTGRES_PASS
            value: authelia
    image:
      repository: docker.io/authelia/authelia
      tag: latest
    envFrom:
      secretRef:
        name:
    service:
      main:
        ports:
          http:
            port: 8083
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "bookshelf"
          hajimari.io/appName: "The Library"
          hajimari.io/group: "Media"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
            ##cert-manager.io/cluster-issuer: "ca-issuer"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
        hosts:
          - host: &uri "library.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *uri
            secretName: *uri
    persistence:
      config:
        enabled: true
        existingClaim: authelia-config-volume
      media:
        enabled: true
        existingClaim: calibre-media-volume
        namespace: media
        mountPath: /library
    resources:
      requests:
        cpu: 15m
        memory: 249M
      limits:
        memory: 299M
