apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: redis-secret
    namespace: databases
stringData:
    password: ENC[AES256_GCM,data:0YqgP7RNjUOfB8YoFq0=,iv:+590vrzNo2I0bliSrRBVAVPQSUTaNr4/vbrzT8fUWBQ=,tag:uLbLGdWGoSSH3RXL3+J0ng==,type:str]
    host: ENC[AES256_GCM,data:+VrWrXAhUjZpl/wdlGdXkn5nPUNfXMxciXekcmgquLcY7hDmY5PwvA==,iv:LunGkiu0hoRvYQcRFGq0YdgxvTTFWB7bkUO4GJeyZNQ=,tag:QF69kwP+vFrDewEJHHj4eg==,type:str]
    port: ENC[AES256_GCM,data:Q3VC3Q==,iv:xvYYe+Amkfa4eAAhdub0IfV7VD0hlCPkRL+dYxoUhB8=,tag:mMs667sg2+JNhxcuD/wbwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweUMvdlNnZG9jd2tMc1dV
            M2FFWDQycm1Dc3pnRFB3eVRMS2JNQ2F4TTNnCkJHQnBpZHNiYWRUL1paQWlUYmxX
            MVU3amJiZjlBUXpxSmJ6eXFaL0tYRmMKLS0tIE16R1ZacWE5RTBHRkN3Tk1MYTgv
            c1NVZmVGOEFRZnVsU1haT09JRDVvaHMKT5GeA+xmWDiRRdIzx2gL5vLc7CV1cY25
            I1H9BIHGR6aRrFm2MgAm591xLakZA7NKqAL9xlQqf2z36kTmuEjvXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-03T23:39:31Z"
    mac: ENC[AES256_GCM,data:Jginl/MmLnStlOBSQvVP8Lk2CtiwTS+iRbFmBK8Pbg8F3imfot06V4F+t5c1b/AiO7pOrDdgQaYDwKSJwA3gH4KVk9r5myoM/oNH85U6DjkDwPfXMFbyU2OhJ/EqJ4rjF9PYMuWQ4zghTgZeEyz2kwlc4G57OerOhEuehgw4Hh4=,iv:qd2Agsyl0u2YBH4jCKMMxMfLfS9mqjdmKwVLP4PHzmQ=,tag:2G8SrmLBiTarhc6dFN+4Ig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
