apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: redis-secret
    namespace: databases
stringData:
    host: ENC[AES256_GCM,data:8ph5Uu+RmO88TfQYrP+UFyD+st61tQsx3zB8nY/VWru9PQYzJdTRwQ==,iv:/Cec8zwCzelDAp8FEk7cjMp0+a1pWt98CPzt0IJAZkY=,tag:awQNHM4sjbOl/wZctj9NDw==,type:str]
    port: ENC[AES256_GCM,data:xWKi3w==,iv:4dAbRVj8vy1fEBl6TQcnpvSC3tUEuK7v1qy6BHg+mXA=,tag:7wdSYjB/+IA7FTplS2MAJQ==,type:str]
    password: ENC[AES256_GCM,data:i1DbN5GoQ6syvjP+1+Q=,iv:OrQ8myGciJ+0WxucdY97pJknXLBYH4HfhwQZdHbTOT4=,tag:Ec1fPzX+OK2uJe3g8eRx/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYS08zK0crMFFrQzJlaERu
            UHAvQTNDS25nT0FTMHlZN2NVNGltSm9rYzNJClo5dkRoOEZmckplaDZYVVkxcjNL
            U0p1V3h4US9zQlpNUWdrREw2Zi9XT1EKLS0tIDJ2cFNHc08yNlVyZmFiS0JjWkVs
            VDRzN1RvR1pxVnZ1QnVKazRCdGM0TmcKxMaz9RT7ddPZk7eRtFZpFFOcZPS0YuQA
            ngYLK25LdyoYPabbeoLLfRbmbawN2gPb10B4HNGZ7XpLDCEwvxFaDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-21T22:25:58Z"
    mac: ENC[AES256_GCM,data:WFmZOWmset+XmKipBlO0alsKkfOrhQjRylxQd3zMT0WCgLodrbuPlffrWXFVRB/+Kaoo/paf+Mye4W6r99aLEGKJf+x6sp9Ty5fRNEIcoGY/CajPRapITy8EGRpnZY/XFg7fZnss3TDttLVn07ltGjr0ELYHrovRixFtrAqSqzM=,iv:x76nzP+YQJ9cdH23TdqBsQGJF6P2KImmKJCo3qQ4KOA=,tag:8ckD2Nm9lmu5zXC2Vyv2iA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
