---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-pvc
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: local-path
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi
