apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  releaseName: radarr
  chart:
    spec:
      chart: radarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    podLabels:
      app: radarr
    podSecurityContext:
      fsGroup: 568

    image:
      repository: ghcr.io/k8s-at-home/radarr-develop
      #tag:  v4.0.5.5981
      pullPolicy: IfNotPresent
    
    # -- environment variables.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: "${TIMEZONE}"
    
    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 7878
        type: ClusterIP
    
    persistence:
      config:
        enabled: true
        existingClaim: "radarr-config-volume"
    
      omoikane:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume1/omoikane
        mountPath: /omoikane
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume2/downloads
        mountPath: /downloads
#      downloads-k3s:
#        enabled: true
#        type: custom
#        volumeSpec:
#          nfs:
#            server: ${NAS_ADDR}
#            path: /volume2/downloads-k3s
#        mountPath: /downloads-k3s

