apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metube
  namespace: media
  label:
    app: metube
spec:
  releaseName: metube
  chart:
    spec:
      chart: metube
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 5m
  values:
    labels:
      app: metube
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdiPlayNetwork"
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "dl.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "metube.${SECRET_DEV_DOMAIN}"
            secretName: "metube-devdomain-tls-staging"

    image:
      repository: tccr.io/truecharts/metube
      tag: v2022-04
      pullPolicy: IfNotPresent
    
    env:
      OUTPUT_TEMPLATE: "%(title)s.%(ext)s"
      YTDL_OPTIONS: "{}"
    
    service:
      main:
        ports:
          main:
            port: 8081
        type: ClusterIP
              
    persistence:
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume2/downloads-k3s
        mountPath: /downloads

