apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- ./dashboards/hajimari
  - ./diagnostics/podinfo
  - ./diagnostics/echo-server
  - ./utilities/smokeping
  - ./utilities/firefox
  - ./utilities/pgadmin
  - ./utilities/ltb-project
  #- ./utilities/vaultwarden_ldap
  #- ./utilities/vaultwarden
  - ./media/metube
  - ./media/sonarr
  - ./media/radarr
    #- ./media/bazarr
    #- ./media/tautulli
  - ./media/outline
  - ./media/invidious


  - ./home/mealie
    #- ./monitoring/prometheus-stack
  - ./monitoring/grafana
    #  - ./monitoring/loki
    #- ./monitoring/tobs

  - ./networking/traefik
    #- ./networking/unifi-controller
    #- ./authentication/authelia
    #
  - ./databases/cloudnative-pg
  - ./databases/cloudnative-pg/clusters
  - ./databases/redis
  - ./databases/redis-operator

  - ./storage/kopia-web
  - ./storage/nextcloud

  - ./kube-tools/system-upgrade
  - ./koube-tools/kyverno
