apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./dashboards/hajimari
  - ./diagnostics/podinfo
  - ./diagnostics/echo-server
  - ./utilities/smokeping
  - ./utilities/firefox
  - ./utilities/pgadmin
  #- ./utilities/minio
  - ./media/metube

    #  - ./monitoring/prometheus-stack
    #  - ./monitoring/grafana
    #  - ./monitoring/loki
    #- ./monitoring/tobs

  - ./networking/traefik
    #- ./authentication/authelia
    #
  - ./databases/cloudnative-pg
  - ./databases/cloudnative-pg/clusters
