apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname magicmirror
  namespace: home
spec:
  interval: 20m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  # See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:

    image: 
      repository: karsten13/magicmirror
      tag: v2.24.0

    env:
    - name: DEBUG
      value: "true"

    command:
      - /opt/magic_mirror/entrypoint.sh
      - npm
      - run
      - server

    persistence:
      config-js:
        enabled: true
        type: configMap
        name: mm-config-js
        subPath: config.js
        mountPath: /opt/magic_mirror/config/config.js

    service:
      main:
        type: LoadBalancer
        ports:
          http:
            port: &port 8080

    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: eos-icons:ai
          hajimari.io/info: Local AI
          hajimari.io/group: home
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
        hosts:
        - host: &uri mm.${SECRET_DEV_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
            - *uri
          secretName: *uri
    
    nodeSelector:
      node-role.kubernetes.io/worker: "true"

    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        memory: 2000Mi


    modules:
      install:
        - "https://gitlab.com/khassel/MMM-RepoStats"
        - "https://github.com/jalibu/MMM-RAIN-MAP"

    config: |
      language: "en",
      locale: "en-US",
      logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
      timeFormat: 24,
      units: "metric",
      modules: [
        {
          module: "alert",
        },
        {
          module: "updatenotification",
          position: "top_bar"
        },
        {
          module: "clock",
          position: "top_left"
        },
        {
          module: "calendar",
          header: "US Holidays",
          position: "top_left",
          config: {
            calendars: [
              {
                symbol: "calendar-check",
                url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"					}
            ]
          }
        },
        {
          module: "compliments",
          position: "lower_third"
        },
        {
          module: "weather",
          position: "top_right",
          config: {
            weatherProvider: "openweathermap",
            type: "current",
            location: "New York",
            locationID: "5128581", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
            apiKey: "YOUR_OPENWEATHER_API_KEY"
          }
        },
        {
          module: "weather",
          position: "top_right",
          header: "Weather Forecast",
          config: {
            weatherProvider: "openweathermap",
            type: "forecast",
            location: "New York",
            locationID: "5128581", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
            apiKey: "YOUR_OPENWEATHER_API_KEY"
          }
        },
        {
          module: "newsfeed",
          position: "bottom_bar",
          config: {
            feeds: [
              {
                title: "NPR",
                url: "https://feeds.npr.org/"
              }
            ],
            showSourceTitle: true,
            showPublishDate: true,
            broadcastNewsFeeds: true,
            broadcastNewsUpdates: true
          }
        },
      ]
    
