apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    defaultRules:
      rules:
        kubelet: false
    kubelet:
      enabled: false
    prometheusOperator:
      kubeletService:
        enabled: false
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    prometheus:
      prometheusSpec:
        replicas: 1
        shards: 1
        retention: 15d
        podMonitorNamespaceSelector: {}
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring
      ingress:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - &host "prometheus.${SECRET_DEV_DOMAIN}"
        tls:
          - hosts:
              - "prometheus.${SECRET_DEV_DOMAIN}"
            secretName: "prometheus-devdomain-tls-staging"
    enabled: false
