apiVersion: v1
kind: Secret
metadata:
    name: ltb-secret
stringData:
    SECRET_LTB_KEYPHRASE: ENC[AES256_GCM,data:PuYDxhWMnC8qbi181oDPpStDKHLDJyiyGzbGsh0HyvxW18fnAE1D0DkkyzLNCJh5SThNk7BFHw==,iv:n28by+5UBCx54VSMcjn1q7gtKFxOQCUSbjaj/rk2XS0=,tag:qihaPxN9Jat/tOXqw6WN+A==,type:str]
    SECRET_LTB_SMTP_USER: ENC[AES256_GCM,data:JO/GTcjO7DLlW/aKTDsorf35yow=,iv:ompAhmgrUnfGjBULQE3eiRDXbQ7YPErLq7qimitNxIQ=,tag:Wl6uiBQpyTyOF/uzyKR18Q==,type:str]
    SECRET_LTB_SMTP_PASSWORD: ENC[AES256_GCM,data:dyN/H+hZmQvWt1r3Ckp9iQ/adWRdb7KID1FX0WGI1MEknO+Xq5HoXPTBYjs=,iv:MYIQwBUfxkycGVZ6Yz0vwU8bIaPUNnDOD7+fOM3PWQc=,tag:DEDLcdv9+XScuYRQTx8P4A==,type:str]
    SECRET_LTB_SMTP_HOST: ENC[AES256_GCM,data:9wmTENZCzVILRQSK+2U+0BSl2WbYPPKNb09EU6nWaKXi6A==,iv:UntQU65A+Ur3lUI+RcMpgR0zWTdIdzDB6pR7+AmkTZU=,tag:sR6T1KicdKaTcDPEf2AFWg==,type:str]
    SECRET_LTB_SMTP_MAIL_FROM: ENC[AES256_GCM,data:w5t9y3xdR0vuZYok1Q27TL0Xrw==,iv:rN8i9HHBswwn1PhLL9LvoefoIXEYLDo35FNodqIO2fE=,tag:y07eDUcvl6I4X6G4ZE/uCA==,type:str]
    SECRET_LTB_SMTP_MAIL_FROM_NAME: ENC[AES256_GCM,data:Nch/wrEv9trqn42deI/2AqclKe8XGlLrXMa59glieb3aY4dog+Ce,iv:6YUgdR8+3I6eHTm1U6E+TkOS0jyQS06SfIY9+cQzQ4o=,tag:PUFxbRLz2GzyYE1kbYS21Q==,type:str]
    SECRET_LTB_PASSWORD_RESET_URL: ENC[AES256_GCM,data:GGJn3B2q6gBzPRFVAViXriIaDvVG3cddttVoo+rWzBEKp0i61w==,iv:2s8m8wPH3qST3/noq+zrlaqGQN79SgCihW2FSdUbsTY=,tag:p/tERgsaukNJ+3ksUDGA6A==,type:str]
    SECRET_LTB_LDAP_PASSWORD: ENC[AES256_GCM,data:KY7G9T04LGxeMFA4jUk=,iv:9xEf5ZrioO16gLST7TZkySXV4xzvpTIKpciR+L8Ro0o=,tag:LpKlgCq2wMxAfWCJkS9TkQ==,type:str]
    SECRET_LTB_LOGO: ENC[AES256_GCM,data:Mn76sIHILh5qbQMDL4wwvtBLUp9blA==,iv:VPJQZ5bT4uoZuXISXjNCV5opyVTJUz2uOtHEHBhK5+U=,tag:aHTbeTQh5aJgCb0CZxkm+w==,type:str]
    SECRET_LTB_LDAP_BINDDN: ENC[AES256_GCM,data:yOrClaiYWf2w4C5NsJXRnuhJw4rNZ237GZC8q73r6TFh6H/TbNB6,iv:vtWnD6hDaTyrf8lHAug5h0D4qoGWC1BR6PDm+NbSQZw=,tag:28pMS4WnO/ESgyPqV/6phA==,type:str]
    SECRET_LTB_LDAP_BASE: ENC[AES256_GCM,data:CciTz7ijYfNgOoWibnPmVg==,iv:cdclHkdR/tbpxtsVtS9bQZQfhYoLgcuNKxig9q5Zz/A=,tag:/aMmWzwxTOiqCcTXupnTFA==,type:str]
    SECRET_DEV_DOMAIN: ENC[AES256_GCM,data:JNEfqWwVxK6pj0o2lNn2XaEJSkc=,iv:ZwBzHy8wh8YoCXyzJJUgbYfl49lfNnILuancXJMeaz8=,tag:S0uhWQyBiTcBcXXof+Vx1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rr569v9jm7ck70q4wpnspfhdvt4y5m6s604tx0ygs0a65qkt7g4qdszk6k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQmRhdnJMVDNxVEd2VmtV
            c2svelMzWnB1U3AxZms5eFNqZHZPUUl4TkNJCjloVnQ1VXpMelI2aWtJakJXUEg3
            UTgyTWV0WERhM2x1UTZGbFhKdmF4dm8KLS0tIDJhaDA1cjB0TXlXS2dwWkx5ZjQz
            aGRxTEpsSnFnTTNKeFh5T3A4SWFRUFEKaRt46LAHdkf+9yGox7RjGGANf5qmFkQO
            WCPmql08c4xWQod4ZDJUg0p7yjlFzrWkC5T0E2qFobzK1zd+v6E5/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-10T06:36:38Z"
    mac: ENC[AES256_GCM,data:mg/pGm+xZCdBoKIelhPbHjnxz29j5nLnnS0oU3Rdggt5sqAX9n+vm8KE1AAEa6HTCuLljmefVrWtsAmaKhqbSRTfTUuLKvD/c3EtHDwMqbstX0YKIQHZLYGGlBEEMRbJ+ydxZSrHcjuLb6e4eSz5bH6KPhEZOmkimYLDWub6FIE=,iv:edf/Z1aeHoOAHpDWOuC++DPjLhJ94wRL1wxE2e12sdI=,tag:TIdNr5KeTX27EBxoDNfmvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
