#apiVersion: v1
#kind: Pod
#metadata:
#  name: bookstack
#  namespace: media
#spec:
#  containers:
#  - name: bookstack
#    image: ghcr.io/linuxserver/bookstack
#    lifecycle:
#      postStart:
#        exec:
#          command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname bookstack
  namespace: media
spec:
  chart:
    spec:
      version: "5.1.2"
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "book-open-page-variant"
          hajimari.io/appName: "Wiki"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
            #cert-manager.io/cluster-issuer: "ca-issuer"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: &uri "w.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *uri
            secretName: *uri
    service:
      main:
        type: LoadBalancer 
---
