apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - ingress.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: test123
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
