---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maraidb-data-volume
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
---
