apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: guacamole-config-volume
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: longhorn
    resources:
        requests:
            storage: 256Mi

