apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pvc.yaml
    #- helm-release.yaml
    #- configmap.yaml
configMapGenerator:
  - name: guacd-cm
    files:
      - entrypoint.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
