---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app guacamole
  namespace: utilities
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: docker.io/guacamole/guacamole
      tag: 1.4.0
    env:
      TZ: "${TIMEZONE}"
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: 192.168.0.125
      MYSQL_PORT: 3306
      MYSQL_DATABASE: guacamole
      MYSQL_USER: guacuser
      MYSQL_PASSWORD: qvNc9mYV1k4Do2VXjvpExiq5Qyvd6G
      #EXTENSIONS: auth-totp
      GUACAMOLE_HOME: /config
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "alpha-s-circle-outline"
          hajimari.io/group: "Media"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
            ##cert-manager.io/cluster-issuer: "ca-issuer"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
        hosts:
          - host: &uri "guac2.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *uri
            secretName: *uri
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: guacamole-config-volume
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 1200Mi

    additionalContainers:
      guacd:
        name: guacd
        image: docker.io/guacamole/guacd:1.4.0
        env:
          TZ: "${TIMEZONE}"
        service:
          main:
            ports:
              http:
                port: &port 4822
