#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: tcp-services
#  namespace: defaultpg-ingress
#data:
#  5432: databases/defaultpg-rw:5432
---
apiVersion: v1
kind: Service
metadata:
  name: defaultpg-ingress
  namespace: databases
  labels:
    app.kubernetes.io/name: defaultpg-ingress
    app.kubernetes.io/part-of: defaultpg-ingress
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: defaultpg-ingress
    app.kubernetes.io/part-of: defaultpg-ingress
