apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: sonarr-config-volume
    podLabels:
      app: sonarr
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: longhorn
    resources:
        requests:
            storage: 1Gi

