apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  releaseName: sonarr
  chart:
    spec:
      chart: sonarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    podLabels:
      app: sonarr 
#    ingress:
#      main:
#        enabled: true
#        ingressClassName: "traefik"
#        annotations:
#          hajimari.io/enable: "true"
#          hajimari.io/icon: "mdiPlayNetwork"
#          cert-manager.io/cluster-issuer: "letsencrypt-staging"
#          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
#        hosts:
#          - host: "sonarr.${SECRET_DEV_DOMAIN}"
#            paths:
#              - path: /
#                pathType: Prefix
#        tls:
#          - hosts:
#              - "sonarr.${SECRET_DEV_DOMAIN}"
#            secretName: "sonarr-devdomain-tls-staging"

    image:
      repository: ghcr.io/k8s-at-home/sonarr-develop
      tag: v3.0.7.1479
      pullPolicy: IfNotPresent
    
    # -- environment variables.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: "${TIMEZONE}"
    
    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 8989
        type: ClusterIP
    
    persistence:
      config:
        enabled: true
        existingClaim: "sonarr-config-volume"
    
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume1/media
        mountPath: /media-nfs
      downloads-k3s:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume2/downloads-k3s
        mountPath: /downloads-k3s
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume2/downloads
        mountPath: /downloads

