apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname changedetection-io
  namespace: utilities

spec:
  releaseName: *appname
  chart:
    spec:
      chart: *appname
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
   
    service:
      main:
        primary: true
        annotations:
          metallb.universe.tf/address-pool: dev-infra
        ports:
          http:
            port: 5000
        type: LoadBalancer
        externalTrafficPolicy: Local

    image:
      repository: ghcr.io/dgtlmoon/changedetection.io
      tag: "0.39.4"
      pullPolicy: IfNotPresent
    
    env:
      TZ: ${TIMEZONE}
    
    ingress:
      main:
        enabled: false
    
    persistence:
      data:
        enabled: true
        mountPath: /datastore
        existingClaim: changedetection-data-volume
