apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: utilities
spec:
  chart:
    spec:
      version: "5.1.0"
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdiPlayNetwork"
          #cert-manager.io/cluster-issuer: "letsencrypt-staging"
          cert-manager.io/cluster-issuer: "ca-issuer"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "vault.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
        tls:
          - hosts:
              - "vault.${SECRET_DEV_DOMAIN}"
            secretName: "vaultwarden-devdomain-tls-staging"
