apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: media
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: bookstack
      app.kubernetes.io/name: bookstack
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: bookstack
        app.kubernetes.io/name: bookstack
    spec:
      containers:
        volumeMounts:
        - name: bookstack-env
          mountPath: /config/www
      volumes:
      - name: bookstack-env
        projected:
          sources:
          - configMap:
              name: bookstack-config
