apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      version: "6.33.0"
  values:
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "chart-scatter-plot-hexbin"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - &host "grafana.${SECRET_DEV_DOMAIN}"
      tls:
        - hosts:
            - *host
          secretName: *host
    grafana.ini:
      #auth:
      auth.basic:
        enabled: true
      auth.anonymous:
        enabled: true
        #org_name: HomeOps
        org_id: 1
        org_role: Viewer
