apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      version: "6.31.0"
  values:
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "mdiPlayNetwork"
        #cert-manager.io/cluster-issuer: "letsencrypt-staging"
        cert-manager.io/cluster-issuer: "ca-issuer"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - &host "grafana.${SECRET_DEV_DOMAIN}"
      tls:
        - hosts:
            - *host
          secretName: *host
    grafana.ini:
      auth:
        signout_redirect_url: "https://authelia.${SECRET_DEV_DOMAIN}/logout"
        oauth_auto_login: false
      auth.generic_oauth:
        enabled: true
        name: Authelia
        client_id: grafana
        client_secret: "${SECRET_GRAFANA_OAUTH_CLIENT_SECRET}"
        scopes: "openid profile email groups"
        empty_scopes: false
        auth_url: "https://authelia.${SECRET_DEV_DOMAIN}/api/oidc/authorization"
        token_url: "https://authelia.${SECRET_DEV_DOMAIN}/api/oidc/token"
        api_url: "https://authelia.${SECRET_DEV_DOMAIN}/api/oidc/userinfo"
        login_attribute_path: preferred_username
        groups_attribute_path: groups
        name_attribute_path: name
        use_pkce: true
      auth.generic_oauth.group_mapping:
        role_attribute_path: |
          contains(groups[*], 'admins') && 'Admin' || contains(groups[*], 'people') && 'Viewer'
        org_id: 1
      auth.basic:
        enabled: false
        # disable_login_form: false
      auth.anonymous:
        enabled: true
        #org_name: HomeOps
        org_id: 1
        org_role: Viewer
