apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Utilities Namespace
  - ../base/diagnostics/podinfo
  - ../base/diagnostics/echo-server

  # Monitoring Namespace
  #- ../base/monitoring/prometheus-stack
  #- ../base/monitoring/grafana
  #- ../base/monitoring/loki
  #- ../base/monitoring/tobs

  # Default Namespace
  - ../base/dashboards/hajimari

  # Media Namespace
  - ../base/media/sonarr
  - ../base/media/radarr
  - ../base/media/nzbget
  - ../base/media/bookstack
    #  - ../base/media/metube

  # IOT Namespace
  - ../base/iot/mosquitto
  - ../base/iot/nodered

  # Utilities Namespace
  - ../base/utilities/vaultwarden
  - ../base/utilities/uptimekuma


patchesStrategicMerge:
  #- podinfo-values.yaml
  #- echoserver-values.yaml
  - mosquitto-values.yaml

  # Media Namespace
  #- bookstack-values.yaml
  - sonarr-values.yaml
  - radarr-values.yaml
  - nzbget-values.yaml

  # Default Namespace
  - hajimari-values.yaml
  - vaultwarden-values.yaml

  # Monitoring Namespace
  #- prometheus-stack.yaml
  #- grafana-values.yaml
  #- tobs-values.yaml

  # Utilities Namespace
  - uptimekuma-values.yaml

  # Home Automation Namespace
  - nodered-values.yaml
