apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack 
  namespace: monitoring
spec:
  chart:
    spec:
      version: "2.x"
  values:
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: networking-chain-no-auth@kubernetescrd
      hosts:
        - &host "loki.${SECRET_DEV_DOMAIN}"
      tls:
        - hosts:
            - *host
          secretName: *host
