apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname nodered
  namespace: iot
spec:
  chart:
    spec:
      version: "10.3.2"
  values:
    image:
      tag: 3.0.2 
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        name: "Node-RED"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "resistor-nodes"
          hajimari.io/appName: "Node-RED"
          hajimari.io/group: "IOT"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          #cert-manager.io/cluster-issuer: "ca-issuer"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
        hosts:
          - host: &uri "nodered.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
            - *uri
            secretName: *uri
