apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &appname podinfo
  namespace: utilities
spec:
  chart:
    spec:
      version: "6.2.0"
  test:
    enable: false
  values:
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "alpha-p-box"
        hajimari.io/group: "Utilities"
        #cert-manager.io/cluster-issuer: "letsencrypt-staging"
        cert-manager.io/cluster-issuer: "ca-issuer"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: networking-chain-authelia@kubernetescrd
      hosts:
        - host: &uri "podinfo.${SECRET_DEV_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
          - *uri
          secretName: *uri
