apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      version: "38.0.2"
  values:
    admissionWebhooks:
      enabled: false
      patch:
        enabled: false
