apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  chart:
    spec:
      version: ">=1.0.0"

  values:
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          #cert-manager.io/cluster-issuer: "letsencrypt-staging"
          cert-manager.io/cluster-issuer: "ca-issuer"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "sonarr.${SECRET_DEV_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "sonarr.${SECRET_DEV_DOMAIN}"
            secretName: "sonarr-devdomain-tls-staging"
