apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nodered
  namespace: homeautomation
spec:
  releaseName: nodered
  chart:
    spec:
      chart: node-red
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  values:
    #image:
    #  repository: node-red/node-red-docker
    #  tag: v2.2.2
    #  pullPolicy: IfNotPresent
    
    # -- environment variables.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: "${TIMEZONE}"
      # -- Node.js runtime arguments
      NODE_OPTIONS:
      # -- Setting to `true` starts Node-RED with the projects feature enabled
      NODE_RED_ENABLE_PROJECTS:
      # -- Setting to `true` starts Node-RED in safe (not running) mode
      NODE_RED_ENABLE_SAFE_MODE:
      # -- Location of the flows configuration file.
      # If you set `FLOWS: ""` then the flow file can be set via the `flowFile` property in the `settings.js` file.
      FLOWS: flows.json
    
    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 1880
        type: ClusterIP
    
    persistence:
      data:
        enabled: true
        existingClaim: "nodered-config-volume"
